### ISSUE TITLE
possible things to strategically de-flexify for next major release

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#103]
Some things are so flexible that they give us headaches; here's the start of a list of things that might usefully be removed in the 4.0 release:

- As discussed in #101, a mutation's origin_generation need not actually be the mutation's generation of origin. This could be problematic, since the time information is used to determine genotypes in tree sequences.

**Comment by bhaller** [comment]
Also mentioned there, I think: we allow the user to use addSubpopSplit() to make a new p2 from p1, and then to make a new p3 from p2, all in a single generation.  To do this, we have to use fractional time values in the tree-sequence code so the later children have a later timestamp than the earlier children.  Do we actually want to allow this in SLiM at all?  It would simplify the code and the mental model if we just disallowed it.

**Comment by petrelharp** [comment]
Right - anything that a WF model can do should make sense for annual plants, and p1->p2->p3 doesn't.

**Comment by bhaller** [comment]
I think we should just turn pedigree tracking on always; the overhead is very low, and testing whether pedigree recording is on or not all over the code base is messy and is also slow (since it's a branch point that interferes with CPU pipelining).

**Comment by bhaller** [comment]
I'm not sure any of this needs to wait for 4.0; these are fairly minor shifts really.  I'm inclined to roll them into 3.5; but I'll wait until the tskit PR has been merged, since there would be merge conflicts with the changes discussed here.

**Comment by bhaller** [comment]
We should require treeSeqOutput() to be called from either early() or late(), not from any other point in the script, to simplify management of time issues in pyslim.

**Comment by bhaller** [comment]
Related to getting rid of the first-gen stuff: we should now state clearly in the doc that first-gen individuals will not be in the individuals table unless a call to treeSeqRememberIndividuals() is made.  The discussion of first-gen individuals in the doc needs to be revised in general now, I think; the discussion of simply-vs-no-simplify in Python presumably needs revision.  (I'm lumping this in with "de-flexifying" because why not.)

**Comment by petrelharp** [comment]
Oh, right - that's a major TODO for the pyslim release.

**Comment by bhaller** [comment]
I'm going to use the rocket to mark items I have done.  (Which might not be pushed up to GitHub yet.)

**Comment by bhaller** [comment]
> Also mentioned there, I think: we allow the user to use addSubpopSplit() to make a new p2 from p1, and then to make a new p3 from p2, all in a single generation. To do this, we have to use fractional time values in the tree-sequence code so the later children have a later timestamp than the earlier children. Do we actually want to allow this in SLiM at all? It would simplify the code and the mental model if we just disallowed it.

So, I'm not sure any real simplification can be done here.  Even for the first call to addSubpopSplit() in a given generation we add the fractional offset to the time counter, and I think we probably need to, otherwise the split population would get marked with the same timestamp as the population it's splitting off from, or the next child generation of the split population would get marked with the same timestamp as the split population.  (Which one happens depends on whether addSubpopSplit() is called in an early() or late() event, I think.)  I haven't tested this, but I think it's true.  We could outlaw p1->p2->p3 splits if we wanted to, but it wouldn't buy us any code simplification at all, and allowing them isn't actually causing us any trouble.

The fundamental problem is that addSubpopSplit() is, semantically, an instantaneous action – split off a new subpopulation *now* – where it ought to be what I call a "future request" – next time you generate offspring, make a new subpop that derives from this existing subpopulation.  That's a tactical error that dates back to SLiM 1, but it's pretty set in stone now.

So I move that this item be stricken from the to do list.

**Comment by bhaller** [comment]
> We should require treeSeqOutput() to be called from either early() or late(), not from any other point in the script, to simplify management of time issues in pyslim.

This appears to already be the case.  I forget where this item came from; were you seeing a problem related to this, somehow?  I'm going to mark it rocket for now; I don't see how this could happen.

**Comment by bhaller** [comment]
OK, I think everything on this list is done, apart from the first_gen doc changes, which are really unrelated to this bug, and are now on my own local to-do list.  If you concur with my comments above, then let's close.

**Comment by petrelharp** [comment]
>  were you seeing a problem related to this, somehow?

No - I assert()'ed it in the code, and you commented that you thought others were possible.

**Comment by bhaller** [comment]
> > were you seeing a problem related to this, somehow?
> 
> No - I assert()'ed it in the code, and you commented that you thought others were possible.

Ah!  OK, then I guess I checked and we're OK.  :->
