### ISSUE TITLE
Compiling with cmake 3.11

### ISSUE THREAD

**Issue by jydu** [MesserLab/SLiM#113]
Hi there,

Just leaving that here in case it might be useful:
In order to compile with more recent version of CMake (like on the latest Ubuntu for instance), you need to add the following in the CMakeList.txt file (before find_package(openGL):

```
if(POLICY CMP0072)
    cmake_policy(SET CMP0072 NEW)
endif()
```
Cheers,

Julien.

**Comment by bhaller** [comment]
Hi!  It builds no problem for me on Ubuntu 18.04 LTS and 20.04 LTS, both just updated to the latest this morning.  Are you on a more recent version than 20.04 LTS?  Can you provide more details on the error you get, exactly?  I'm not sure that I can add what you suggest to CMakeList.txt, because it looks like it changes a CMake policy from OLD to NEW, and OLD is probably required to build on most people's machine right now, if I understand the description of the policy correctly.  Anyway, I can leave this issue open in case it is helpful to others, and perhaps someone who knows more about this than I do can shed light on how to do this safely without breaking anybody's build...?

**Comment by bhaller** [comment]
For reference, here the CMake doc on this policy: https://cmake.org/cmake/help/latest/policy/CMP0072.html

**Comment by jydu** [comment]
Hi,

I have a 20.04 LTS up to date with cmake 3.16.3. The problem only arises when trying to build SlimGUI. Here is the message it gives:
```
Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  CMakeLists.txt:152 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
```
This message can be suppressed by adding the code I mentioned before. When running slimgui, I had a black window and an error message infinitely looping in the terminal. I initially thought this was due to using the legacy openGL libraries... After some extra check it does not seem to be the case, because after recompiling against libGL.so (OLD) instead of libOpenGL (NEW) SlimGUI seems to be working. So this was supposedly two independent issues (one being just a warning and the other might be due to my configuration). Sorry for the bother!

**Comment by bhaller** [comment]
Got it.  If you're getting the black window running under WSL in Windows, that might be a known issue with Xming; use VcXsrv instead.  See the manual section 2.4.5.  And yes, it looks like you have two versions of GL installed, which I don't think is the case for Ubuntu 20.04 LTS "out of the box"; it must be a consequence of some other installs you did.  But AFAIK the warning is just a warning, and can be ignored.  Good luck!
