### ISSUE TITLE
Error while trying to compile QtSLiM

### ISSUE THREAD

**Issue by eburgueno** [MesserLab/SLiM#115]
I tried using both `cmake && make` and `qmake && make`, but both fail at this step

```
Scanning dependencies of target QtSLiM_autogen
[ 47%] Automatic MOC and UIC for target QtSLiM
[ 47%] Built target QtSLiM_autogen
make[2]: *** No rule to make target '/opt/SLiM/QtSLiM/recipes/Recipe 16.15 - Implementing a Wright?Fisher model with a nonWF model.txt', needed by 'QtSLiM_autogen/UXQW7GK73I/qrc_recipes.cpp'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:120: CMakeFiles/QtSLiM.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
Here is my build environment:
```
# cat /etc/issue
Ubuntu 20.04.1 LTS \n \l

# qmake --version
QMake version 3.1
Using Qt version 5.12.8 in /usr/lib/x86_64-linux-gnu
```

I tried both the `SLiM.zip` file from the official site as well as the latest `v3.4.tar.gz` tagged release from GitHub.

**Comment by bhaller** [comment]
Yes, this was an issue with 3.4 with certain toolchains.  If you want to build QtSLiM, I'd recommend just using the current GitHub head, which fixes this bug.  If you don't want to do that, you can try to fix it yourself; the issue is that your system doesn't like an "en dash" dash that found its way into the filename in "Wright–Fisher"; systems/toolchains that don't understand Unicode filenames don't like that.  Fix the filename and the corresponding entry in the resource file and your build should work.  But if you're not conversant with this sort of thing, it's probably simpler to just build the GitHub head.
