### ISSUE TITLE
Invalid filname for windows filesystems: `QtSLiM/recipes/Recipe 17.4 ...`

### ISSUE THREAD

**Issue by grahamgower** [MesserLab/SLiM#116]
It seems that windows doesn't allow filenames containing double quotes.
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions

Attempting to clone the repository on windows produces the following:
```
Cloning into 'SLiM'...
error: invalid path 'QtSLiM/recipes/Recipe 17.4 - Detecting the "dip in diversity" (analyzing tree heights in Python) I.txt'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by bhaller** [comment]
I'll fix this, since of course it's easy to do so, but Windows is not a supported platform.  Since people report no problems checking out SLiM under the WSL, it looks like the GH Action you're setting up is doing the checkout of the sources outside of the WSL.  But anyway, easy to fix so I'll fix it, and maybe the rest of the GH Action will happen inside the WSL even if the checkout doesn't?

**Comment by grahamgower** [comment]
Ah yes, it looks like there are some hoops to jump through to enable and use WSL on github actions. I'm not suggesting you should spend your energy supporting Windows, but not being able to clone the repository would be a significant barrier to any vollunteer that wanted to try. At the very least, the github action could be configured to do non-build things for windows to catch any such recurrence of this. It's up to you though!

**Comment by bhaller** [comment]
Yes, makes sense.  :->
