### ISSUE TITLE
checkCoalescence not documented in initializeTreeSeq()

### ISSUE THREAD

**Issue by hyanwong** [MesserLab/SLiM#138]
The `initializeTreeSeq()` method apparently has a parameter `checkCoalescence` but the inline help in SLiMgui doesn't say what it does.

**Comment by bhaller** [comment]
It is documented.  Note that to search for information on a parameter, rather than a call name or class name, you need to switch the find window from "headers" to "content".

**Comment by hyanwong** [comment]
Sorry for the noise @bhaller - oddly, it's in the Pages doc you sent me, but not in the documentation within the (recently downloaded) SLiMgui app, so I guess it's a recent doc change that simply hasn't made it into the GUI app yet?

By comparison to the pages doc, it should be immediately above the para starting "The runCrosschecks parameter" - screenshot below to show it's missing on my OS X version of the GUI app help files

<img width="999" alt="Screenshot 2021-01-11 at 17 53 17" src="https://user-images.githubusercontent.com/4699014/104219349-e5c7ab80-5435-11eb-9fb9-788603161588.png">

**Comment by bhaller** [comment]
Oh, I see – it's listed as a parameter to initializeTreeSeq() in the online docs, but the body text doesn't have the description of it.  I'll fix that, thanks.  (Not because it's a recent change; just a change propagation error.  This doc stuff is all done by hand unfortunately.)

**Comment by bhaller** [comment]
OK, fixed.  Apologies for not believing the bug was real!  :->  I saw it listed as a parameter in the online docs and so I thought you had just performed too restricted of a search.  :->

**Comment by hyanwong** [comment]
No problem. Happy to help. 

To catch this sort of thing, I wondered whether there was a way to auto-export a plain-text only version of the pages doc and compare it against a plain text dump of the GUI manual somehow?

**Comment by bhaller** [comment]
> No problem. Happy to help.
> 
> To catch this sort of thing, I wondered whether there was a way to auto-export a plain-text only version of the pages doc and compare it against a plain text dump of the GUI manual somehow?

Yeah, maybe.  As always, the devil is in the details.  The online doc differs from the manual doc intentionally in some respects.  Most notably, references to manual sections are removed; when the manual says something like "As discussed further in section 17.3, ..." I will delete that portion of the sentence, since it doesn't make much sense in the context of the online doc.  So the plain-text comparison would have to be pretty smart not to flag these differences (of which there are quite a large number!) as problems.  There are other differences too; for example, only some of the sections of each manual are vended in the online doc, while other sections are omitted because they're not as "reference manual"-y.  Any diff comparison would need to be smart about that, too.

An overall shift in the way doc is handled would probably be good, and @petrelharp has been pushing for it for a while, but the issues involved are really quite complicated.  At present, the doc lives as two Pages documents (Eidos and SLiM), specific sections get converted into RTF (via copy-paste from Pages into Xcode, plus re-application of paragraph styles since the paste screws them up) and hand-edited (removing section references, primarily), and then those RTF files get converted (by hand, but trivially, with a Save As in TextEdit) into HTML files.  SLiMguiLegacy uses the RTF files for its online doc, SLiMgui (QtSLiM) uses the HTML files for its online doc.  (Neither are presented as is; they get parsed by C++ code that breaks them into separate sections, makes them searchable, etc.)  Maybe in a perfect world it would all be LaTeX or something, and the RTF and HTML could be auto-generated and the section references etc. could automatically be pruned out using custom LaTeX tags, and the whole process could be automated and could live better on GitHub, and a website of online doc could be auto-generated as well for those who would prefer that; but I see no easy path to get there from here, given that 600+ pages of doc already exist in Pages.  Anyway, if one of you would like to open an issue on this problem, I completely agree that it is a problem; I just haven't thought of a good solution yet.
