### ISSUE TITLE
Compression in logging raises zlib error

### ISSUE THREAD

**Issue by vsbuffalo** [MesserLab/SLiM#156]
In SLiM version 3.5 the SLiM file below, which does some very basic logging with compression, raises the following error:

```
$ slim ./simple.slim
[...]
#ERROR (Eidos_WriteToFile): encountered zlib errors while writing to file at path log.tsv.gz.

Error on script line 12, character 12:

  log = sim.createLogFile("log.tsv.gz", compress=T, sep="\t", logInterval=10);
            ^^^^^^^^^^^^^
```

This is on Mac OS X, and @petrelharp has confirmed that this occurs too on Linux.

```
  initialize() {
    initializeMutationRate(1e-8);
    initializeMutationType("m1", 0.5, "f", 0.0);
    initializeGenomicElementType("g1", m1, 1);
    initializeGenomicElement(g1, 0, 99999);
    initializeRecombinationRate(1e-8);
  }
  
  
  1 early() {
    sim.addSubpop("p1", 100);
    log = sim.createLogFile("log.tsv.gz", compress=T, sep="\t", logInterval=10);
    log.addGeneration();
  }
  
  2000 late() {
    sim.simulationFinished();
  }
```

**Comment by bhaller** [comment]
Fixed.  It was due to a bug in the zlib APIs, actually.  They state: "gzwrite returns the number of uncompressed bytes written or 0 in case of error".  If you write zero uncompressed bytes – which happens when createLogFile() is called, if no initial contents are supplied – then everything works fine and 0 is returned since that's the number of uncompressed bytes written – but that is supposed to be the error indicator.  So actually everything was working fine, but Eidos was seeing the 0 return value and thinking it indicated an error on write.  Now Eidos specifically ignores the 0 return value if the number of bytes requested to be written is 0, to work around this bug.  With that in place, things seem to work fine.  I don't know how this got into the release; I certainly tested the compression case!  Maybe I always happened to have an initial contents vector when I had compression turned on, which works around the bug since the data written is then non zero-length.  Who knows.

I also found and fixed a problem with using LogFile inside SLiMgui, which caused the logged data to get written to the wrong path in some cases because the current working directory was incorrect.  Should be good now.  So if you're using SLiMgui, rebuild it too.

This is committed to the GitHub head; use that or wait for the next SLiM release.  I believe it is stable, but some new tskit/treeseq stuff has gone in that could still have issues.

Thanks for the report!
