### ISSUE TITLE
SLiMgui: Haplotype plot in main window changes as mouse cursor moves about window.

### ISSUE THREAD

**Issue by bryce-carson** [MesserLab/SLiM#157]
# Build Information

Fedora 33 build of SLiMgui 3.5 tagged release; unlikely to be related to packaging.

# System Information

64-bit Fedora 33 (Workstation Edition)
5.8GiB RAM (8GB installed, ~2.5 shared with APU)
AMD Ryzen 5 3400g with Radeon Vega Graphics x 8
AMD Raven graphics

Gnome Version 3.38.3
Wayland windowing system

# Issue
The haplotype plot in the main window changes between several different plots as my mouse cursor is moved around my screen. This issue was seen while using _Recipe 9.6.2 - A sweep from standing variation at a predetermined locus_.

The issue is seen using either the X11 or Wayland windowing system, so it is probably a Qt issue. Is this seen on the devel build?

Attached is a screencast of the issue.

[Screencast from 02-12-2021 03:18:27 PM.zip](https://github.com/MesserLab/SLiM/files/5974575/Screencast.from.02-12-2021.03.18.27.PM.zip)

**Comment by bhaller** [comment]
Wacky.  OK, so.  The haplotype display is based on a random sample of genomes from the selected subpops; it isn't based on all genomes because then calculating the haplotypes is too slow.  Each time that the haplotype display redisplays, it gets a different random sample, and so the displayed haplotypes appear to change; the underlying model state hasn't changed, but the random sample of genomes has.

Normally, this is not particularly visible because the chromosome view redisplays only when the model state changes.  It then makes sense to the user that the haplotype display has changed.  You can normally only reveal this behavior by, for example, switching from haplotype display to frequency display and then back to haplotype display; what you see the second time you're on haplotype display will be different from what you saw originally.

You seem to be in a state, however, where the chromosome view is redisplaying just because you're moving the mouse around on the screen.  That does not happen for me on either macOS or Ubuntu 20.04 LTS.  Do you have any idea why that would be happening?

It's not completely trivial to fix the chromosome view, because it doesn't hold on to the haplotype data after it finishes displaying it; that's why it looks different each time it redisplays.  So fixing this bug in that way would require making the chromosome view cache the haplotype data that its display is based upon, and use the cached data whenever the model state has not changed.  Not impossible, but I'm not crazy about it; additional complexity in the design.

My first inclination is to regard this bug as belonging to whatever aspect of your system is making views redisplay just because the cursor is moving around.  That is not normal, in my experience, and seems quite inefficient.  If you have a guess as to why that's happening, that would be helpful.

**Comment by bryce-carson** [comment]
> Wacky. OK, so. The haplotype display is based on a random sample of genomes from the selected subpops; it isn't based on all genomes because then calculating the haplotypes is too slow. Each time that the haplotype display redisplays, it gets a different random sample, and so the displayed haplotypes appear to change; the underlying model state hasn't changed, but the random sample of genomes has.
> 
> Normally, this is not particularly visible because the chromosome view redisplays only when the model state changes. It then makes sense to the user that the haplotype display has changed. You can normally only reveal this behavior by, for example, switching from haplotype display to frequency display and then back to haplotype display; what you see the second time you're on haplotype display will be different from what you saw originally.
> 
> You seem to be in a state, however, where the chromosome view is redisplaying just because you're moving the mouse around on the screen. That does not happen for me on either macOS or Ubuntu 20.04 LTS. Do you have any idea why that would be happening?
> 
> It's not completely trivial to fix the chromosome view, because it doesn't hold on to the haplotype data after it finishes displaying it; that's why it looks different each time it redisplays. So fixing this bug in that way would require making the chromosome view cache the haplotype data that its display is based upon, and use the cached data whenever the model state has not changed. Not impossible, but I'm not crazy about it; additional complexity in the design.

We might make this process clear to the user, by changing the context menu to read "Display Haplotype (random sample)," such as with this change in QtSLiMChromosomeWidget.cpp (line 1402):

```c
QAction *displayHaplotypes = contextMenu.addAction("Display Haplotypes (random sample)");
```
Doing this, and having an errata for Gnome (as below) seems like the simplest solution to this issue.

> My first inclination is to regard this bug as belonging to whatever aspect of your system is making views redisplay just because the cursor is moving around. That is not normal, in my experience, and seems quite inefficient. If you have a guess as to why that's happening, that would be helpful.

It seems to be related to Gnome in some way; the issue isn't present using the LXQt desktop environment. We can regard this as a known issue with Gnome going forward; I don't know how to assess why this is occurring, unfortunately.

**Comment by bryce-carson** [comment]
We can prevent the redrawing of individuals for which haplotypes are displayed by launching SLiMgui with the `-style Fusion` flag on the commandline (`SLiMgui -style Fusion`).

I don't know why the Breeze and Adwaita Qt 5 widget themes, but not the Windows or Fusion themes, cause this to happen. It's a minor issue, but could use improvement. :)

**Comment by bhaller** [comment]
Yeah, seemed like it had to be a bug in the widget kit – or perhaps a feature, if they are intentionally redrawing on mouse-moves in order to show some kind of cursor-driven focus or something.  Thanks for confirming.  I thought of a fix that might work well; rather than saving the full haplotype analysis so that I can redraw identically, what I can do is maybe save the random number seed used to generate it, and use the same seed when I redraw unless the model state has changed.  Might be simpler.  Anyway, this is on my radar, thanks.

**Comment by bhaller** [comment]
Hi @bryce-carson.  I think I just fixed this, but I don't have your setup to test it on.  Please let me know if it isn't fixed.  Thanks!

**Comment by bryce-carson** [comment]
Will do! I'll test on my configuration, and a fresh bare-metal os.

**Comment by bhaller** [comment]
Just your own config will suffice, if it previously exhibited the bug.  Ifit's fixed, it will be fixed everywhere; it's a very simple bug.  :->

**Comment by bryce-carson** [comment]
The bug is no longer observed in SLiMgui built from the master sources. I tested it with each Qt Widget Style present on my system, none were bugged (Adwaita-Dark, Adwaita, Breeze, Windows, Fusion).

Thanks, Ben!

**Comment by bhaller** [comment]
No, thank you!  As always, I'm impressed by your thoroughness.

**Comment by bryce-carson** [comment]
> No, thank you! As always, I'm impressed by your thoroughness.

Thanks! 🐙
