### ISSUE TITLE
remove check on number of input populations?

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#168]
I've run into the following error: on [this line](https://github.com/MesserLab/SLiM/blob/91beaaa5fd728cbf28fd2f54a8d3360dc5af9626/core/slim_sim.cpp#L7939) when SLiM is reading in a trees file for a WF model, it checks that the number of populations-with-SLiM-metadata in the trees file matches the number of subpops, that I'm guessing is created by iterating over the individuals and creating the populations. However: suppose that I (1) run a SLiM simulation with 4 populations; (2) write out the trees file and do something to it, including removing all the individuals except in one population; (3) want to read it into SLiM and simulate a WF model with just one population.  This will (I think? haven't double-checked) raise that error.

I could, in addition to removing individuals, also remove the corresponding entries in the population table. But those populations are still valid - ancestral nodes refer to them - so I guess I'd not remove their entries, just remove their metadata.

But, I don't think we need this check at all? I think it was just a consistency check, but really, the "population table" should contain information about not just the current generation, but also ancestral ones.

And: where I've actually encountered this problem is in recapitation. It's natural to want to add new 'ancestral' populations in recapitation, and it's being difficult to set their metadata appropriately. We can deal with that somehow, but I'm hoping we can do away with this check for the reasons above.

**Comment by petrelharp** [comment]
Well, removing that check and also [this one](https://github.com/MesserLab/SLiM/blob/91beaaa5fd728cbf28fd2f54a8d3360dc5af9626/core/slim_sim.cpp#L7955) produces a segfault, so it's not *quite* so easy...

**Comment by bhaller** [comment]
The first check should be safe to remove; the second one is essential, why do you want to remove it?  SLiM metadata must be of the length expected by SLiM, otherwise it needs to throw an error; removing that check means that it's trying to decode metadata that it doesn't understand, which understandably causes a segfault.

The basic issue here, and the removal of the first check, makes sense to me.  I imagine it's possible to even trigger that error directly for a .trees file written out by SLiM, if an ancestral subpopulation ends up with zero individuals in the final generation, and is thus present in the population table but empty?  Maybe only if one of the ancestral subpopulation has a remembered or retained individual?  Anyway, even if our code is smart enough to avoid that sort of self-triggering, if you're hitting it in other usage cases then it seems reasonable to remove it.

**Comment by petrelharp** [comment]
Heh, whoops. I was not reading carefully enough there. The problem was that when I removed the first check, I errored on the second check... but this is probably due to a legit error in the trees I'm trying to read in. I'll figure it out and report back.

**Comment by petrelharp** [comment]
Edit: the error that happens next if the first error is removed is actually [this one](https://github.com/MesserLab/SLiM/blob/91beaaa5fd728cbf28fd2f54a8d3360dc5af9626/core/slim_sim.cpp#L7966). And, removing it produces a segfault, as I've done here anyhow: https://github.com/petrelharp/SLiM/tree/no_subpop_check

**Comment by bhaller** [comment]
Yeah, WF models are not allowed to have populations with zero individuals.  Don't do that.  :->

**Comment by petrelharp** [comment]
But that's the problem here!

**Comment by bhaller** [comment]
> But that's the problem here!

SLiM doesn't (or shouldn't) care what populations are in the tskit tables.  But the code where you commented out the error and got a segfault is about creating SLiM subpopulation objects to contain extant individuals; and WF models cannot have empty SLiM subpopulation objects.  If you are trying to achieve *that*, then you are trying to violate SLiM's rules regarding what WF models are allowed to do.  If you're just trying to allow the tskit population table to contain a subpop that is now empty, because ancestral individuals lived in it, that should be fine, I think (but should make no difference to SLiM whatsoever); if doing that is hitting that error check, then that is a bug, but the solution to the bug is not to remove the error check.  :->

**Comment by petrelharp** [comment]
I didn't just comment out the error, I asked it to not create the subpop (I think): https://github.com/MesserLab/SLiM/compare/master...petrelharp:no_subpop_check#diff-0ae7a04e87e1ce83b282da28825cc9492ad328d2d4a6d0343fb24f61137de991R7946

**Comment by bhaller** [comment]
> I didn't just comment out the error, I asked it to not create the subpop (I think): [master...petrelharp:no_subpop_checkdiff-0ae7a04e87e1ce83b282da28825cc9492ad328d2d4a6d0343fb24f61137de991R7946](https://github.com/MesserLab/SLiM/compare/master...petrelharp:no_subpop_checkdiff-0ae7a04e87e1ce83b282da28825cc9492ad328d2d4a6d0343fb24f61137de991R7946)

I tried that link but got "There isn’t anything to compare.  We couldn’t figure out how to compare these references, do they point to valid commits?"

**Comment by bhaller** [comment]
Supply me with a .trees file that has a subpop in the population table that is referenced by non-extant individuals in the past, but is empty at the present time, and triggers this issue, and I'll be happy to debug and fix.  I'm not sure whether SLiM would then write out such a file correctly again at the end; there might also be bugs in that area.

**Comment by petrelharp** [comment]
Hmph, sorry about that. Working on it.
