### ISSUE TITLE
pedigree IDs not available even with TreeSeq

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#177]
With SLiM 3.6, this script:
```
initialize() {
	initializeSLiMModelType("nonWF");
	initializeTreeSeq();
	initializeMutationType("m0", 0.5, "e", 1/100);
	initializeGenomicElementType("g1", m0, 1);
	initializeGenomicElement(g1, 0, 9);
	initializeMutationRate(1e-10);
	initializeRecombinationRate(0.0);
}

1 early() {
    sim.addSubpop(0, 1);
    catn(p0.individuals.pedigreeID);
 }  
```
produces the error
```
ERROR (Individual::GetProperty): property pedigreeID is not available because pedigree recording has not been enabled.
```
This is confusing, because the documentation for pedigreeID says that it should be available if TreeSeq is turned on. And, I could have sworn that this got fixed? Apologies if I'm missing something obvious (likely).

**Comment by bhaller** [comment]
Hmm.  The doc and the code are out of sync, for sure.  So something ought to be changed.

Originally, the policy was that pedigreeID and other pedigree-related stuff would only be available if pedigree tracking was explicitly enabled by the user.  The fact that pedigreeIDs get used internally by tree-sequence recording should not, I think, magically make the pedigree tracking feature turn on for the user, for two reasons.  One is just because that's weird and magical and depends upon internal implementation details that should not affect the behavior of the APIs.  The other is because if we ever rearchitected tree-seq to _not_ use pedigreeID internally, we would no longer need to force pedigree tracking to be enabled, and then scripts that relied on the assumption that tree-seq forces pedigree recording on would suddenly break – or tree-seq would have to continue to force pedigree tracking on, for no reason except backward compatibility.  In short, it just feels wrong to me – it raises my hackles.  If you want pedigree tracking, ask for it; if you don't ask for it, you don't have it.  :->

Now, a little while back I tried the experiment of just making pedigree tracking be on all the time, always.  My hope was that we could get rid of the whole issue.  Unfortunately, that turned out to have somewhat serious performance effects for some models, and I had to back that change out.  My guess is that when I backed the change out, my edits in the manual were incorrect, leading to the inconsistency you have now discovered.  Or I could just be misremembering all this history and everything; totally possible.  :->  I could dig around in the history to try to confirm that hunch, but in the end, it is what it is.

My current opinion is that the code is correct and the doc is wrong: pedigree tracking features should only be available to be user when they have explicitly requested them, they should not be implicitly activated when tree-seq is activated (even though they really are activated, under the hood), for the reasons given above.  However, I recall that you disagreed with that choice.  If you think there's a good case to be made for implicitly turning pedigree tracking on when tree-seq turns on, I'll listen.  :->

**Comment by petrelharp** [comment]
Oh, right! Sorry, i keep forgetting. And no - the "serious performance effects" is a great reason (unfortunately).  (However, I'm surprised that it has performance effects, as it's "just" information that's "already there...")

**Comment by bhaller** [comment]
In really core code, just a single "if" that checks a flag somewhere can have a significant performance impact.  The flag is located in a block of memory that isn't in-cache, so everything stalls while the CPU waits for the memory bus to come back with the flag value.  And now you're thrown away a whole cache line, so you'll pay another memory fetch price when you get back to doing actual work and you need to re-fetch that cache line.  It can be surprisingly painful.  You want core code to just keep its head down, focus on the task at hand, and consult no external state whatsoever.  :->
