### ISSUE TITLE
provide method to compute proportion of interaction area within spatial bounds

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#182]
It's common in spatial models to have mortality be an increasing function of the number of neighbors within distance R, say. However, this gives a bonus to the individuals living on the edge of the range, which doesn't make sense, because - if we imagine this is due to competition for resources - they're getting the benefit of grazing outside of the rectangle where everyone is allowed to live. It would make a lot more sense if we adjusted for the actual amount of habitat that's within distance R of them. If the function `i1.proportionInteracting(p1, pos, R)` returns the proportion of the circle of radius R centered at pos that lies within the spatial bounds of population `p1`, then this would work something like so:
```
initializeInteractionType("i1", "xy", reciprocal=T, maxDistance = R);
i1.setInteractionFunction("f", 1.0/(PI*R^2));
//  ...
density = i1.totalOfNeighborStrengths(p1.individuals); // density within distance R of each individual
habitat = i1.proportionInteracting(p1, p1.individuals.spatialPosition, R);
p1.individuals.fitnessScaling = 1 / (1 + exp(-density/(habitat * K)));
```
Effectively, what's going on here is we've under-estimated local density by a factor of `habitat`, so we correct for that.

The calculation is not terribly straightforward, but I've worked it out [here](https://petrelharp.github.io/circle_rectangle_intersection/circle_rectangle_intersection.html).

Since it's a fairly annoying calculation, and edge effects can be a major source of bugs (eg you can have extremely long-lived individuals on the margins on accident), I think it's worth making this a method of Interactions.

If the interaction function was not flat, this actually becomes easier- for instance for the Normal it can be computed from the normal CDF. But I thought I'd raise the question first before working *that* out.

**Comment by bhaller** [comment]
Yes, this certainly seems worth adding, thanks!  Ideally it would be supported for all of the standard interaction functions.  Could you work out the correct equations for all of them?  If one proves to be intractable, then I suppose it could return an error to try to get the interaction area with that interaction function; but it would be much better if they all worked.

It occurs to me that the next step would be to be able to get the interaction area that intersects with a given spatial map; that would allow the same sort of thing to be done with Martin's spammr stuff.  :-O

**Comment by petrelharp** [comment]
>  Could you work out the correct equations for all of them?

Not sure - I'd have to try. There's just one parameter, up to scaling, so we could at least create a lookup table numerically. (Hell, that might be the fast thing to do for all the cases anyhow...)

**Comment by petrelharp** [comment]
> It occurs to me that the next step would be to be able to get the interaction area that intersects with a given spatial map;

Yes! But that would have to be done numerically.

**Comment by petrelharp** [comment]
I'm recording here a vectorized method for a "normal" interaction, in Eidos:
```
function (float) area(o$ pop, f$ sigma, f$ maxDistance) {
   x = pop.individuals.x;
   y = pop.individuals.y;
   ab = pop.spatialBounds;
   left = (x < ab[0] + maxDistance);
   right = (x > ab[1] - maxDistance);
   bottom = (y < ab[2] + maxDistance);
   top = (y > ab[3] - maxDistance);
   A = rep(1.0, length(x));
   if (any(left))
     A[left] = A[left] - pnorm(x[left], ab[0], sigma);
   if (any(right))
     A[right] = A[right] + pnorm(x[right], ab[1], sigma) - 1;
   if (any(bottom))
     A[bottom] = A[bottom] - pnorm(x[bottom], ab[2], sigma);
   if (any(top))
     A[top] = A[top] + pnorm(x[top], ab[3], sigma) - 1;
   if (any(left & bottom))
     A[left & bottom] = A[left & bottom]
        + pnorm(x[left & bottom], ab[0], sigma) * pnorm(x[left & bottom], ab[2], sigma);
   if (any(left & top))
     A[left & top] = A[left & top]
        + pnorm(x[left & top], ab[0], sigma) * (1 - pnorm(x[left & top], ab[3], sigma));
   if (any(right & bottom))
     A[right & bottom] = A[right & bottom]
        + (1 - pnorm(x[right & bottom], ab[1], sigma)) * pnorm(x[right & bottom], ab[2], sigma);
   if (any(right & top))
     A[right & top] = A[right & top]
        + (1 - pnorm(x[right & top], ab[1], sigma)) * (1 - pnorm(x[right & top], ab[3], sigma));
   return(A);
}
```

**Comment by bhaller** [comment]
So I guess the question is, as you said, whether these would be best implemented as lookup tables anyway.  What would that look lie, do you think?  What would the lookup table be looking up, exactly?  A 2D table looking up x and y distance to the edge of the world?  Also: I apologize in advance for asking this, but what about the 3D case?

**Comment by bhaller** [comment]
For the 3D case in particular, an x-y-z distance lookup table with sufficient resolution to provide precise numbers (good to, say, four decimal places?) would be quite large, wouldn't it?  So maybe the 3D cases would need to be done numerically, since a lookup table would be too large.  Even the 2D lookup tables might be a bit large.

**Comment by petrelharp** [comment]
(note: the above code was wrong and too complicated; fixed now)

You're right, it'd have to be a d-dimensional lookup table in d dimensions. We'd need this even for the 'circle' case in 3D because I don't want to figure out all that 3D geometry. =) But I think we could get away with a pretty small lookup table because (a) we can interpolate, and (b) we don't need to be terribly precise (two decimal places?). So maybe like a 21x21x21 = 9261 lookup table in 3d. The lookup tablbe could be created numerically  from the interaction itself (so, not relying on any analytics) at runtime the first time this method is called, and then cached.

**Comment by bhaller** [comment]
Hmm, ok.  I've already got 1D/2D/3D interpolation code, for the spatial maps; I could probably share that code.  How does the lookup table get created numerically from the interaction itself?  Yes, I suppose maybe two decimal places would suffice.  9261 doubles is quite small, we can go larger than that.

**Comment by petrelharp** [comment]
>  How does the lookup table get created numerically from the interaction itself?

I think the goal is to compute the integral of the interaction function over the "available habitat", namely, the intersection of the maxDistance circle with the habitat, whatever the interaction function is. So, we'd do that by (a) making a grid of points centered at zero and evaluating the interaction function at each point and zero'ed past maxDistance, and (b) across a (possibly coarser) grid of "boundary distances" compute the sum of the values that lie closer than the appropriate boundary multiplied by the grid area to approximate the integral.

Hm: a point has *four* distances to the sides of the rectangle in 2d (and a circle might stick out all four sides), so at first glance we'd need a 4d grid. But we can do it with two 1d grids and one 2d grid by inclusion-exclusion. (or, four 2d grids and four 1d grids if the interaction is not symmetric)

**Comment by bhaller** [comment]
Interesting.  Complicated.  This is all worth the effort, in your estimation, I take it?

**Comment by petrelharp** [comment]
I think so, but maybe let me use it a bit more and see how I feel in a month or so.

**Comment by bhaller** [comment]
Hi @petrelharp.  You said above "let me use it a bit more and see how I feel in a month or so".  What are your thoughts now?  I'm contemplating this.  Something like this, on InteractionType:

- (float)clippedIntegral(io<Subpopulation>$ subpop, No<Individual> individuals)

It would use the spatial bounds of the given subpop to clip the interaction function at the edges, evaluated at the positions of the given individuals.  This is slightly different than you proposed above; I have it take a vector of individuals, not a vector of spatial positions, partly for efficiency and partly so the user doesn't need to worry about translating between the dimensionality of the model and the spatiality of the interaction type if they are different (i.e., an "xz" interaction in an "xyz" model).  And I don't have it take the radius R as a parameter, since it seems to me that should be taken from the definition of the InteractionType, not be user-supplied.  To keep life simple, I'm inclined to say that this method raises an error if the max distance of the interaction is more than half of the width or height of the spatial bounds, thus eliminating all the messiness you contemplated above; it's a bad idea to use interactions that cover that much of the spatial area anyway, in general, probably.  If you pass NULL, the method returns the maximum integral, when the interaction function is completely unclipped by any spatial bounds.

Does this seem like a reasonable design?  What do you think of `clippedIntegral()` as a name?  And the big question: having pondered it for a while, do you still think this is sufficiently useful to justify its existence?

**Comment by petrelharp** [comment]
> the focal individual itself doesn't get counted as part of the local density, and that makes the density-dependence penalty be just a smidge too low. I would like to fix this

Oh, curses, right. Yes, this would be a good thing to fix - we've found this to be important.

I think that `interactionDensity()` is a *great* idea, because it'll be easier for people to find and to understand! It's really not at all obvious that `totalOfNeighborStrengths()` will give a density estimate (in units of *individuals* per unit area).

**Comment by bhaller** [comment]
OK, great.  And would `interactionDensity()` *always* add 1, or would that need to be subject to a flag?  Are there uses/cases where adding 1 would not be correct?

**Comment by petrelharp** [comment]
It should add whatever the value of the interaction kernel is at distance 0. (i.e., "here's another individual at distance zero"). I don't think that needs a flag.

**Comment by bhaller** [comment]
(yeah, that's what I really meant by "1" :->)

**Comment by bhaller** [comment]
OK, I have taken out `[density=F]` from `totalOfNeighborStrengths()` and added a new `interactionDensity()` method on `InteractionType`.  This stuff is all tested and seems happy; the only thing left is to modify recipes.  My plan is to modify only recipe 16.11, showing the old way of doing "carrying capacity density" calculations first (to explain the necessary concepts), and then showing the spiffy new way using `interactionDensity()`, but maybe I'll change my mind about that, I haven't thought about it hard yet.

Here is the current documentation for the additions; it would be good to get a thumbs-up that this all sounds correct, @petrelharp:

`– (float)clippedIntegral(object<Individual> individuals)`
Returns a vector containing the integral of the interaction function as experienced by each of the individuals in individuals.  For each given individual, the interaction function is clipped to the edges of the spatial bounds of the subpopulation that individual inhabits; the individual’s spatial position must be within bounds or an error is raised.  A periodic boundary will, correctly, not clip the interaction function.  The interaction function is also clipped to the interaction’s maximum distance; that distance must be less than half of the extent of the spatial bounds in each dimension (so that, for a given dimension, the interaction function is clipped by the spatial bounds on only one side), otherwise an error is raised.
The computed value of the integral is not exact; it is calculated by an approximate numerical method designed to be fast, but the error should be fairly small (typically less than 1% from the true value).  A large amount of computation will occur the first time this method is called (perhaps taking more than a second, depending upon hardware), but subsequent calls should be very fast.  This method does not depend upon the evaluation of the interaction at all; evaluate() does not need to be called beforehand.  Similarly, interaction() callbacks are not invoked by this method; the calculated integrals are only for the interaction function itself, and so will not be accurate if interaction() callbacks modify the relationship between distance and interaction strength.  For these reasons, the overhead of the first call will not reoccur when individuals move or when the interaction is re-evaluated; for typical models, the initial overhead will be incurred only once.  The initial overhead will reoccur, however, if the interaction function itself, or the maximum interaction distance, are changed; frequent change of those parameters may render the performance of this method unacceptable.
The integral values returned by clippedIntegral() can be useful for computing interaction metrics that are scaled by the amount of “interaction field” (to coin a term) that is present for a given individual, producing metrics of interaction density.  Notably, the interactionDensity() method automatically incorporates the mechanics of clippedIntegral() into the calculations it performs; see that method’s documentation for further discussion of this concept.  This approach can also be useful with the interactingNeighborCount() method, provided that the interaction function is of type "f" (since the neighbor count does not depend upon interaction strength).

`– (float)interactionDensity(object<Individual> individuals)`
Returns a vector of the total interaction density present at the location of each individual in individuals, which does not need to be a singleton; indeed, it can be a vector of all of the individuals in a given subpopulation.  However, all of the individuals in individuals must be in the same subpopulation.
Interaction density is defined as the total interaction strength present at a given point, divided by the integral of the interaction function around that point after clipping by the spatial bounds of the focal subpopulation (what one might think of as the amount of “interaction field” around the point).  In a sense, it is a measure of the amount of interaction happening per unit of interaction field in the space surrounding the point.
To calculate the clipped integral of the interaction function, this method uses the same numerical estimator used by the clippedIntegral() method of InteractionType, and all of the caveats described for that method apply here also; notably, all individuals must be within spatial bounds, the maximum interaction distance must be less than half the spatial extent of the subpopulation, and interaction() callbacks are not used (and so, for this method, are not allowed to be active).  See the documentation for that method for further discussion of the details of these calculations.
To calculate the total interaction strength around the position of a given individual, this method uses the same machinery as the totalOfNeighborStrengths() method of InteractionType, except that – in contrast to other InteractionType methods – the interaction strength exerted by the focal individual itself is included in the total.  This is the reason why this method is described as the interaction density present at the locations of individuals, rather than the interaction density felt by the individuals themselves; the interaction density at the location of an individual includes the interaction strength exerted by that individual, even though the interaction strength of an individual with itself is zero by definition.
To see the point of this method, consider an individual located near the edge of the spatial bounds of its subpopulation.  Some portion of the interaction function that surrounds that individual falls outside the spatial bounds of its subpopulation, and will therefore never contain an interacting individual.  If, for example, interaction strengths are used as a measure of competition, this individual will therefore have an advantage, because it will never feel any competition from the portion of its range that falls outside spatial bounds.  However, that portion of its range is presumably also not available to the individual itself, for foraging or hunting, in which case this advantage is not biologically realistic, but is instead just an undesirable “edge effect”.  Dividing by the integral of the interaction function, clipped to the spatial bounds, provides a way to compensate for this edge effect.  A nice side effect of using interaction densities instead of total interaction strengths is that the maximum interaction strength passed to setInteractionFunction() no longer matters; it cancels out when the total interaction strength is divided by the focal individual’s clipped integral.  If interaction densities are not used, making these types of calculations come out correctly is much more tricky.

I expect to commit this later today, or perhaps tomorrow.

**Comment by petrelharp** [comment]
I've got some suggestions, including renaming the method.

```
– (float)populationDensity(object<Individual> individuals)
Returns a vector of the local population density present at the location of each individual in individuals, which does not need to be a singleton; indeed, it can be a vector of all of the individuals in a given subpopulation. However, all of the individuals in individuals must be in the same subpopulation.
Population density is estimated using interactions: what is returned is computed as the total interaction strength present at a given point, divided by the integral of the interaction function around that point after clipping by the spatial bounds of the focal subpopulation (what one might think of as the amount of “interaction field” around the point). This provides an estimate of local population density, in units of individuals per unit area, as a weighted average over the area covered by the interaction function.
This can also be thought of as a measure of the amount of interaction happening per unit of interaction field in the space surrounding the point.
```

After reading your description in terms of total of interaction strengths, I'm also very tempted to put back in the `includeSelf=T` argument, since if you start thinking about e.g. grazing pressure, if you do "includeSelf=F" then you get the total amount of grass that *other* individuals have eaten.

**Comment by bhaller** [comment]
> I've got some suggestions, including renaming the method.
> 
> ```
> – (float)populationDensity(object<Individual> individuals)
> ...

Hmm.  It's only population density if the interaction uses a type "f" kernel, right?  Because then each individual within the interaction field is equally weighted, so it happens to be a measure of local population density.  But for other types of interaction functions, it would not be population density – at least not in any conventional sense – right?  So I think I like talking about "interaction density" rather than "population density"...?  Perhaps we ought to zoom about this.

> After reading your description in terms of total of interaction strengths, I'm also very tempted to put back in the `includeSelf=T` argument, since if you start thinking about e.g. grazing pressure, if you do "includeSelf=F" then you get the total amount of grass that _other_ individuals have eaten.

Yes, having an includeSelf parameter seems potentially useful, although I'm not sure exactly how, in practice – i.e., what would a model actually *do* with the metric "total amount of grass that _other_ individuals have eaten"?  But it's trivial to add, might as well provide the flexibility.

**Comment by petrelharp** [comment]
> Hmm. It's only population density if the interaction uses a type "f" kernel, right? Because then each individual within the interaction field is equally weighted, so it happens to be a measure of local population density. But for other types of interaction functions, it would not be population density – at least not in any conventional sense – right?

Nope - it's a population density no matter what the kernel!!  The math holds up, but here is some numerical verification: I'm laying down a bunch of points at three different densities (rho), computing the local density estimate using a Normal kernel with three different bandwidths (sigma), and histogramming the resulting density estimates around a bunch of points not near the edges. They all cluster around the true density values, regardless of the bandwidth.
```
sigmavals <- c(0.5, 1, 2)
rhovals <- c(2, 10, 20)
layout(seq_along(sigmavals))
for (sigma in sigmavals) {
    for (rho in rhovals) {
        W <- 10
        N <- W * W * rho

        xy <- cbind(
                    x=runif(N, -W/2, W/2),
                    y=runif(N, -W/2, W/2)
        )
        center <- pmax(abs(xy[,1]), abs(xy[,2])) < W/5

        D <- sqrt(
                  outer(xy[center,1], xy[,1], "-")^2 
                  + outer(xy[center,2], xy[,2], "-")^2 
            )

        f <- function (d, sigma) {
            return( exp(-d^2 / (2  * sigma^2)) / (2 * pi * sigma^2) )
        }

        I <- f(D, sigma=sigma)
         
        hist(rowSums(I), xlim=c(0, max(rhovals)*1.5), add=(rho != rhovals[1]), col=match(rho, rhovals),
             freq=FALSE, main=sprintf("sigma=%f", sigma))
        abline(v=rho, col=match(rho, rhovals), lwd=2, lty=2)
    }
    legend("topright", fill=1:3, legend=sprintf("density = %d", rhovals))
}
```
which produces
![Screenshot from 2021-11-03 13-21-11](https://user-images.githubusercontent.com/1046249/140186746-7f7c330b-55c1-4977-8296-3773b05feb38.png)

**Comment by petrelharp** [comment]
> Yes, having an includeSelf parameter seems potentially useful, although I'm not sure exactly how, in practice – i.e., what would a model actually do with the metric "total amount of grass that other individuals have eaten"? But it's trivial to add, might as well provide the flexibility.

Actually - let me take this back. It is the totalOfInteractionStrengths which is *actually* the amount of grass eaten; normalizing is useful for getting population densities, not for computing grazing pressure. So - never mind about adding the parameter.

**Comment by bhaller** [comment]
> > Hmm. It's only population density if the interaction uses a type "f" kernel, right? Because then each individual within the interaction field is equally weighted, so it happens to be a measure of local population density. But for other types of interaction functions, it would not be population density – at least not in any conventional sense – right?
> 
> Nope - it's a population density no matter what the kernel!! The math holds up, but here is some numerical verification: I'm laying down a bunch of points at three different densities (rho), computing the local density estimate using a Normal kernel with three different bandwidths (sigma), and histogramming the resulting density estimates around a bunch of points not near the edges. They all cluster around the true density values, regardless of the bandwidth.

I can see it being an approximation of population density, on average.  But in general it is not population density, right?  It seems trivial to construct examples where it completely fails to measure population density.  For example: the interaction function within the maximum radius is 1 on the left-hand side, 0.001 on the right-hand side.  The left-hand side happens to be empty; the right-hand side happens to contain a bunch of individuals.  This will not produce anything like a good estimate of the population density inside the maximum radius.

**Comment by bhaller** [comment]
Had a zoom; agreed on `localPopulationDensity()`; clarified that it is providing *weighted* population density, which was my misunderstanding; should say in doc that this is doing "kernel density estimation", treating the subpopulation boundaries correctly.

**Comment by bhaller** [comment]
OK, here's a new writeup for `localPopulationDensity()`.  I think it's probably good now, so I won't wait for comments (but they are welcome of course).  Thanks for the feedback @petrelharp, helpful as always.  I just need to modify the recipe writeup now.

`– (float)localPopulationDensity(object<Individual> individuals)`
Returns a vector of the local population density present at the location of each individual in individuals, which does not need to be a singleton; indeed, it can be a vector of all of the individuals in a given subpopulation.  However, all of the individuals in individuals must be in the same subpopulation.
Population density is estimated using interaction strengths, effectively doing a kernel density estimate using the interaction function as the kernel.  What is returned is computed as the total interaction strength present at a given point, divided by the integral of the interaction function around that point after clipping by the spatial bounds of the focal subpopulation (what one might think of as the amount of “interaction field” around the point).  This provides an estimate of local population density, in units of individuals per unit area, as a weighted average over the area covered by the interaction function, where the weight of each individual in the average is the value of the interaction function at that individual’s position.  This can also be thought of as a measure of the amount of interaction happening per unit of interaction field in the space surrounding the point.
To calculate the clipped integral of the interaction function, this method uses the same numerical estimator used by the clippedIntegral() method of InteractionType, and all of the caveats described for that method apply here also; notably, all individuals must be within spatial bounds, the maximum interaction distance must be less than half the spatial extent of the subpopulation, and interaction() callbacks are not used (and so, for this method, are not allowed to be active).  See the documentation for clippedIntegral() for further discussion of the details of these calculations.
To calculate the total interaction strength around the position of a given individual, this method uses the same machinery as the totalOfNeighborStrengths() method of InteractionType, except that – in contrast to other InteractionType methods – the interaction strength exerted by the focal individual itself is included in the total.  This is because population density at the location of an individual includes the individual itself.  If this is not desirable, the totalOfNeighborStrengths() method should probably be used.
To see the point of this method, consider an individual located near the edge of the spatial bounds of its subpopulation.  Some portion of the interaction function that surrounds that individual falls outside the spatial bounds of its subpopulation, and will therefore never contain an interacting individual.  If, for example, interaction strengths are used as a measure of competition, this individual will therefore have an advantage, because it will never feel any competition from the portion of its range that falls outside spatial bounds.  However, that portion of its range is presumably also not available to the individual itself, for foraging or hunting, in which case this advantage is not biologically realistic, but is instead just an undesirable “edge effect”.  Dividing by the integral of the interaction function, clipped to the spatial bounds, provides a way to compensate for this edge effect.  A nice side effect of using local population densities instead of total interaction strengths is that the maximum interaction strength passed to setInteractionFunction() no longer matters; it cancels out when the total interaction strength is divided by the focal individual’s clipped integral.  However, the shape of the interaction function does still matter; it determines the relative weights used for individuals at different distances from the position of the focal individual.

**Comment by bhaller** [comment]
Here is a PDF of the new section 16.10 (text changes but no code changes) and section 16.11 (text changes and code changes, to use `localPopulationDensity()`).  Comments welcome.

[SLiM_Manual_density.pdf](https://github.com/MesserLab/SLiM/files/7471902/SLiM_Manual_density.pdf)
