### ISSUE TITLE
string values not allowed when loading json dictionary

### ISSUE THREAD

**Issue by grahamgower** [MesserLab/SLiM#184]
This should be supported, right?
```
$ cat /tmp/a.txt
Dictionary('{"a": "b"}');
$ eidos /tmp/a.txt
ERROR (EidosDictionaryUnretained::AddJSONFrom): unsupported value type "string" in AddJSONFrom().

Error on script line 1, character 0:

Dictionary('{"a": "b"}');
^^^^^^^^^^
```

**Comment by bhaller** [comment]
Yes, it should.  Just fixed it.  Slipped through the cracks of my unit tests, which is not *quite* as dumb as it sounds.  The problem is that Eidos will JSON-serialize that Dictionary as '{"a": ["b"]}', not '{"a": "b"}'; since everything in Eidos is a vector, all values get serialized as arrays, not singletons.  (That is potentially fixable if it's a problem, but it was the easy way to do things, since the values are thought of by Eidos as vectors under the hood.)  So the unit tests were exercising that case properly, but the case of supplying singleton, non-array values was not tested as thoroughly.  Anyway, fixed, now on GitHub.  Thanks!
