### ISSUE TITLE
eidos: can't use negative numbers for function parameter default value

### ISSUE THREAD

**Issue by grahamgower** [MesserLab/SLiM#186]
```
$ cat /tmp/a.txt
function (void)foo([integer$ bar = -1]) { catn("hi"); }

$ eidos /tmp/a.txt
ERROR (EidosScript::Parse_Constant): unexpected token '-'.

Error on script line 1, character 35:

function (void)foo([integer$ bar = -1]) { catn("hi"); }
                                   ^
```

**Comment by bhaller** [comment]
hmm, surprising, ok, thanks

**Comment by bhaller** [comment]
OK, so, this is expected and conformant with the Eidos grammar (but obviously undesirable).  The reason is that a numeric constant in Eidos is always a positive number; when you write "x = -5" the "-5" is actually an expression involving unary minus with a numeric constant of 5.  Possibly not ideal, but also not unusual in language grammars, I think?  Ordinarily this has no user-visible consequence; anywhere that you can use a numeric constant, you can also use a unary minus to make it negative – EXCEPT default values in function declarations, because they do not allow the default value to be an expression, even a constant expression like "2*5"; it must be a simple constant.  Unary minus is therefore out of the picture.

The hard fix would be to allow constant expressions of any kind for default values (or perhaps even non-constant expressions, evaluated at the time the declaration is processed).  I think that's a can of worms I don't want to open.  The easy fix is to modify the grammar of function declarations to explicitly allow a single unary minus to precede a numeric constant.  I think that is what I will do.  Stay tuned.

**Comment by grahamgower** [comment]
Thanks Ben. I don't have a strong use for this, but was just surprised that it didn't work. Feel free to close without fixing if it looks like too much work. I wanted to use the default value to detect whether the parameter was passed to the function, and if not, set a value based on another parameter. My first thought was to use -1, because negative numbers are invalid for that parameter. However the following works just fine:
```
function (void)foo(integer$ a, [Ni$ b = NULL]) {
    if (isNULL(b)) {
        b = a;
    }
    ...
}

**Comment by bhaller** [comment]
No worries, it's a good bug and should be fixed.  Now that I know it exists, I wouldn't be able to sleep at night if I closed it without fixing it.  :->  Thanks!

**Comment by bhaller** [comment]
Fixed.  In your specific situation, using NULL is probably the better API design anyway, but now it works.  :->  Thanks!
