### ISSUE TITLE
eidos: source() and folders don't mix

### ISSUE THREAD

**Issue by grahamgower** [MesserLab/SLiM#190]
It would be nice to be able to use `source("foo")` a bit like `#include <foo>`. Currently this doesn't seem to be possible. E.g.

```
$ pwd
/tmp/a
$ ls -R
.:
a.txt  b/

./b:
b.txt  c.txt

$ cat a.txt
print("a.txt: " + getwd());
source("b/b.txt");

$ cat b/b.txt
print("b.txt: " + getwd());
source("c.txt");

$ cat b/c.txt
print("hi from c.txt")
```

```
$ eidos a.txt
"a.txt: /tmp/a"
"b.txt: /tmp/a"
#WARNING (Eidos_ExecuteFunction_readFile): function readFile() could not read file at path c.txt.
```

Because `source("foo")` looks for "foo" relative to the working directory, rather than the directory containing the currently executing script, this can't work. I didn't see any obvious way to detect the full path to a currently executing file, so I don't think it's possible to write a source()-like replacement function that does this.

**Comment by grahamgower** [comment]
PS: I don't really want to do stupidly complex things here. My goal is the following folder structure:
```
./demes.eidos      eidos functions for demes
./demes.slim        slim functions for demes, that calls `source("demes.eidos")`
./tests/some_tests.slim     a test written in slim/eidos
./tests/tests.sh      some driver script to run all the tests
```

**Comment by bhaller** [comment]
@petrelharp thoughts?  I recall you pushed some of this source/directory stuff in a direction that made sense to you, in the past.  How do you handle the issue that @grahamgower is raising here, and what do you think should be done about the issue he raises?  I feel like I'm too far from the applied cases that you guys work with to judge the right course of action here.

**Comment by bhaller** [comment]
Interesting.  Well, I think it would be easy to add a `[logical$ chdir = F]` parameter to `source()` that provides exactly the same functionality, I think (at least on the assumption that the supplied path is non-pathological and thus the correct directory can be obtained by just splitting the path at the last `/` character).  @grahamgower would that solve the problem for you?

**Comment by grahamgower** [comment]
Ah, that is interesting. Yes, that would work perfectly!

**Comment by bhaller** [comment]
OK, fixed.

The only quirk you might notice is that if you're using `source()` inside an interactive Eidos console with `chdir=T`, and an error gets raised during the execution of the sourced file, the working directory will not get restored; it will be changed to the directory of the sourced file.  This is because the error raise blows through the code that would restore the old working directory.  More deeply, it is because `source()` is actually implemented in Eidos, not in C++, and Eidos presently has no try/catch type of mechanism to catch and handle exceptions, so the Eidos code that would restore the working directory never gets executed in this case.  This could be fixed, but would require me to change the implementation of `source()` from Eidos to C++ (so that I have proper exception handling), which I'd prefer not to do unless this quirk actually bothers somebody.  So, if it bothers you, please open a new issue.  Note that this is a non-issue when you're not executing in an interactive Eidos console, because then the error terminates the process anyway.

Thanks for the interesting bug!

**Comment by grahamgower** [comment]
Awesome, thanks Ben!
