### ISSUE TITLE
negative binomial distribution

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#215]
The negative binomial distribution (`rnbinom` in R) is pretty commonly used in ecological modeling, as it lets you draw a random integer while controling both the mean *and* variance - eg if you want to add overdispersion to your Poisson. It's possible to do that now through mixtures (eg a Poisson with a random mean), but it's a natural thing that people are going to want to do (eg, me right now; no hurry though).

So: proposal is to add `rnbinom` and `dnbinom`, following R.

**Comment by bhaller** [comment]
OK.  In general, I have added the `d` functions for distributions only when they are actually needed; Eidos has a lot more `r` distribution functions than `d` distribution functions, since usually people just want to draw from a distribution.  Do you think the `dnbinom` function is actually called for here, or shall I wait for someone to need it before I add it?

**Comment by bhaller** [comment]
Do you care about the "alternative parametrization via mean" as provided by R?  Or is providing the standard parameterization with p and n sufficient?

**Comment by bhaller** [comment]
Well, I didn't do that for now.  Seems to work; let me know if there's any problem.  Same parameterization as R, which is not the same as Wikipedia.
