### ISSUE TITLE
Eidos events don't execute

### ISSUE THREAD

**Issue by YuetongXU** [MesserLab/SLiM#239]
[SLiM_fixed_neutral.eidos.txt](https://github.com/MesserLab/SLiM/files/7532248/SLiM_fixed_neutral.eidos.txt)
 
Hello, when I run the above script, the standard output is

        start
        loaddata
        t10000

But there is no ‘t1000’, which means that "1000 {cat('t1000\n');}" is not executed. What is the reason? Thank you！

**Comment by YuetongXU** [comment]
[1772950904144.fixed.txt](https://github.com/MesserLab/SLiM/files/7532257/1772950904144.fixed.txt)

The above file is the input ‘outputfull’ file, which simulates the fixed result of a beneficial mutation in the center of the 225kb chromosome fragment. 

I hope that the eidos script in the question can read the fixed 'outputfull' file, and on this basis simulate the influence of neutral mutations after different generations (such as t100, t500, t1000, t5000, t10000) on the population genetic map.

I don’t know if it is possible to merge two eidos (simulation fixation + simulation the influence of neutral mutation after fixation on the selection sweep area) into one eidos. If so, please let me know, thank you!

**Comment by bhaller** [comment]
> But there is no ‘t1000’, which means that "1000 {cat('t1000\n');}" is not executed. What is the reason? Thank you！

The output file appears to have been saved at generation 3222; the first line of it is:

`#OUT: 3222`

which provides the generation number as documented in section 26.1.1 of the manual:

> The header line begins with `#OUT:` and then gives the generation in which the output was produced, followed by an `A` (for “all”).

When `readFromPopulationFile()` is called, that generation number is restored, as documented in section 24.13.12:

> As of SLiM 2.1, this method changes the generation counter to the generation read from the file.  If you do not want the generation counter to be changed, you can change it back after reading, by setting `sim.generation` to whatever value you wish.

If you execute the model in SLiMgui (always recommended for model development and debugging – that's what SLiMgui is there for!), you can see that as soon as generation 1 finishes, the generation counter is then set to 3223 (not 3222, because it gets incremented at the end of the generation).  As the quote above notes, you can set sim.generation to whatever you want if you wish to override the generation set by `readFromPopulationFile()`.

> I don’t know if it is possible to merge two eidos (simulation fixation + simulation the influence of neutral mutation after fixation on the selection sweep area) into one eidos. If so, please let me know, thank you!

Sure.  Section 9.2 shows how to simulate conditional upon fixation of a mutation.  If you want to then do further simulation after fixation has occurred, just continue simulating instead of calling `sim.simulationFinished()`, switching your script into whatever new simulation modality you wish.  Eidos is a fairly general-purpose programming language, so you can do whatever you wish.

It seems like you are just getting started using SLiM, so if you have not done so already, I recommend that you do the SLiM workshop, available for free online at [http://benhaller.com/workshops/workshops.html](http://benhaller.com/workshops/workshops.html).

Closing this issue now, since there is no bug here, but if you comment further, I will see it.  Happy modeling!
