### ISSUE TITLE
Ability to run command-line slim using stdin as input

### ISSUE THREAD

**Issue by hyanwong** [MesserLab/SLiM#24]
Using the command-line utility, it would be useful to be able to pipe commands into slim, rather than have to rely on a file in the filesystem. E.g. I'd hope to be able to do

```
cat test.txt | slim
```

as well as 

```
slim test.txt
```

This would allow me to e.g. generate an eidos script in python, and pipe it into slim, without having to use a temporary file as an intermediate step. You can do this with python scripts: the python man page says 

> ... when called with a file name argument or with a file as standard input, it reads and executes  a  script from that file; .....  In non-interactive mode, the entire input is parsed  before  it is executed.

**Comment by bhaller** [comment]
OK, so.  This is trivial to implement.  I don't work on the command line that much (I'm more of a Mac person than a Unix person), so I have a question for you, though.  Some Unix tools read from stdin if they simply aren’t given a file to work with instead; others require that a filename of “-“ be supplied to indicate that they ought to use stdin.  Is there any particular rhyme or reason to this, or is it a matter of the personal preference of the writer of the tool?  I lean toward requiring “-“ to use stdin, and having a missing filename be an error (as it is now), for clarity, since I figure reading from stdin will be a rare power-user feature whereas forgetting to supply a filename on the command line would be a common novice error, and you don’t want the common novice error to result in what appears to be a working run or a hang (i.e. slim just sitting and waiting for input, which is hard to distinguish from slim being busy simulating).  Do you concur, or is there something else at stake here that I’m missing?

**Comment by bhaller** [comment]
I've just committed a fix for this.  If you want to use the github head version of SLiM, you can try it out now; otherwise, it'll be out in the next release of SLiM, whenever that happens.  Thanks for the suggestion.  :->

**Comment by hyanwong** [comment]
I agree about using - for clarity. Thanks!

**Comment by bhaller** [comment]
> I agree about using - for clarity. Thanks!

Peter convinced me otherwise, actually, which is why I deleted the question above.  So, no "-" required (or allowed), as it turns out.  :->
