### ISSUE TITLE
readFromPopulationFile() without initializeTreeSeq() still keeps track of trees

### ISSUE THREAD

**Issue by nobrien97** [MesserLab/SLiM#246]
Hi,

A couple of weeks ago I asked a [question on slim-discuss](https://groups.google.com/g/slim-discuss/c/Y4fKfhrk6w0) regarding using a coalescent approach to burn-in my SLiMulations. In short, I want to burn-in my forward simulations with mutations generated from msprime, but I don't want to keep the tree sequences afterwards. I've been testing the current head for this and encountered a problem. I can import my .trees file just fine, however the simulation slows considerably compared to simulations which don't read in a tree sequence (~3.5x slower in my simple test case). I looked into this a bit more and found I can call `sim.treeSeqOutput()` in these models, whereas `treeSeqOutput()` results in an error for my standard forward-time burn-in simulation. In addition, occasionally memory usage will skyrocket in models using `readFromPopulationFile()`, with memory continuing to increase as the simulation continues. However, this memory usage spike isn't 100% consistent, and I haven't been able to find what conditions cause this behaviour. My suspicion is that the tree sequences are somehow still being kept track of after the .trees are read in, as I'm unsure as to what else would cause this. 

I've attached some [example scripts](https://github.com/MesserLab/SLiM/files/7592634/treeforward.zip) - they both have the same parameters, but you'll notice the non-tree-sequence-initialised simulation runs much faster and errors out when asked to output a tree sequence (as expected). The tree model loads in a tree sequence and runs considerably slower, and uses more memory. It also _can_ output a tree sequence, even though `initializeTreeSeq()` hasn't been called.

Looking forward to hearing your insights!

**Comment by bhaller** [comment]
Hmm, interesting.  I'll look into it; thanks for the report.

**Comment by bhaller** [comment]
OK, straightforward.  Sorry about the bad fix the first time around.  I'll push a new fix in a moment that should clear things up.  Both models error out on `outputTreeSeq()` now, and both run in the same time; tree-sequence recording _really_ is turned off now.  (It was getting turned off, but then it was being forced back on again as a side effect of some of the loading code, which I hadn't realized would happen.)  Actually the models you linked to _don't_ run the same speed, but that's because the model that loads the `.trees` gets a population size of 379 from the `.trees`; if I add a call to `p0.setSubpopulationSize(500);` after loading then they run the same.

Thanks for noticing this discrepancy; it's good not to ship this dumb bug in the next release.  :->  Do continue to keep your eyes open for other issues with this; this option of loading in a `.trees` even though tree-seq is not enabled is a totally new way of using the software, which is hard to comprehensively test against the zillion different ways it might interact with everything else (WF vs. nonWF, nucleotides vs. not, etc. etc.), so other bugs might remain.  Thanks!
