### ISSUE TITLE
A recipe in the manual about N vs. Ne would be useful

### ISSUE THREAD

**Issue by bhaller** [MesserLab/SLiM#252]
This is an FAQ, so it'd be good to have a recipe in the manual that helps explain it.  There are a few points to be covered:

- N != Ne; N is a parameter, Ne is an emergent property/metric, derived from empirical measurements

- What factors in a model, given a fixed N, affect Ne?  Why is N != Ne?  Selection, non-random mating, spatiality, what else should be mentioned?

- There are multiple definitions of Ne and they differ, so be careful

- How can the Ne of a given SLiM simulation be measured?

I'm pretty up on the first two points.  The third point is not something I know anything about but I can perhaps crib something from Wikipedia, which seems to have a decent page about Ne.  On the fourth point I probably need some advice; I can't remember whether I've ever measured the Ne of a SLiM model, but there seems to be nothing in the manual about it now, and if I ever have done it, I don't remember how I did it.  Ideally it would be measured in the running model, perhaps based upon either the pedigree-tracking information collected by SLiM with `keepPedigrees=T`, or upon metrics the model collects on itself as it runs (the distribution of the number of offspring per parent?), or upon heterozygosity or something.  But if it's really necessary the measurement could depends upon a recorded `.trees` file; I'd prefer not to have that be the case, though, because I would like to introduce this recipe much earlier in the manual than that, probably in chapter 5 (demography).  Anyhow, how to measure Ne is an area where my knowledge of population genetics gets dangerously thin.  :->  Any advice @philippmesser @petrelharp @DrK-Lo @mnavascues?  Anybody want to write a brief paragraph on point 3 above?  Anybody have Eidos code for measuring Ne somehow that they can share?  Thanks!

**Comment by petrelharp** [comment]
I'm happy to help write down some things. Perhaps @vsbuffalo might have some code to contribute?

**Comment by mnavascues** [comment]
Happy to help, I have the code to calculate Ne in a WF model (outcrossing hermaphrodite case).

**Comment by mnavascues** [comment]
I can also help writing something, but I could not find the SLiM manual on github...

**Comment by bhaller** [comment]
> I can also help writing something, but I could not find the SLiM manual on github...

Yes, the manual doesn't live on GitHub, it's a large Pages document and GitHub doesn't like such things.  :->  Just paste your suggested text here, and I'll worry about formatting it and integrating it into the document.  Thanks!

**Comment by bhaller** [comment]
OK, so I modified your code, @mnavascues, to do a selective sweep rather than setting the population size, and got this:

[Ne plot.pdf](https://github.com/MesserLab/SLiM/files/7696531/Ne.plot.pdf)

Which seems rather nice.  I plotted only the coalescent Ne; for this scenario, the three metrics you provided produce virtually identical results, their curves overlap almost exactly.  I guess the point of your code setting the population size was to show that the metrics were not identical in that case, because one lagged the others by a generation, or some such?  That's kind of a subtle point, though; I'm not sure I want to really get into details about _how_ different coalescence metrics differ, I just want to state that they _do_ differ, so that the reader is aware that that is a thing.  If they want to know more about the details of different metrics, they can go read about it elsewhere.

I also converted it to use LogFile, since that's a new-ish feature I want to show off.  So here's the code, at the moment:

initialize() {
	initializeSLiMOptions(keepPedigrees=T);
	initializeMutationRate(1e-7);
	initializeMutationType("m1", 0.5, "f", 0.0);		// neutral
	initializeMutationType("m2", 0.5, "f", 2.0);		// beneficial
	m2.convertToSubstitution = F;
	initializeGenomicElementType("g1", m1, 1.0);
	initializeGenomicElement(g1, 0, 99999);
	initializeRecombinationRate(1e-8);
}
1 {
	sim.addSubpop("p1", 10000);
	defineGlobal("previous_N", p1.individualCount);
	
	// configure a log file with Ne metrics
	defineConstant("LOG", sim.createLogFile("Ne_log.csv"));
	LOG.addGeneration();
	LOG.addCustomColumn("N(t-1)", "previous_N;");
	LOG.addCustomColumn("N(t)", "p1.individualCount;");
	LOG.addCustomColumn("freq", "beneficialFreq();");
	LOG.addCustomColumn("Ne_coalescent", "prob_coal = sum(K/sum(K)*(K-1)/sum(K)*0.5); 1/prob_coal/2;");
	LOG.addCustomColumn("Ne_inbreeding", "(previous_N*mean(K)-2)/(mean(K)-1+var(K)/mean(K));");
	LOG.addCustomColumn("Ne_variance", "(previous_N*mean(K)-mean(K))/(1+var(K)/mean(K));");
}
2: late() {
	// tabulate parental fecundity and generate a log row
	parentIDs = p1.individuals.pedigreeParentIDs;
	rescaledParentIDs = parentIDs - min(parentIDs);
	k = tabulate(rescaledParentIDs, previous_N - 1);
	defineGlobal("K", k);
	
	LOG.logRow();
	
	defineGlobal("previous_N", p1.individualCount);
}
100 late() {
	target = sample(p1.genomes, 1);
	target.addNewDrawnMutation(m2, 50000);
}
200 {
	sim.simulationFinished();
}

function (float)beneficialFreq(void) {
	beneficialMut = sim.mutationsOfType(m2);
	if (beneficialMut.size() > 0)
		return sim.mutationFrequencies(NULL, beneficialMut);
	return NULL;
}

I think I will probably remove the other two Ne calculations, and move all of the tabulation stuff into a user-defined function called by the LogFile, as the beneficial mutation frequency is done now; it'll make for a much cleaner design.

I'm not 100% sure about removing the other Ne metrics, though; maybe it's nice to provide the code for more than one way of doing it.  I'm annoyed that they produce virtually identical results, though; I was really hoping that they would be visually different, which would make it interesting.  It can be calculated based upon heterozygosity, right?  Would that be likely to be substantially different?  Are there any other ways of calculating it that would provide a different perspective?  I'm not so much opposed to including multiple metrics, I just don't want them to be effectively identical for the example being shown, because that undermines the key point that different ways of measuring it can mean very different things and produce very different results.

So... thoughts on this, @mnavascues and anyone else?  The selective sweep certainly shows that Ne varies even when census size is constant, and the plot is pretty.  I think it gets the message across, and will let me emphasize that N is a model parameter while Ne is something empirical that you _measure_.

**Comment by petrelharp** [comment]
Small correction: the coalescent Ne should be E[K(K-1)]/(N(N-1)):
```
	LOG.addCustomColumn("Ne_coalescent", "prob_coal = sum(K/sum(K)*(K-1)/(sum(K)-1)*0.5); 1/prob_coal/2;");
```

**Comment by petrelharp** [comment]
Also, it might help to point out this won't work for a nonWF model, and in that case to put something in the `reproduction( )` callback to keep track of `K`?

**Comment by petrelharp** [comment]
And - that plot is excellent.

**Comment by petrelharp** [comment]
As for the other Ne: `Ne_inbreeding` and `Ne_variance` are identical in this case because this is a WF population of fixed size, so `mean(K)` is always 2.  I'm forgetting what the precise interpretation of these is - do you have a quick summary, @mnavascues?

**Comment by bhaller** [comment]
> Also, it might help to point out this won't work for a nonWF model, and in that case to put something in the `reproduction( )` callback to keep track of `K`?

Well, maybe people will figure this out on their own; and the implementation has shifted considerably, there is no more K.  See what you think.

**Comment by bhaller** [comment]
OK, here's a draft of the writeup.  Comments welcome – ASAP, please, as SLiM 3.7 is planned to ship any day now.

[SLiM_Manual_Ne.pdf](https://github.com/MesserLab/SLiM/files/7697767/SLiM_Manual_Ne.pdf)

And here's the model, if you want to play around with it:

[Ne_estimation.txt](https://github.com/MesserLab/SLiM/files/7697769/Ne_estimation.txt)

I think I'm happy with how it came out.  I'll close this once the recipe is committed to GitHub.  Thanks for your help, everybody!

**Comment by mnavascues** [comment]
I will read and comment @bhaller proposal tomorrow, but I'll give now my first reactions to some of your comments above. I had added variance and inbreeding Ne because of the point regarding the different definitions of Ne, but if the text is not going to go in detailed and the example does not show differences between them I think it is better to remove them from the recipe. The code/equations are not very general and they would be invalid for some more complex models. Coalescent Ne is more versatile even though it might need some modifications for other models, certainly for nonWF as pointed out by @petrelharp. This should be explicitly mentioned.

Regarding the interpretation of inbreeding Ne and variance Ne:
Inbeeding Ne measures how much inbreeding increases due to drift, that is why Ne take values close to the populations size from the previous generation (in the example I gave above). That is if the previous generation has few individuals, it does not matter that current generation has thousands of individuals, they are going to be very inbreed
Variance Ne measures how much allele frequencies change from one generation to another. In this case is the size of the current generation that matters: if the previous generation was huge but current generation is small there will be many loci with large changes in allele frequencies.
Right now I do not remember the derivation of the equation, I would need to check the original publications, but you must notice that previous_generation_N * mean(k) = current_generation_N, so it seems intuitive that mean(k) should appear in the equation.

**Comment by bhaller** [comment]
I think @philippmesser was thinking that of the three you provided he might want to include the inbreeding one, not the coalescent one.  IIRC he thinks that many might object to the coalescence-time estimate coming from just a single generation – that many might feel that that one is not really correct, for that reason.  Perhaps he will correct me, I might be misremembering his rationale.

**Comment by mnavascues** [comment]
The inbreeding Ne would be also for one generation. In any case, for the Ne over several generations, you can take the harmonic mean. At the end of the day, which is the appropriate Ne depends a lot on what information the user wants from Ne. If it is for recapitation, I think harmonic mean of IIRC could be the best option. But there might be as many different reasons to calculate Ne as users...

**Comment by mnavascues** [comment]
Regarding the text proposed for the manual, I think it is fine. I do not like this "heterozygosity Ne" because it is meaningless during the first part of the simulation (until reached the first coalescence) and then it measures Ne in an unspecified period of time (around the last 2N generations). Also, I think Ne is supposed to measure genetic drift, not diversity. But I understand that others might have a different opinions and different needs, so you can ignore my rant ;) .

Regarding the calculation of inbreeding and variance Ne, I think the appropriate citation would be James F. Crow & Motoo Kimura 1970 "An Introduction to Population Genetics Theory" Harper and Row, New York.

For the coalescent Ne, note that I did not take the equation from anywhere, I just worked out the probabilities, so if there is really something wrong as @petrelharp suggest it is worth verifying it.

**Comment by philippmesser** [comment]
Hi Miguel et al,

My experience has been that the "heterozygosity Ne" is actually among the
most widely used definitions in practical applications. Heterozgosity often
is the one thing that can be measured relatively easily for a natural
population of which little is known about its demographic history,
structure, etc. So together with an independent estimate of the mutation
rate, it makes sense that people sometimes just try to fit a simple WF
model of constant size to their study population through the relation pi
=4Ne*mu.

This definition obviously makes less sense for non-equilibrium populations
such as a simulation during burn-in or a locus where a sweep has just
occurred. However, this just illustrates to me how one always has to
consider very carefully what estimate one wants to capture with a
particular definition. I think Ben does a very good job at discussing this
in the earlier sections on the general concept of Ne.

Miguel, as for your definition of "coalescence Ne", I'm a bit concerned
that there could be confusion with the definition put forth in this classic
paper: https://doi.org/10.1534/genetics.104.026799. There, coalescence Ne
is estimated over a timescale that is longer than a single generation, and
its existence is actually contingent on demographic fluctuations and
coalescence events occurring over different timescales. By contrast, your
definition could vary for every generation. To make things even more
confusing, some folks (including Wikipedia!) refer to the definition of
"heterozygosity Ne" Ben uses as "coalescence Ne". This is presumably
because pi is the product of the mutation rate and two times the expected
time to pairwise coalescence, which is 2Ne in a WF model.

So it seems different people can mean very things when they use coalescence
Ne, and I'm not sure we want to get drawn into this debate in the SLiM
manual. Maybe we should therefore just leave out coalescence Ne?

As for your definition of variance Ne, Miguel, I have some difficulties
interpreting this as well. My understanding of variance Ne has always been
that it measures the variance in allele frequency differences over the
time-scale of one generation, which should be Var[x(t+1)-x(t)] =
x(1-x)/(2Ne) in a WF model. So an effort to measure this variance directly
should look at allele frequency differences, no? Does your definition
account for the fact that carriers of one allele can have a different
average fecundity than those of the other, for example in a selective sweep?

Anyways, I think this fun discussion just provides a great example of how
intricate this whole Ne business is.

Philipp

**Comment by bhaller** [comment]
OK, great discussion folks.  I've made some executive decisions and the final result is here (but no need to reread it unless you really want to):

[SLiM_Manual_Ne.pdf](https://github.com/MesserLab/SLiM/files/7706725/SLiM_Manual_Ne.pdf)

I chose to focus on the heterozygosity Ne and Miguel's inbreeding Ne, for clarity and to avoid any controversy about the definition of "coalescence Ne" etc.  Anyway the main goal is to show two different Ne estimators that produce very different results, to underline that choosing one's estimator carefully is important; I think the writeup underlines that well now.  Great comments everybody.  I added some emphasis of the fact that the inbreeding estimator code works only with a WF model here, and would have to be adapted for nonWF particularly with overlapping generations.  I also added a mention of smoothing across generations with a harmonic mean, with the caveat that that might smooth away transients that actually mean something.  I think it has come together very well.  This issue will be closed momentarily, when I push the recipe to GitHub.  Thanks everybody!
