### ISSUE TITLE
empty population metadata should be `'null'` not `''`

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#258]
We've switched from the `struct` codec to the `json` codec for encoding population metadata. And, recall that the metadata schema allows either "object" or "None" for metadata. Well, it turns out that while the struct codec expects no bytes to mean "no metadata", the json codec expects the string of four characters `"null"`. I guess this is how [JSON represents null/empty values](https://stackoverflow.com/questions/45882285/what-is-the-json-standard-for-an-empty-string-or-null-variable). It might have been nice to allow the empty metadtaa for the json codec as well, but we haven't done that.

**Comment by bhaller** [comment]
OK, so.  This was fixed by your PR; the question is, is there a bug here that should be logged on tskit?  My vote is "yes".  It seems annoying/silly to have to put "null" in for the metadata of every single row in a table, just because the schema is JSON instead of struct.  It's a waste of space and time.  Worth logging an issue?
