### ISSUE TITLE
[Documentation] SLiM Manual

### ISSUE THREAD

**Issue by bryce-carson** [MesserLab/SLiM#284]
@bhaller, can you share the current workflow for how the SLiM Manual is built? Last time I contributed to it we passed back and forth Apple Pages files over email. We can do that again if that is what works for you; I'm okay using the "Track Changes" feature in Pages, doesn't bother me any more than a plain diff!

**Comment by bhaller** [comment]
Hi @bryce-carson.  The SLiM manual is simply a Pages file that lives on my computer.  It can't be on GitHub because Pages files are binary, and it is quite large, and GitHub doesn't like that.  :->  It's almost 25 MB, so it also doesn't fit through email well in its entirety.  Assuming that this issue has to do with improving the installation instructions in chapter 2 (can you change the title of this issue to reflect what the actual issue is?), I will email you the current chapter 2, and you can do changes with Track Changes on, and I'll merge them in.  For changes to make 3.7.1, please do them today or _maybe_ tomorrow; I am rolling 3.7.1 as fast as I can now.

**Comment by bhaller** [comment]
@bryce-carson email sent.

**Comment by bryce-carson** [comment]
Hi @bhaller, I've made the changes and you can review them and accept if you'd like to include in this release.

Email sent now. :)
