### ISSUE TITLE
calcFST taking average of ratios rather than ratio of averages

### ISSUE THREAD

**Issue by jgroh** [MesserLab/SLiM#296]
I was noticing some unexpectedly low Fst estimates for two populations using the `calcFST` function in this population split script below. I was comparing Fst values to a theoretical expectation of T/(T+4N) where T is the number of generations since the population split. When I calculated Fst using the ratio of average heterozygosities I was getting much closer to the expected answer. When I tried manually calculating Fst as the average of ratios at each locus, I was getting the same results as output by calcFST. It seems like this has been discussed in the literature on estimating Fst and the recommendation is generally to use a ratio of averages as opposed to an average of ratios which can be badly biased e.g. [https://genome.cshlp.org/content/23/9/1514.long](url) Perhaps the default for `calcFST` should be to calculate a ratio of averages instead? See script below for a comparison. 

```
initialize() {
defineConstant("N", 100);
initializeMutationRate(1e-7);
initializeMutationType("m1", 0.5, "f", 0);
initializeGenomicElementType("g1", m1, 1.0);
initializeGenomicElement(g1, 0, 999999);
initializeRecombinationRate(1e-8);

}

1 {sim.addSubpop("p0", N); }

1000 {sim.addSubpopSplit("p1", N, p0); }

10000 {
    
// slim function - seems to be calculating average of ratios
catn(calcFST(p0.genomes, p1.genomes));
    
// vs.  ratio of averages

// average heterozygosity of subpopulations
Hs = mean(c(calcHeterozygosity(p0.genomes), calcHeterozygosity(p1.genomes)));

// heterozygosity of total population
Ht = calcHeterozygosity(c(p0.genomes, p1.genomes));

// genome-wide Fst
catn(1-(Hs/Ht));

}
```

**Comment by bhaller** [comment]
Hi @jgroh.  So, since I am not a population geneticist, I don't really have a handle on what your objection is, apart from the calculated values being in some way not what you expected them to be, or how I would go about fixing it.  The source code for `calcFST()` can be seen by doing `functionSource("calcFST")`:

```
(float$)calcFST(object<Genome> genomes1, object<Genome> genomes2, [No<Mutation> muts = NULL], [Ni$ start = NULL], [Ni$ end = NULL]) <SLiM>
{
	// handle windowing
	if (!isNULL(start) & !isNULL(end))
	{
		if (start > end)
			stop("ERROR (calcFST()): start must be less than or equal to end");
		if (isNULL(muts))
			muts = sim.mutations;
		mpos = muts.position;
		muts = muts[(mpos >= start) & (mpos <= end)];
		length = end - start + 1;
	}
	else if (!isNULL(start) | !isNULL(end))
	{
		stop("ERROR (calcFST()): start and end must both be NULL or both be non-NULL");
	}
	
	// do the calculation
	p1_p = genomes1.mutationFrequenciesInGenomes(muts);
	p2_p = genomes2.mutationFrequenciesInGenomes(muts);
	mean_p = (p1_p + p2_p) / 2.0;
	H_t = 2.0 * mean_p * (1.0 - mean_p);
	H_s = p1_p * (1.0 - p1_p) + p2_p * (1.0 - p2_p);
	fst = 1.0 - H_s/H_t;
	fst = fst[!isNAN(fst)];  // exclude muts where mean_p is 0.0 or 1.0
	return mean(fst);
}
```

How would you propose to modify it?  I'd also like to ping a couple of people who understand this stuff better than I do: @philippmesser @petrelharp @DrK-Lo

**Comment by petrelharp** [comment]
The proposal is to change this to
```
	// do the calculation
	p1_p = genomes1.mutationFrequenciesInGenomes(muts);
	p2_p = genomes2.mutationFrequenciesInGenomes(muts);
	mean_p = (p1_p + p2_p) / 2.0;
	H_t = 2.0 * mean_p * (1.0 - mean_p);
	H_s = p1_p * (1.0 - p1_p) + p2_p * (1.0 - p2_p);
	fst = 1.0 - mean(H_s)/mean(H_t);
	return fst;
```
(right, @jgroh?)

And, I agree with @jgroh that this is the version of Fst that I would much rather get back, and we should encourage others to use this version.

**Comment by bhaller** [comment]
OK, thanks, that is very helpful.  Is there any utility to the present version – do we want to provide both versions, under different names or selected by a flag passed in?  Or should I just replace the current version with this?  Should I worry about backward compatibility?  (If so, I could give this new version of the function a new name, so that existing code using calcFST() will break.)

**Comment by petrelharp** [comment]
My inclination would be to make it an option (maybe called `perSite`), but curious what others say.

**Comment by bhaller** [comment]
> My inclination would be to make it an option (maybe called `perSite`), but curious what others say.

I gather the default ought to be the new way (`perSite=F`, if I understand correctly?), so behavior would change for existing code; do you think that's a problem?

**Comment by petrelharp** [comment]
It is a breaking change; maybe it's a good one for the SLiM v4.0 list?

**Comment by bhaller** [comment]
Yeah, it's pretty definitely going into 4.0 now; I'm hoping to keep the 3.x release cycle frozen if possible.  My preference for breaking changes is to make them really break – silent changes in behavior are bad.  So I want to either (a) change the name of this function, so that old code calling it explicitly breaks, or (b) add a flag parameter like `perSite`, but make it default to the old behavior.  So to me, the question is whether the old behavior is useful/defensible (even if the proposed new behavior is arguably better), or whether it should just be considered wrong.  If useful/defensible, then I think I'll do (b); if just wrong, then I think I'll do (a).  So opinions regarding that question are needed.  :->

**Comment by petrelharp** [comment]
Historically, people have totally done both ways of calculating Fst, so the existing implementation is totally defensible. However, as @jgroh says, it's definitely best practice to do ratio-of-averages. If there was a natural new name to change it to, I'd vote to obsolete the existing code? But, I'd like to hear what others say.

BTW, the documentation is misleading on this:
![Screenshot from 2022-04-11 09-20-55](https://user-images.githubusercontent.com/1046249/162786152-1dc2df9a-f0fc-4ead-bf9e-1e2ac39ed599.png)

**Comment by mnavascues** [comment]
I think the default behavior should be ratio of averages. Giving the option for the users will make many users to use the biased estimator (default option) either because they don't read the documentation or because they are not aware of the difference. So I would suggest the first option (remove `calcFST()`, add new function... `FST()`? `calculateFST()`?).

**Comment by bhaller** [comment]
OK, two votes to obsolete the old and give a new name to the new.  @petrelharp, you wrote:

> BTW, the documentation is misleading on this...

Can you clarify what exactly is misleading?  And will that doc cease to be misleading, with no wording change, when the function's implementation is changed as proposed?  Or if not, how should the doc be changed?  I really am clueless on this stuff.  :->

**Comment by jgroh** [comment]
I also vote that the default behaviour should be to use a ratio of averages. If this becomes the new default, I would find the following line from the documentation unclear:
> The implementation of calcFST() ... treats every mutation in muts as independent in the heterozygosity calculations

A small addition to the documentation should help clarify what is happening, e.g. 

> The FST value reported is an average across the specified mutations in the two sets of genomes, where H_s and H_t are first averaged across all specified mutations prior to taking the ratio of the two, which yields better statistical properties.

**Comment by bhaller** [comment]
OK, I'm about to commit this fix.  It will be in the `multispecies` branch of SLiM on GitHub, which will become SLiM 4; I'm not planning another 3.x release.  In the end, I decided that since the "average of ratios" is considered biased and poor practice (even if still often used, sigh), and the "ratio of averages" is considered best practice, I would regard this change as a bug fix.  In light of that, I kept the name `calcFST()` and I will make it clear in the release notes that the behavior of the function changed in SLiM 4 as a result of fixing what I regard as a bug.

I tried to edit the documentation to clarify things.  Here's what I ended up with; I can of course make further changes if necessary, but this seems pretty clear to me:

> Calculates the FST between two Genome vectors – typically, but not necessarily, the genomes that constitute two different subpopulations (which we will assume for the purposes of this discussion).  In general, higher FST indicates greater genetic divergence between subpopulations.
> The calculation is done using only the mutations in muts; if muts is NULL, all mutations are used.  The muts parameter can therefore be used to calculate the FST only for a particular mutation type (by passing only mutations of that type).
> The calculation can be narrowed to apply to only a window – a subrange of the full chromosome – by passing the interval bounds [start, end] for the desired window.  In this case, the vector of mutations used for the calculation will be subset to include only mutations within the specified window.  The default behavior, with start and end of NULL, provides the genome-wide FST, which is often used to assess the overall level of genetic divergence between sister species or allopatric subpopulations.
> The code for calcFST() is, roughly, an Eidos implementation of Wright’s definition of FST (but see below for further discussion and clarification):
> FST = 1 - HS / HT
> where HS is the average heterozygosity in the two subpopulations, and HT is the total heterozygosity when both subpopulations are combined.  In this implementation, the two genome vectors are weighted equally, not weighted by their size.  In SLiM 3, the implementation followed Wright’s definition closely, and returned the average of ratios: mean(1.0 - H_s/H_t), in the Eidos code.  In SLiM 4, it returns the ratio of averages instead: 1.0 - mean(H_s)/mean(H_t).  In other words, the FST value reported by SLiM 4 is an average across the specified mutations in the two sets of genomes, where H_s and H_t are first averaged across all specified mutations prior to taking the ratio of the two.  This ratio of averages is less biased than the average of ratios, and and is generally considered to be best practice (see, e.g., Bhatia et al., 2013).  This means that the behavior of calcFST() differs between SLiM 3 and SLiM 4.
> The implementation of calcFST(), viewable with functionSource(), treats every mutation in muts as independent in the heterozygosity calculations; in other words, if mutations are stacked, the heterozygosity calculated is by mutation, not by site.  Similarly, if multiple Mutation objects exist in different genomes at the same site (whether representing different genetic states, or multiple mutational lineages for the same genetic state), each Mutation object is treated separately for purposes of the heterozygosity calculation, just as if they were at different sites.  One could regard these choices as embodying an infinite-sites interpretation of the segregating mutations.  In most biologically realistic models, such genetic states will be quite rare, and so the impact of these choices will be negligible; however, in some models these distinctions may be important.

Thanks for your help, everybody!

**Comment by petrelharp** [comment]
Here's a paper discussing this, btw: https://genome.cshlp.org/content/23/9/1514.long

**Comment by bhaller** [comment]
> Here's a paper discussing this, btw: https://genome.cshlp.org/content/23/9/1514.long

Yep – "(see, e.g., Bhatia et al., 2013)" in the above doc excerpt.  @jgroh beat you to it.  :->
