### ISSUE TITLE
Recombination callback triggers tsk_table_collection_deduplicate_sites

### ISSUE THREAD

**Issue by vsbuffalo** [MesserLab/SLiM#297]
@petrelharp and I have been exploring some more recombination callback tricks similar to the inversion recipe we worked with you on before. Here, we're trying to evolve a segment under selection and look at the effect at a bunch of independent "tracking" sites (in terms of the tree sequences) that are each a basepair long. But here's the catch — we want to hack the recombination callback so the tracking sites are all X recombination fraction apart from the selected segment. That way, in a single evolutionary replicate, we can average over lots of linked neutral trees in a single simulation to reduce noise.

We think we've found a way to do this (this is fairly preliminary!) but run into the following error: 

```
Error:tsk_table_collection_deduplicate_sites: Right coordinate > sequence length
tsk_table_collection_deduplicate_sites: Right coordinate > sequence length
```

Below is an MRE: 

```
initialize() {
  initializeTreeSeq();
  // selected segment
  defineConstant("segment_length", 10000);
  defineConstant("track_length", 100);
  defineConstant("region_length", segment_length + track_length);
  // vector of all tracked bp for finding breakpoints
  defineConstant("trackbp", seq(segment_length, region_length-1));
	
  defineConstant("seglen", 10000);
  defineConstant("rep", 0);
  defineConstant("rbp", 1e-8);
  defineConstant("recfrac", 0.001);
  defineConstant("N", 1000);
  defineConstant("s", -2e-2);
  defineConstant("mu", 1e-8);
  defineConstant("h", 0.5); 

  // Runtime settings
  defineConstant("burnin", 10*N);
  defineConstant("endsim", burnin);

  initializeMutationRate(mu);
  initializeMutationType("m1", h, "f", -s);
  initializeGenomicElementType("g1", m1, 1);
  initializeGenomicElement(g1, 0, segment_length-1);

  initializeRecombinationRate(0); // since handled in the recombination callback
}

recombination() {
  // we break this into figuring out the breakpoints for the 
  // tracking regions and selected segment separately
  X = 1-rbinom(track_length, 1, recfrac);
  Y = 1-c(X[0], X[1:(length(X)-1)] == X[0:(length(X)-2)]);
  tracking_breakpoints = trackbp[which(asLogical(Y))];
  segment_breakpoints = rdunif(rpois(1, rbp*segment_length), 0, segment_length-1);
  breakpoints = sort(unique(c(segment_breakpoints, tracking_breakpoints)));
  assert(all(breakpoints < region_length));
  return T;
}

1 {
  sim.addSubpop("p1", N);
  sim.rescheduleScriptBlock(s1, start=2, end=endsim);
  sim.rescheduleScriptBlock(s2, start=endsim, end=endsim);
}

s1 {
  cat(paste(sim.generation, "/", endsim, "\n"));
}

s2 late() {
  sim.treeSeqOutput("recomb2.tree", metadata=metadata);
}
```

One thing we thought initially is that we could have an off-by-one error and a breakpoint is landing outside of bounds (or exactly on the right bound). However, subtracting 1 or 10 doesn't prevent the error.

Peter's thinking with the callback routine is this: let `X_i` be an indicator that locus `i` is inherited alongside locus 0, for `1 ≤ i ≤ n`. The `X_i` should be i.i.d. `Bernoulli(recfrac)`. If we let `Y_i` be an indicator that locus `i` should be inherited with locus `i-1` (no crossover). We then set `Y_1 = X_1`, and then for `i > 1`, `Y_i = 1` iff `X_{i-1} = X_{i}` and `Y_i = 0` otherwise. This is what the callback routine (should) be doing.

**Comment by bhaller** [comment]
Hi @vsbuffalo.  I set a breakpoint on the spot where the error gets raised, in `tsk_table_collection_check_edge_integrity()`:

```
        if (right > L) {
            ret = TSK_ERR_RIGHT_GREATER_SEQ_LENGTH;
            goto out;
        }
```

`L` is 10000, `right` is 10009, for the run I did.  You set up the chromosome to span from 0 to `segment_length-1`:

`initializeGenomicElement(g1, 0, segment_length-1);`

So it goes from 0 to 9999 (as you can verify in SLiMgui).  But your `assert()` tests something different:

`assert(all(breakpoints < region_length));`

It looks like `region_length` is 10100.  So you're allowing a breakpoint at 10009 to be returned, even though that is past the end of the chromosome.  I guess SLiM just ignores that (I'm not sure whether to regard that as a bug or not – recombinations past the chromosome end do nothing, so ignoring them is not unreasonable), but the tree sequence doesn't like it, so you get the raise.  If you want the chromosome to span up to 10099, then set it up that way; if you don't want the `g1` genomic element to extend out into those last 100 positions, then force the chromosome length to extend beyond the end of the genomic element by passing `region_length-1` as the end position in your call to `initializeMutationRate()` or `initializeRecombinationRate()`; the chromosome extends out to whatever the maximum is among the end of the mutation rate map, recombination rate map, and the last genomic element.  Or just make the mutation rate be 0 for the last 100 bases, in which case extending the genomic element out to cover that area should be harmless; whatever you prefer.

BTW, I didn't try to really grok your code, but I'm confused by your description:

> Here, we're trying to evolve a segment under selection and look at the effect at a bunch of independent "tracking" sites (in terms of the tree sequences) that are each a basepair long. But here's the catch — we want to hack the recombination callback so the tracking sites are all X recombination fraction apart from the selected segment.

Can this not be done simply by setting up a recombination rate map with the appropriate rates between the positions?  I think I missed something.  :->  Anyway, I think I've diagnosed your bug here, although I'm not sure what the right fix to your callback code is, so I'm going to close; feel free to re-open if you think there is actually a SLiM bug here, but it looks to me like things are working properly – you're getting an error because you requested a breakpoint that is beyond the end of the chromosome.
