### ISSUE TITLE
feature request: visualizing multispp models in slimgui

### ISSUE THREAD

**Issue by bobweek** [MesserLab/SLiM#307]
previously i had been representing different species as subpopulations. i found it convenient that slimgui would display the population sizes and spatial positions side-by-side. however, using the new multispp tools, this information is displayed in different tabs. being able to watch both sources of information is helpful for debugging and finding "sweet-spots" in parameter space. im finding myself pausing slim and switching between tabs to obtain the same information which is hindering my productivity. is it possible to display multispp information similarly to the way multiple subpopulations are visualized?

**Comment by bhaller** [comment]
I plan to add an "all" tab to the species tab bar, which will show everything together; just hasn't been implemented yet.  :->

The big obstacle, though, is that I haven't figured out what to do with the chromosome view.  The other views – the population table, the individuals views – can accommodate that "all" mode seamlessly.  But the chromosome view is tailored to the species in ways that make it hard to share – the x scale spans the length of the chromosome (which could be different between species), the y-heights of bars indicate frequency (which is frequency in one species), and in any case showing mutations from more than one species mixed up together in one chromosome view seems wrong.  I don't want to get into showing multiple chromosome views, one per species, stacked on top of each other in the main window, though; that would get quite messy, wouldn't work well for more than two species, and is a bit difficult to code as well, since the layout of the main window isn't really that dynamic.

So, what to do?  I'm really not sure.  I'm pondering the possibility of adding a way for the user to open a new chromosome view for a particular species in a separate window.  You could then open one for fox and one for mouse, and see both at once, and put them where you want them to be on the screen.  That leaves the chromosome window in the main window useless, though, which is a huge waste of screen real estate.  I haven't thought of the right design yet.  Any ideas?  @petrelharp tagging you as well, since maybe you've been playing with this too.  :->

**Comment by bobweek** [comment]
oh nice! looking forward to the "all" tab :)

i didn't mind looking at the chromosomes side-by-side when i was simulating different species as subpopulations. it was a little misleading as the heights would change as relative abundances of species changed, even if allele frequencies within species were constant. im sure that can be fixed in this new version, but then it may become awkward when species have subpopulations...

**Comment by bhaller** [comment]
> oh nice! looking forward to the "all" tab :)

:->

> i didn't mind looking at the chromosomes side-by-side when i was simulating different species as subpopulations. it was a little misleading as the heights would change as relative abundances of species changed, even if allele frequencies within species were constant. im sure that can be fixed in this new version, but then it may become awkward when species have subpopulations...

Yeah, I don't think that's a viable path forward.  :->

**Comment by bhaller** [comment]
After some more pondering, I think maybe I have an idea I like.  I have been thinking about adding additional chromosome views, for additional species, _vertically_, but I didn't like that idea because it would chew through so much vertical space – on a laptop screen, with three species, you'd have hardly any room left for your script and output views.  But it just dawned on me that I could add the additional chromosome views _horizontally_ instead.  In other words, take the space that is now occupied by the chromosome view, and if there are two species, then (when on the "all" tab) divide that space in half, and show a chromosome view for one species on the left, and a chromosome view for the other species on the right.  The gear "action button" on the right would control both views, for simplicity; I don't see any real need to be able to independently configure things like whether the recombination rate map is displayed or not, etc., that config can all be shared.  And even on a laptop screen it seems like it would work quite acceptable with three or four species; it's nicer to see mutations spread out over a longer horizontal axis, of course, but squeezing them horizontally is not the end of the world.  I think this is what I will do.

**Comment by bhaller** [comment]
OK, you now get side-by-side chromosome views when you select the "all" species tab in a multispecies model (as well as the other expected changes for "all").  This involved extensive changes under the hood that may have been destabilizing for SLiMgui (not for SLiM); you might get a crash or other bad behavior.  It'd be great if you could play around with it and report any problems you see.  I will optimistically close this issue, though, since it seems to be working well for me.  :->
