### ISSUE TITLE
Approach for calculating inbreeding load

### ISSUE THREAD

**Issue by ckyriazis** [MesserLab/SLiM#310]
Following up on this [issue](https://groups.google.com/g/slim-discuss/c/qcqs3Fu8_90/m/EdaMwnL4BwAJ?utm_medium=email&utm_source=footer&pli=1) - I coded up an approach for calculating the inbreeding load in a population, which may be useful to include as a function in SLiM. In brief, the inbreeding load is a measure of the quantity of recessive deleterious variation concealed in heterozygosis in a population, or in other words, a measure of the potential impact of inbreeding depression under future inbreeding. See [Morton et al 1956 ](https://www.pnas.org/doi/abs/10.1073/pnas.42.11.855)for further detail. 

The code is as follows: 

```
muts = unique(p1.genomes.mutations);

q = p1.genomes.mutationFrequenciesInGenomes(muts);

s = -muts.selectionCoeff;

// replace mutations with s>1.0 with 1.0 (can happen when drawing from gamma distribution)
s[s>1.0]=1.0;

// get h for each mutation
// note that this will not work if changing h using fitness callbacks
h=muts.mutationType.dominanceCoeff;

// calculate number of diploid lethal equivalents (2B or inbreeding load)
// equation from Morton et al 1956
2*(sum(q*s)-sum(q^2*s)-2*sum(q*(1-q)*s*h));
```

Note that one issue with this approach is that it will not work as intended when changing the dominance coefficient (h) of a mutation using fitness() callbacks. For example, its typically desirable to set h as a function of s, whereby h becomes more recessive (closer to 0) as s gets more deleterious (closer to -1). In that case, it may be possible to to get h for each mutation using that function, but I am not sure the best way to incorporate such an approach in a function for general use.

**Comment by bhaller** [comment]
Thanks @ckyriazis!  I'll likely add this as a function like:

- (float$)calcInbreedingLoad(object<Subpopulation> subpopulations)

Any comments from the popgen folks on here, such as @philippmesser @petrelharp @mnavascues @DrK-Lo?  I would probably use pretty much the description @ckyriazis put above for it, since I don't know enough about this stuff to try to expand upon that text.  :->  Is there anything else that should be said on the topic?  Is the definition of this term controversial?  Are there alternative definitions that would lead to a different numerical result, which should be noted?

**Comment by mnavascues** [comment]
I am not very familiar with the definition of "inbreeding load" but it is a relatively common measure of inbreeding depression in many theoretical and conservation genetics papers. Regarding the exact equation proposed by @ckyriazis I cannot comment on whether there are better alternatives to quantify it. Now, I am not sure of the factor two (this is pop gen after all...), on what I have seen, inbreeding load=B (not 2B) and 2(A+B) is the number of diploid lethal equivalents (but I have no experience on this topic, so input from someone else could be useful).

from [Morton et al 1956](https://www.pnas.org/doi/abs/10.1073/pnas.42.11.855)
B = sum(q*s)-sum(q^2*s)-2*sum(q*(1-q)*s*h)
A = x + sum(q^2*s)+2*sum(q*(1-q)*s*h)

**Comment by ckyriazis** [comment]
Hi @mnavascues - thanks for weighing in. Youre correct that the factor of two may or may not be desirable to include - it really just depends if we would want the function to estimate the inbreeding load / number of lethal equivalents per haploid or per diploid (I tend to prefer 2B since I think its more intuitive to think about this quantity at an individual level, but others may disagree). 

As for the A term, this measures the reduction in fitness under no inbreeding, so is somewhat different from the inbreeding load B. In other words, A is the y-intercept of a regression line between log(fitness) as a function of levels of inbreeding and -B is the slope. See [Hedrick & Garcia-Dorado 2016](https://www.sciencedirect.com/science/article/pii/S0169534716301586) and [Nietlisbach et al. 2018](https://onlinelibrary.wiley.com/doi/full/10.1111/eva.12713) for recent reviews that also touch on this issue.

**Comment by bhaller** [comment]
That is very helpful, thanks @ckyriazis.  Not being a pop geneticist myself, I'm not sure I understand all of the subtle points here.  @ckyriazis would you mind writing up a brief summary of what exactly your code does, similar to the writeups the other `calc...()` functions in SLiM have?  It should explain the factor of two choice made in your implementation and how to correct the result if the user wants the other choice, and clarify this A vs. B business.  Sorry, I just don't know how to translate the above discussion into good documentation, since I don't understand the issues involved.  Thanks!

**Comment by ckyriazis** [comment]
Sure! I will do this as soon as possible.

**Comment by bhaller** [comment]
Hi @ckyriazis, just a ping.  :->

**Comment by ckyriazis** [comment]
Hi Ben - sorry for the delay...heres my stab at it:

__________________
Calculates inbreeding load (the haploid number of lethal equivalents or B) for a vector of genomes. The inbreeding load is a measure of the quantity of recessive deleterious variation that is heterozygous in a population and can contribute to fitness declines under inbreeding. This function implements the equation from Morton et al. 1956, which assumes no epistasis and random mating:
            
B = sum(q*s) - sum(q^2*s) - 2*sum(q*(1 - q)*s*h)
 
Where q is the frequency of a given deleterious allele, s is the absolute value of the selection coefficient, and h is its dominance coefficient. Note that, by default, the implementation sets a maximum |s| of 1.0 (i.e., a lethal allele), as |s| can sometimes be >1.0 when drawn from a distribution, though in practice an allele with |s|>1.0 has the same lethal effect as when s=1.0. Also note that this implementation will not work when changing the dominance coefficients of mutations using fitness() callbacks, as it relies on the dominanceCoeff property of each mutation type [Ben: is there any way to work around this? perhaps we can have users supply the dominance function as an input if they use one?]. Finally, note that, to estimate the diploid number of lethal equivalents (2B), the output of this function can simply be multiplied by two.
__________________


Note that I decided it might just be simpler to calculate the haploid inbreeding load (B) and let users multiply that by two to get the diploid inbreeding load if desired (so please remove the factor of two at the start of the last line in the code block I posted at the top of this thread). Also, I had made an attempt to address the A vs B issue, but decided it is a bit hard to explain without the full context of Morton 1956. So my opinion is that we dont need to explain it here, as it may be confusing and A isnt the inbreeding load and, though it can contribute to the number of lethal equivalents, in practice it is quite small and is ignored in studies of inbreeding depression. For example, A is not even really discussed in [these](https://www.sciencedirect.com/science/article/pii/S0169534702024898) [two](https://www.sciencedirect.com/science/article/pii/S0169534716301586?via%3Dihub) highly cited reviews on this topic. 

Let me know what you think!

**Comment by bhaller** [comment]
@ckyriazis This looks great, thanks!  Your timing is good, I'll work on this today I think.

I don't feel like it's necessary to get into trying to support scripted modifications of dominance coefficients.  The source code for this function will be available in Eidos (as with all the popgen functions in SLiM), so people who are sufficiently motivated can simply copy your code and modify it to do what they want.

A function name of `calcInbreedingLoad()` seems good, I'll go with that unless you object.  (It could be `calcHaploidInbreedingLoad()` but that seems wordy and the doc explains it well, so that feels unnecessary.)

Rather than talking about `|s|` it should just talk about `s`, no?  I.e., your code does:

`s[s>1.0]=1.0;`

and never calls `abs()`; mutations that are strongly beneficial, rather than strongly deleterious, will not be clipped to a maximum magnitude.  (But it does do `s = -muts.selectionCoeff` which I suppose is why you're talking about |s|?)

A final question: would it be useful for the function to take a mutation type, which it would limit the calculations to?  If so, that's easy, I'm happy to add it in; I'm just making sure there's no reason _not_ to do it.

Oh, one more thing.  I notice that the code does `muts = unique(p1.genomes.mutations)` to focus in on mutations that are present in the focal subpopulation.  It looks to me like there would be no harm in just using `sim.mutations`, though; any mutations not present in the focal subpopulation would have `q` of 0, and so would just drop out of the summations harmlessly.  I'm not missing anything, am I?  (I ask because unique() is slow, and p1.genomes.mutations is also very slow, for big models.)

I'm going to go on the assumption that I've got hold of the right end of the stick, and work up a final version of this as a PR.  I'll post again here when that PR is ready for review.  Let me know if I'm going off-piste, though.  :->  Thanks again!

**Comment by bhaller** [comment]
Oh, one more question.  Is this a statistic that it is useful do calculate "windowed", for only the mutations within some range [start, end] in the genome?  If so, it's easy to add that, of course; I can do that if somebody thinks I should.

**Comment by bhaller** [comment]
Sigh, another question (ironing out all the little details is complicated).  You write "a measure of the quantity of recessive deleterious variation", but the calculations do not exclude beneficial mutations.  Should they?  It would be easy enough to narrow `muts` down to only those mutations that are, in fact, deleterious.  What's the right thing to do?

**Comment by bhaller** [comment]
OK, PR created.  I don't think it ready yet, though; I need clarification on the questions above.

It's hard to read the doc in the form it gets committed to GitHub, so here's what it looks like (sans formatting):

`(float$)calcInbreedingLoad(object<Genome> genomes, [No<MutationType>$ mutType = NULL])`
Calculates inbreeding load (the haploid number of lethal equivalents, or B) for a vector of genomes passed in genomes. The calculation can be done only for a mutation type passed as mutType; if mutType is NULL (the default), all of the mutations for the focal species will be included in the calculation.
The inbreeding load is a measure of the quantity of recessive deleterious variation that is heterozygous in a population and can contribute to fitness declines under inbreeding. This function implements the following equation from Morton et al. (1956), which assumes no epistasis and random mating:
B = sum(qs) − sum(q2s) − 2sum(q(1−q)sh)
where q is the frequency of a given deleterious allele, s is the absolute value of the selection coefficient, and h is its dominance coefficient.  Note that, by default, the implementation sets a maximum |s| of 1.0 (i.e., a lethal allele); |s| can sometimes be greater than 1.0 when drawn from a distribution, but in practice an allele with |s| > 1.0 has the same lethal effect as when s = 1.0. Also note that this implementation will not work when changing the dominance coefficients of mutations using fitness() callbacks, since it relies on the dominanceCoeff property of MutationType. Finally, note that, to estimate the diploid number of lethal equivalents (2B), the result from this function can simply be multiplied by two.
This function was contributed by Chris Kyriazis; thanks, Chris!

It'd be great to wrap this up @ckyriazis; we're almost there!  :->

**Comment by ckyriazis** [comment]
Hi Ben - lots of great points raised above!

- Yes, I think we should limit this to just deleterious mutations, and youre right on point that the `s = -muts.selectionCoeff` is what I really meant when I was making reference to `|s|`. The reason I wanted positive `s` is that Morton et al 1956 assume positive `s` for deleterious mutations, though of course SLiM models deleterious mutations as having negative `s`.
- I also cant see any harm in just using `sim.mutations` if `muts = unique(p1.genomes.mutations)` is slow. 
- I personally have never had the need to calculate the inbreeding load for a window - its conceivable that someone else may want to do this, but that might be unlikely. I'll leave it up to you what to decide here. 

Ok, I think that answers everything, let me know if there was anything I missed!

**Comment by bhaller** [comment]
Hi @ckyriazis.  Almost done, but one important question remains:

> You write "a measure of the quantity of recessive deleterious variation", but the calculations do not exclude beneficial mutations. Should they? It would be easy enough to narrow muts down to only those mutations that are, in fact, deleterious. What's the right thing to do?

Should I filter the vector of mutations down to only those that are deleterious?  Or does it actually make sense to talk about the "inbreeding load" of beneficial mutations?

**Comment by ckyriazis** [comment]
Yes - it would make sense to filter down to only deleterious mutations!

**Comment by bhaller** [comment]
> Yes - it would make sense to filter down to only deleterious mutations!

OK, perfect.  I think I understand everything now; I'll update the PR and post again here when it's ready for review.  Thanks!

**Comment by bhaller** [comment]
OK, the PR is done and merged.  Changes were trivial, apart from adding the exclusion of non-deleterious mutations, so it didn't seem like it needed further review.  Sorry I didn't notice your first reply on that particular point, @ckyriazis; I guess I read too fast.  :->  Anyhow, this is a great addition, thanks again Chris!  I hope I didn't make the process too painful; I'd love to see more popgen utilities like this.  :->

**Comment by ckyriazis** [comment]
Awesome!! Not painful at all. I am so extremely grateful for the heroic amount of work you've put into SLiM so happy to help in any small way I can :)
