### ISSUE TITLE
reading from a tree sequence where individuals are from an already-assigned population

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#313]
Over in #311 I've got [a simple example](https://github.com/MesserLab/SLiM/issues/311#issuecomment-1124085928) where I get the error:
```
ERROR (Population::AddSubpopulation): subpopulation p0 has been used already,
and cannot be used again (to prevent conflicts).
```
The reason for this is that:
1. the first tree sequence I read in defines `p0`
2. in the second tree sequence, my population table defined `p1` and leaves `p0` empty,
3. **but** the individuals all say they're in subpopulation 0, so SLiM assumes there should be a `p0` from this tree sequence also.

Maybe it should not be allowed to load in a tree sequence with individuals referring to a population not defined in the population table, but probably it should at least throw a warning. This was a pretty easy mistake to make, so it'd be nice to have a better error message; if first it warned about this situation that would serve the purpose.

**Comment by bhaller** [comment]
I'm having a weird deja vu feeling because I thought I already wrote this comment.  Maybe I wrote it on the wrong issue.  Anyhow, this situation now produces the error "ERROR (Species::__TabulateSubpopulationsFromTreeSequence): individual has a subpopulation id (0) that is not described by the population table."  Should do the trick.
