### ISSUE TITLE
rows in population metadata without individuals no longer allowed in WF models

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#317]
This is not necesarily a bug but it is a backwards incompatibility: when reading in from a tree sequence file, if there are populations in the table with SLiM metadata but no corresponding metadata, in a WF model, then we get an error with the `multispecies` branch, but we did not with 3.7.1. (Maybe this is the desired behavior, but it's part of the bigger picture in #316.)

To set things up run this script:
```
import pyslim, msprime

demog = msprime.Demography()
demog.add_population(initial_size=10, name='A')
demog.add_population(initial_size=10, name='B')

ts = msprime.sim_ancestry(
        samples={"B" : 5},
        demography=demog,
        sequence_length=100000
)

ts = pyslim.annotate_defaults(ts, model_type='WF', slim_generation=1)
ts.dump("init_msprime.trees")
```
This produces two annotated populations:
```
╔══╤══════════════════════════════════════════════════════════════════════╗
║id│metadata                                                              ║
╠══╪══════════════════════════════════════════════════════════════════════╣
║0 │{'bounds_x0': 0.0, 'bounds_x1': 1.0, 'bounds_y0': 0.0, 'bounds_y1':...║
║1 │{'bounds_x0': 0.0, 'bounds_x1': 1.0, 'bounds_y0': 0.0, 'bounds_y1':...║
╚══╧══════════════════════════════════════════════════════════════════════╝
```
but individuals are only in population `p1`.

Then, run this SLiM script:
```
initialize() {
	initializeTreeSeq();
	initializeMutationRate(0.0);
	initializeMutationType("m1", 0.5, "f", 0.0);
	initializeGenomicElementType("g1", m1, 1.0);
	initializeGenomicElement(g1, 0, 99999);
	initializeRecombinationRate(1e-8);
}

1 late() {
	sim.readFromPopulationFile("init_msprime.trees");
}

20 late() { catn("Done!!!"); sim.treeSeqOutput("final_msprime.trees"); }
```
This works fine in `3.7.1` but using `multispecies` errors with
```
ERROR (Population::AddSubpopulation): subpopulation p0 empty.

Error on script line 11, character 5:

   sim.readFromPopulationFile("init_msprime.trees");
```

**Comment by bhaller** [comment]
Hmm, OK, thoughts on this:

- Out of curiosity, why are there only individuals in `p1`?  The code gives `initial_size=10` for both; shouldn't they both have 10 extant individuals, one with an ancestral history added, one without?  This is presumably just my lack of comprehension of msprime APIs.  :->

- Empty subpops are not allowed in SLiM WF models.  It has ever been thus; setting the size to 0 in WF removes the subpop, so it is a logical contradiction to say that a WF subpop exists but contains no individuals.  I'm surprised that this worked in 3.7.1; the same check is there: https://github.com/MesserLab/SLiM/blob/37e4b933790e7efb985ce1832356ade09a33e0e0/core/population.cpp#L186 .  But I guess something about the code paths has shifted.  I'm a bit curious about what changed; but as you say, it's not clear that this is a bug.  If anything it seems like an improvement to me, fixing a bug that apparently 3.7.1 had.

- If a WF subpop used to exist, and has ancestry in the tree, but is no longer extant, then its metadata should be `"null"`, I think?  This is where I'm not sure whether this is a bug or not.  Should it be OK for such a subpopulation to have metadata?  I guess when reading in, we would just say "well, this is a WF subpop of size zero, so yeah, it has metadata, but it still doesn't exist and we're going to ignore the metadata".  That would be fine, I think.

That last bit might be the right policy, because I suspect we can trigger this same problem entirely in SLiM, meaning that there is a SLiM bug _somewhere_.  Thought experiment: make a SLiM model, WF, two subpops, run a bit, save as step1.trees.  This will have metadata for both subpops.  Next SLiM model: read step1.trees, set one subpop to size 0 (removing it), run a bit, save as step2.trees.  Next SLiM model: read step2.trees.  The removed subpop will be size zero in the .trees file, but will have metadata, because the metadata (I think?) got carried over from the population table read in from step1.trees.  So you'll get this error.

Assuming that scenario does trigger this error message (I'm 99% sure it would), the bug could be in one of two places.  (1) We ought to allow a WF subpop of size zero to have metadata, and just ignore it since it must be removed/nonexistent, or (2) When we write out step2.trees in the above scenario, we should _not_ carry over the metadata for the removed subpop from the old population table, but should instead replace it with `"null"`.  I am OK with either of these policies, I think, but (1) seems maybe better; there's no need to throw away metadata information.

So I think I will fix it following (1), but if you disagree than let's talk about it.  :->

**Comment by bhaller** [comment]
I figured out what changed.  In 3.7.1, `__TabulateSubpopulationsFromTreeSequence()` sets up to create a SLiM subpop based on the individuals it finds in the tree sequence; it doesn't look at the population table at all, in fact, unless individuals are found, so it doesn't matter that metadata is there.

Since then, I have added a new method, `__PrepareSubpopulationsFromTables()`, that gets called before `__TabulateSubpopulationsFromTreeSequence()` and does some pre-planning based upon the contents of the population table.  This was to fix #313, where you had a pathological case involving a tree sequence with individuals that belonged to a non-existent subpopulation.  To fix that, we have to actually look at the population table and figure out which subpops exist, so that we can flag any individuals that belong to a non-existent subpop, and that is what `__PrepareSubpopulationsFromTables()` does.

So.  According to approach (1) above, the fix is to take the results of `__PrepareSubpopulationsFromTables()` as indicating what subpopulations _could_ exist, potentially; any individual marked as belonging to some other subpop still gets flagged.  But if no individuals actually _do_ exist for a given subpop, then that's OK; we just don't create it, figuring that it must be ancestral.

BUT!  I am now realizing that I think (2) is actually the correct fix.  The reason is because of nonWF models.  For nonWF models, you are allowed to (a) remove them entirely, or (b) have them contain zero individuals but still exist.  Those are both legal, and distinct, states.  It seems to me that our policy is that metadata of `"null"` indicates that the subpop no longer exists (i.e., was removed entirely), whereas non-null metadata indicates that the subpop is just empty but still exists.  And if that's our policy, then we probably ought (for simplicity) to draw the same distinction for WF models – except that they aren't _allowed_ to be empty, so then the "has metadata but contains no individuals" state is illegal.

So, I think that (a) the error you're getting here is correct (although the error message could stand to be improved – it should say something about WF models not being allowed to have zero-size subpops), and (b) when writing out the population table, we need to convert SLiM metadata into `"null"` for subpops that no longer exist, to preserve the policy in the scenario I outlined above.  So those are two two things that actually need to be fixed because of this issue.

I'm going to wait for feedback from you now, since this is complicated and I'm not sure.  If we do end up in agreement about these policies, I'll fix the two things mentioned in the previous paragraph, and perhaps you could add the policy decisions to that document you have written somewhere?  :->

**Comment by petrelharp** [comment]
> Out of curiosity, why are there only individuals in p1? The code gives initial_size=10 for both; shouldn't they both have 10 extant individuals, one with an ancestral history added, one without? This is presumably just my lack of comprehension of msprime APIs. :->

This is because of this line:
```
        samples={"B" : 5},
```
where we say that we would like there to be 5 sampled genomes from population B (and none from A).

**Comment by bhaller** [comment]
> > Out of curiosity, why are there only individuals in p1? The code gives initial_size=10 for both; shouldn't they both have 10 extant individuals, one with an ancestral history added, one without? This is presumably just my lack of comprehension of msprime APIs. :->
> 
> This is because of this line:
> 
> ```
>         samples={"B" : 5},
> ```
> 
> where we say that we would like there to be 5 sampled genomes from population B (and none from A).

Huh.  So the `initial_size=10` is just ignored/unused?  That seems weird to me, but mine not to reason why... :->

**Comment by petrelharp** [comment]
I agree with everything you wrote above, otherwise! But we ought to just talk through the policy, first.

**Comment by bhaller** [comment]
> > Huh. So the initial_size=10 is just ignored/unused? That seems weird to me, but mine not to reason why... :->
> 
> It's not - suppose you want to get 5 diploid samples from one of two populations that exchange migrants. The `initial_size` is the size of the populations, which is different than the number of samples you draw from them.

I'm not sure where my point of confusion lies, but anyway this is orthogonal to the issue at hand.  :->  I guess I've just never used these msprime APIs and don't really understand what they're doing.  :->

**Comment by bhaller** [comment]
Fixed in `multispecies`, following approach (2) as per our discussion on zoom.  Closing.
