### ISSUE TITLE
add tests of population remapping

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#319]
Add tests (perhaps to the `treerec/tests` section) that check whether:
- alive nodes with population not having SLim metadata produces an error
- reading of multiple tree sequences whose populations conflict produces an error
- reading of multiple tree sequences whose populations are remapped to not conflict works
- existing non-SLiM metadata in population table entries not referred to by alive nodes is not modified (including at the end of the table, past all slim populations)
- saving out of a tree sequence with an empty pop in nonWF still writes out the empty pop, and reloading it recovers that pop

**Comment by bhaller** [comment]
Should also test that when remapping is used, carryover metadata gets shifted to the new remapped index unmodified, without errors.  This does not work at present; I need a test case to get it working confidently.  Also: test that a remapping that leads to a conflict between the remapped subpops correctly errors out.  Also: test that when carryover metadata is present, SLiM correctly requires a remapping entry for that subpop index (if any remapping is being done at all).  Lots of corner cases that should get exercised.  :->

**Comment by petrelharp** [comment]
I've got a test in pyslim for doing remapping in which there is also non-SLiM metadata to carry over, however this is [not yet working](https://github.com/MesserLab/SLiM/blob/c7238f84c0b5460b1806eb6e3d412009fafc4897/core/species.cpp#L6715). In fact I'm not quite sure how this should work. Proposal: suppose that `subpopMap` has some `pk: j` pairs. Then in the resulting popultaion table (ie after remapping),
1. row `k` should be a SLiM population and have previous-population `j`'s metadata, with id `j`
2. row `j` should be empty (null metadata)

And,

3. any other rows in the table not referenced above should be unchanged.

**Comment by petrelharp** [comment]
> a remapping that leads to a conflict between the remapped subpops correctly errors out

What did you have in mind here?

**Comment by bhaller** [comment]
> I've got a test in pyslim for doing remapping in which there is also non-SLiM metadata to carry over, however this is [not yet working](https://github.com/MesserLab/SLiM/blob/c7238f84c0b5460b1806eb6e3d412009fafc4897/core/species.cpp#L6715).

Ah, yes.  Gotta love when a "FIXME" comment comes back to haunt you.  :->

> In fact I'm not quite sure how this should work. From the docs and above it looks like you're wanting the remapping to cover every input population, including the non-SLiM ones.

Yes, for clarity and to make what is happening fully explicit.

> This makes sense, but the semantics seem a bit funny, because suppose that population 2 is non-SLiM, you'll have to put in something like `"p2": 2`, even though this population will _not_ become `p2` in SLiM. It would be less odd if the keys in `subpopMap` were just plain integers instead of `pX`.

Perhaps true (although then the semantics for the regular SLiM subpop remapping case would become less clear, and that's the common case).  In any event, that isn't possible at present, since `Dictionary` requires that its keys be type `string`.

> Or you could have `subpopMap` be just a list of integers of length equal to the number of input populations, with the `j`th value being the new index of the `j`th population.

Yes, possibly.  If you want to use a very large subpop id, like `p10000000`, that would be a bit annoying, but I guess it would be basically fine.

> > a remapping that leads to a conflict between the remapped subpops correctly errors out
> What did you have in mind here?

Like, mapping 0 and 5 both to "p3", I guess?  But of course that can't even be represented by the dictionary since it can have only one value for the key "p3", so I guess that's a non-issue?  Although the opposite problem, of a dictionary that maps 5 to "p3" and also maps 5 to "p2", is representable with the dictionary, and ought to error out.  And if we went with your "list of integers" proposal above, then mapping 0 and 5 both to "p3" would indeed be an error case that would need to be checked.

OK, so.  I'm not sure what the right fix is here, and I have to confess that I am a bit tired of the endless fallout from this "remapping" feature, and I'm really questioning whether it belongs in SLiM at all.  It's a very weird thing to do, to try to munge the entire tree sequence so that it loads with different population indices than the ones represented in the file on disk.  The code to do it is quite complicated and fragile, and is hard to get right and hard to test on the SLiM side since it depends upon particular input `.trees` files to test meaningfully (and as you know, none of my SLiM unit tests do that, the tests that do that are all in your domain).  It seems like it would be much more natural to have this be a feature in `pyslim` that would remap one subpop from index `x` to index `y`, updating the other tables and metadata as needed to preserve consistency.  People who want to do a remapping would do it on the Python side before loading into SLiM (which, for the user, seems easier and more natural than doing it later with a remapping table at load time in SLiM).  To me that makes much more sense – and not just because I don't relish trying to figure out what the right behavior is for this issue here, and then re-implementing the remapping stuff yet again.  I think this has been a pain in the ass because we're trying to pound a square peg into a round hole.  I would like to rip out this remapping feature.  What do you think?

**Comment by petrelharp** [comment]
Right now I'm feeling like it's Fine the Way It Is - it's a bit unsettling, but just making the documentation a bit more explicit would fix that up. (I had the feeling of "wait is this how it's supposed to work", but a few sentences in the documentation would have cleared that up.) I'm sympathetic to wanting to rip it out, but I don't think that's the way to go because, as we've discussed, we do need to provide the functionality somehow, and writing the code in python would be just as fiddly, and it'd require people to use python who might not have had to otherwise.

But, about the semantics (and, relevant whether we do it in SLiM or in pyslim) - how's this for a proposal:

> `subpopMap` is provided to re-order the populations of the input tree sequence on loading in to SLiM.
> The keys of this dictionary should be SLiM population identifiers (e.g., `p2`) and the values should be indexes
> of populations in the input tree sequence, so that `"p2", 4` would mean that the fourth population in the input
> will become `p2` on loading into SLiM. All populations in the tree sequence must be explicitly mapped,
> even if their index will not change and even if they will not be used by SLiM. For instance, suppose we have a tree sequence
>  in which population 0 is unused, population 1 is not a SLiM population (e.g., an ancestral population produced
> by msrpime), and population 2 is a SLiM population, and we want to load this in with population 2 as `p0` in SLiM.
> Then, we could use `subpopMap = Dictionary("p0", 2, "p1", 1, "p2", 0)`. Although this cannot be used to remove
> populations in the tree sequence, note that it may add populations when `treeSeqOutput( )` is used (although these will
> not be SLiM populations) - if in this example we had used `Dictionary("p0", 0, "p1", 1, "p5", 2)` and then written the result
> out with `treeSeqOutput( )`, the resulting tree sequence would have six populations, although three of them would be empty
> and would not be used by SLiM.

Hm - writing this, I think it would be cleaner to allow totally empty populations to not be remapped? But require any rows with metadata to be remapped? I could draft the docstring if you like.

I do think that the "vector of indexes" might be easier to deal with than the "Dictionary" method, though (in the code as well!).

**Comment by bhaller** [comment]
> Right now I'm feeling like it's Fine the Way It Is - it's a bit unsettling, but just making the documentation a bit more explicit would fix that up...

Hmm, ok.

> But, about the semantics (and, relevant whether we do it in SLiM or in pyslim) - how's this for a proposal:

OK, LGTM.

> Hm - writing this, I think it would be cleaner to allow totally empty populations to not be remapped? But require any rows with metadata to be remapped?

Well, "empty" and "unused" are two different things, right?  An index in the population table might be "empty" in the sense of not having any metadata, but still be used in the tree sequence, right?  And at the point when the remapping happens, the code does not yet know whether a subpop is used or not, so distinguishing between those cases would make things even more complex than they already are (which is pretty freaking complex).  So I think I vote against this.  Every entry in the pop table should be explicitly remapped, just to keep things simple and clear.

> I could draft the docstring if you like.

Yes, please.  But the docstring you provided in your previous post is usable as is, right?  Since (I think) I don't want to adopt the modified policy you proposed?

> I do think that the "vector of indexes" might be easier to deal with than the "Dictionary" method, though (in the code as well!).

I don't think I'm a fan of it.  I like the way the dictionary says explicitly "number three will become symbol p1"; that makes the direction of the mapping very clear.  Yes, for the carryover case it doesn't actually become symbol p1; but that's a rare edge case, and anyway it isn't really that confusing (it just means "number three will go into the slot that SLiM would use for p1", and the symbol "p1" should end up reserved in that case so people can't make a new p1 in SLiM, so it really _did_ become p1 in that sense – it's just not a SLiM subpop).  Providing clarity in the main case should be the thrust of the API.  If it was just a vector of indexes, there would always be confusion about "wait, is 3 getting mapped to 1, or is 1 getting mapped to 3?".  I know I, at least, would have to look that up every time I used the API.

**Comment by petrelharp** [comment]
> Well, "empty" and "unused" are two different things, right? An index in the population table might be "empty" in the sense of not having any metadata, but still be used in the tree sequence, right?

Oh, hah, right, good point. Yes, never mind.



>   >  I could draft the docstring if you like.
> 
> Yes, please. But the docstring you provided in your previous post is usable as is, right? Since (I think) I don't want to adopt the modified policy you proposed?

I meant the docstring for a different semantics where no-metadata pops needn't be remapped, which you point out is a Bad Idea.

> > Dictionary
> I don't think I'm a fan of it. 

Fine, just an idea.

**Comment by bhaller** [comment]
OK, great.  I'll use the docstring you wrote earlier.  So, apart from clarifying the doc in that way, I guess the current behavior is agreed to be correct, _except_ that the carryover case with remapping is not working (because it is not implemented at all), right?  A test case I can use to validate my fix for that would be helpful, as you offered on Slack, yes, thanks!

**Comment by bhaller** [comment]
OK, I believe I have just committed a fix for (a) carryover population metadata, and (b) remapping migration records (but not the migration table, which we ignore).  It now loads your test tree sequence file without errors, and makes two SLiM subpopulations with migration between them.  I also fixed the doc for `readFromPopulationFile()` along the lines of your proposal.

One note: your `.slim` file has a comment that says "Nothing should have changed", but the saved tree sequence will not be the same as the loaded tree sequence – the subpop ids will be remapped.  I imagine you already realize that, and the comment is just stale.  :->

Anyhow, as far as I know this is now off my plate.  Let me know if you run into further issues.  Thanks for your help!

**Comment by petrelharp** [comment]
There is one remaining issue - it's currently not dealing with cases where population is `-1` (ie `TSK_NULL`). I think it's legal for `source` and `dest` to be NULL in a migration table, and by default when we use msprime to make SLiM mutations we get a `subpopulation = -1` in the metadata. I think the -1's should be mapped to -1.

**Comment by bhaller** [comment]
I'm not sure I understand.  We're remapping row indices.  What does it mean for something to be remapped to -1?  I can't put the row for a subpop at index -1.

**Comment by bhaller** [comment]
And do we need to allow -1 to be remapped to something other than -1?

**Comment by bhaller** [comment]
OK, I understand now, thanks.  I believe I have just committed a fix for the `TSK_NULL` case, but it is completely untested.  Let me know if you see further issues.

**Comment by petrelharp** [comment]
I see that if population `X` is remapped to `Y` then you're remapping a non-SLiM population name like `pop_X` (good), but it's being [remapped to `pY`](https://github.com/MesserLab/SLiM/blob/ac12bf6020a7217f0c1010d80d94b9011b9e765a/core/species.cpp#L6829); I would have thought it would go to `pop_Y`, and this would be an easy change? (I also see from the note that you're *not* remapping `pX` to `pY` - why not? It seems like you should since otherwise they will easily conflict with SLiM population names.)

**Comment by petrelharp** [comment]
Never mind - I think what you did there is fine.

**Comment by bhaller** [comment]
> Never mind - I think what you did there is fine.

OK.  Happy to discuss if there is a problem, but it seemed like the right policy to me, dunno.  :->

**Comment by bhaller** [comment]
Hi @petrelharp.  Is this issue finished, or are there more things you still want to do?

**Comment by bhaller** [comment]
@petrelharp ping

**Comment by petrelharp** [comment]
Closed in https://github.com/tskit-dev/pyslim/pull/273
