### ISSUE TITLE
readFromPopulationFile supopulation remapping collision

### ISSUE THREAD

**Issue by bobweek** [MesserLab/SLiM#321]
after rebuilding slim and applying the `subpopMap` function, im still getting a `pop_0 is already in use` error. attached is a mwe.

[mwe.slim.txt](https://github.com/MesserLab/SLiM/files/8757743/mwe.slim.txt)
[mpsrime-burnin.py.txt](https://github.com/MesserLab/SLiM/files/8757744/mpsrime-burnin.py.txt)

**Comment by bhaller** [comment]
Worked fine for me with the current `multispecies` branch, except for this warning:

`#WARNING (Species::ReadTreeSequenceMetadata): the model type of the .trees file (nonWF) does not match the current model type.`

This is because you're calling `pyslim.annotate_defaults()` with `model_type="nonWF"` but then loading into a WF model.  Not a good idea, but I think the error you are seeing is unrelated to that.  My first suspicion is that either you're not running the current `multispecies` branch (maybe you did build it, but you're still actually running an older build?) or you're running a non-standard version of `pyslim` that is annotating in some different way.  Why don't you post the `.trees` files that your `.py` script produced here, and I'll try loading those?

**Comment by bobweek** [comment]
your first suspicion is correct! i forgot to `sudo cp SLiMgui /usr/bin/SLiMgui`. my apologies! it's working now :)

**Comment by bhaller** [comment]
OK, great.  Closing!  :->
