### ISSUE TITLE
Scripts report errors only for certain seeds?

### ISSUE THREAD

**Issue by bioXiaoheng** [MesserLab/SLiM#34]
Hi!

I'm simulating replicates using the attached eidos script with the command 
`slim -d var_age=${y} -d var_s=1 -d var_h=1.33 -t Slim3_50kb_HCG_BalSel-trackBoth.txt`
and has recorded the seeds for each replicate after its completion. Two replicates errored out halfway (and produced incomplete outputs) with the error message

```
ERROR (EidosSymbolTable::_GetValue): undefined identifier p3. 
Error on script line 66, character 4:
    p3.outputMSSample(50);
    ^^
```

I traced back to the seeds for these two runs and was able to replicate the error message with the command
`
slim -d var_age=4501 -d var_s=1 -d var_h=1.33 -s 3515352887805 -t Slim3_50kb_HCG_BalSel-trackBoth.txt > temp.out`
and
`
 slim -d var_age=2501 -d var_s=1 -d var_h=1.33 -s 1990705088010 -t Slim3_50kb_HCG_BalSel-trackBoth.txt > temp.out 
`

Meanwhile, if the seed wasn't specified in these commands, or another seed was specified, the run would be (mostly, given these two exceptions) smooth. I haven't tested the commands in another platform yet, though.

I know I can resolve this issue by using other seeds, but it just made me curious why this is happening.

[Slim3_50kb_HCG_BalSel-trackBoth.txt](https://github.com/MesserLab/SLiM/files/2928640/Slim3_50kb_HCG_BalSel-trackBoth.txt)

**Comment by bhaller** [comment]
Hi!  I looked into the first of the two runs that you specified values for.  It looks like that run just happens to call readFromPopulationFile() in exactly generation 8500, because the mutation it is tracking happens to become fixed in generation 8500.  That readFromPopulationFile() call loads in a population state that does not have p3 defined; the 8500 late() callback is then executed, and fails because p3 is no longer defined.  I would suggest that you read section 22.8 for details on how event scheduling occurs in SLiM; if the generation counter is changed in the middle of a late() event in generation 8500, the rest of the scheduled late() events for generation 8500 will still run, according to SLiM's design.  You might wish to make that 8500 late() event run in generation 8501 instead, so that you can be sure that this scheduling hiccup does not occur.  In any case, that appears to be the source of the problem; what the right solution might be, for your model, is of course a matter of precisely what you're trying to do.  :->  I hope this helps!

Cheers,
-B.

Benjamin C. Haller
Messer Lab
Cornell University
