### ISSUE TITLE
Add parent age information to Individual

### ISSUE THREAD

**Issue by bhaller** [MesserLab/SLiM#350]
As discussed in https://github.com/tskit-dev/pyslim/issues/284, it might make life much easier if SLiM kept track of the ages of the parents of individuals, to make it easy for users to calculate the generation time for nonWF models.  The pyslim doc has an example of this at https://tskit.dev/pyslim/docs/latest/time_units.html that puts it in `tagF`; models that want to use `tagF` for other purposes would have to use `setValue()`, which gets annoying, and this is a very standard thing to need to do, so it should be supported better.

Keeping only the mean of the ages of the parents seems right, because it means that there's no weirdness with cloned/selfed individuals; the `meanParentAge` property on Individual (is that a good property name?) would always be a singleton float, so you could average across a bunch of individuals, some cloned/selfed and some not, without having to worry about those details.  It also keeps memory usage down a bit.

I'm not sure whether SLiM should also automatically compute the mean parent age for each generation, and keep those values around in a property on Species, parallel to the way the pyslim doc's recipe does `GENTIME[community.tick - 1] = mean(p1.individuals.tagF);`.  I lean towards no.  It's easy enough for the user to use LogFile to log this out or whatever, and some models might want to track it separately for each subpop, or separately for separate sexes, or who knows what; probably SLiM should not insert itself into that.  Just keeping the mean parent age already makes life substantially simpler.  But I'm open to debate on that.

It makes sense for the example of how to do this to be in the pyslim docs, I think; but the SLiM docs should mention it as an issue to think about, and link to the pyslim docs.

Anything else to think about with this?  @petrelharp you wrote before that "We should do some testing though first, to double check that we're measuring generation time appropriately."  What testing do you have in mind, and can you perhaps do it now, to confirm we're barking up the right tree?

**Comment by petrelharp** [comment]
Let's see: for testing, we'd
1. simulate under various nonWF models where fecundity depends on age with lots of neutral mutations *in SLiM*
2. compute mean generation time
3. check if mean sequence divergence equals mean coalescence time multiplied by mutations per unit time, i.e., compare
```
ts.diversity(mode='site')
``` 
to
```
ts.diversity(mode='branch') * slim_mut_rate * mean_gen_time
```
where `slim_mut_rate` is the mutation rate per generation in SLiM and `mean_gen_time` is the generation time as computed following the recipe in pyslim's docs.

**Comment by petrelharp** [comment]
I agree this *would* make things easier; if you are not worried about the additional memory & time footprint then I say go for it.

**Comment by petrelharp** [comment]
Brainstorming: one way to make it optional would be to make it a flag to `initializeTreeSeq( )`, say `recordGenerationTime`, that will save an estimate in the final tree sequence's metadata somehow; and the per-individual property is only available if this is turned on. I'm suggesting this because the only common use case I can think of where poeple would want to know this is for post-hoc transformations on the tree sequence. But this is probably over-complicating things.

**Comment by bhaller** [comment]
OK, there's a PR now.  I chose to make keeping mean parent ages be always-on, for now; I'll do some speed tests but I don't expect to see this show up as significant, since it's very minimal bookkeeping and it's per-individual, per-generation; that's not a heavy bottleneck in general.  Trying to actually calculate and record the generation time strikes me as overkill, since (as I wrote above) people may want to do that in different ways, subdivided by subpop/sex/whatever, etc.

**Comment by silastittes** [comment]
This issue came up in a discussion on slack and I offered to help. I imagine some changes will be needed, but wanted to share what I came up with for further suggestions.
I modified the pyslim example recipe for recording generations times and ran 100 simulations varying recombination and mutation rates. The main change to the recipe is using `getValue`/`setValue` to track mean parent ages. I confirmed the changes I made to the pyslim example generated the same mean generation time values. 
Following @petrelharp's suggestion above, this plot shows the relationship between `ts.diversity(mode='branch') * slim_mut_rate / mean_gen_time` and `ts.diversity(mode='site’)`, on the x and y axes, respectively. 

![image](https://user-images.githubusercontent.com/5741919/189762731-7efc064f-6cc1-4483-b260-d6c8c8e56c0f.png)

There’s definitely a clear relationship between them, but they’re off by some constant factor. I'm not sure why. Smells like a factor of 2 error maybe?
Mutations were generated in SLiM rather than added with msprime after. 

Here's the relevant files and code
[Snakefile.txt](https://github.com/MesserLab/SLiM/files/9551956/Snakefile.txt)
[gentime.slim.txt](https://github.com/MesserLab/SLiM/files/9551957/gentime.slim.txt)

Finals steps and plotting were done in a jupyter notebook cell, so I'll share here for simplicity:
```
import pyslim
import tskit
import msprime
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

def compare_gentime(ts):
    ts = tskit.load(ts)
    meta = ts.metadata['SLiM']['user_metadata']
    r = meta['recombination_rate'][0]
    mu = meta['mutation_rate'][0]
    K = meta['K'][0]
    gen_times = np.mean(meta['generation_times'])
    rts = pyslim.recapitate(ts,
                recombination_rate=r,
                ancestral_Ne=K, random_seed=5)         
    ts_divergence = rts.diversity(mode = 'site')
    slim_divergence = rts.diversity(mode='branch') * mu / gen_times

    return pd.DataFrame({
        "recombination_rate": [r],
        "mutation_rate": [mu],
        "K":[K],
        "ts_divergence" : [ts_divergence], 
        "slim_divergence": [slim_divergence]
    })


ts_list = ! ls sim_out/*
sim_df = pd.concat([compare_gentime(ts) for ts in ts_list])

plt.scatter(sim_df["slim_divergence"], sim_df["ts_divergence"])
mnn = np.min((sim_df['ts_divergence'], sim_df['slim_divergence']))
mxx = np.max((sim_df['ts_divergence'], sim_df['slim_divergence']))
plt.plot(
    [mnn, mxx], [mnn, mxx],
    color='black', linestyle='--', linewidth=2
)
plt.xscale('log')
plt.yscale('log')
plt.xlabel('SLiM divergence')
plt.xlabel('tskit divergence')
plt.show()
sim_df[0:5]
```

Hope this proves useful!

**Comment by bhaller** [comment]
Convenient that I forgot to close this issue, since it provides a venue for discussion.  :->

This looks great, thanks @silastittes!  I don't know enough popgen to have any idea regarding the discrepancy in the plot.  Looks like about a factor of 10, actually, not just 2x.  @petrelharp, is there a problem here, or were you looking just for a good correlation (clearly present), not for equality?

**Comment by silastittes** [comment]
"An error by any other factor would smell as suspicious" ;)

**Comment by petrelharp** [comment]
Something's wrong here. One possibility is that you're taking the mean of the whole trajectory, not just the most recent bit of time. Since "generation time" artifically starts out at zero and we have to wait for things to equilibrate, that might be affecting it. Instead, how about:
```
    gen_times = np.mean(meta['generation_times'][50:])
```

**Comment by petrelharp** [comment]
Ah, also - you should not recapitate. We want to compare SLiM-produced mutations to the trees; adding in a recapitated portion messes things up (ie adds some bits of the trees without SLiM-produced mutations).

**Comment by bhaller** [comment]
@silastittes it would be great if you could take another swing at this ASAP.  I'm hoping to release SLiM 4.0.1 in a day or three, and I'd like to know that this new feature is correct/useful.  Thanks!

**Comment by silastittes** [comment]
@petrelharp nailed it!

**Comment by silastittes** [comment]
Foe the curious. Adding recapitation (doh!) was the biggest issue, but the change `gen_times = np.mean(meta['generation_times'][50:])` noticeably shifted things a small amount too.

**Comment by bhaller** [comment]
Awesome!  Hard to imagine a better correlation, that must be a R^2 of 0.999.  :->  Looks like this is all good; closing.  @petrelharp I guess it would be good for the pyslim docs to get updated to use this facility; I imagine you're already on that.  :->  Thanks!

**Comment by bhaller** [comment]
And thank you for doing this, Silas!  :->

**Comment by silastittes** [comment]
No problem, I was happy to do it! I'll chat with Peter, but we do have plans to update pyslim docs.
