### ISSUE TITLE
add `localPopulationDensityAtPoint` method

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#362]
Use cases: say we want to make a map of local density, and then use this for visualization or for looking up local density of individuals more quickly.

**Comment by bhaller** [comment]
"say we want to make a map of local density" this is what the `summarizeIndividuals()` function is for, no?  What's the advantage of the hypothetical `localPopulationDensityAtPoint()` method?

**Comment by petrelharp** [comment]
Hah, yes, sorry, I'm being hasty here. I suppose that a `localPopulationDensityAtPoint( )` could provide a smoothed version of that, but the advantages are not obvious.

So - it's a very natural thing for someone to want to do, *but* I'll have to think more about a compelling use case.

**Comment by bhaller** [comment]
And, ah: the reason there isn't already `localPopulationDensityAtPoint()` is that it depends on the interaction _strength_, which is not defined for the "at point" type of methods.  So I'm not sure `localPopulationDensityAtPoint()` makes sense.  If you can suggest a definition for it that does make sense, then I'll consider it; but really I think this is what `summarizeIndividuals()` is designed to do for you.

To be clear: the reason that the "at point" methods don't involve interaction strengths is because interactions strengths are always individual-individual, and the reason _that_ is true is because `interaction()` callbacks need two focal individuals.  Really an "interaction" is just conceptually between two individuals.  I could make `localPopulationDensityAtPoint()` error out if any `interaction()` callbacks are defined, to fudge this, but that would be a weird inconsistency and I'd strongly prefer not to.

**Comment by bhaller** [comment]
@petrelharp Is this still something that you think would be useful?  As you wrote above, "I'll have to think more about a compelling use case".  Since there are substantial architectural (even paradigmatic!) issues to doing it – as I wrote above, `localPopulationDensityAtPoint()` depends on interaction strength, which is defined as being between two individuals because `interaction()` callbacks need two focal individuals – this is a change that I really don't want to do.  I think it would uglify the whole interaction architecture, and would probably uglify the underlying code as well.  So, pending a compelling use case I think I'm going to close this.  Of course reopen and debate if you disagree – especially if you can think of a use case that is sufficiently compelling.  :->
