### ISSUE TITLE
"end of simulation" tick specification

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#371]
Often there are things we want to do at the end of the simulation. I find myself wanting to (a) specify the total simulation runtime via command-line arguments (e.g., `-d RUNTIME=10000`); and then doing `rescheduleScriptBlock(..., ticks=RUNTIME)` to make it so the script block with `simulationFinished()` runs in tick `RUNTIME`. This is all fine. And, I then start adding other things I want to happen at the end, e.g., write out summary files. It's nice to keep these modular, so then I start rescheduling *those* script blocks also. But, it occurs to me that it'd be nice to be able to do like
```
end late() {
   // stuff
}
```
to mean "run this in a tick if SLiM thinks that tick is going to be the last one". There's some complexities here; like for instance if you have an `end early()` block but `simulationFinished()` gets called in `late()` then the block won't be run; but I think that's okay?

Certainly not essential, but would tidy up some code.

**Comment by bhaller** [comment]
The problem is that the end of simulation is not well-defined right up until the moment it happens.  You could do something like this:

```
end late() {
   // this executes at the start of 1000
}

1000 late() {
   // this executes next in 1000
   community.rescheduleScriptBlock(s1, 2000);
}

s1 1000 late() {
   // this doesn't execute until 2000
}
```

If you want to keep your end-of run cleanup modular (certainly a good goal), how about defining user-defined functions for those chunks of work, and calling them where you call `simulationFinished()`?

**Comment by bhaller** [comment]
The hope is that someday it will be possible to do:

```
RUNTIME late() {
   // runs in the tick defined by constant RUNTIME
}
```

I'm not _so_ far away from being able to do that, now that it is no longer possible to undefine/redefine constants.  As long as RUNTIME is defined by the end of the initialize() block, SLiM could then schedule it for tick RUNTIME without any problems.  But I'm still pondering exactly how I want to approach it, because I'd also like it to be possible to do, e.g.:

```
(10N + 2) late() {
   ...
}
```

So it's a little tricky and I just haven't had time to get into it, since I'm working full-bore on parallelization these days.

**Comment by petrelharp** [comment]
Sounds good; I started to suspect there were problems with the proposal. =)
