### ISSUE TITLE
Smoothing of spatial maps

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#380]
We would like a method to do a (probably Gaussian) kernel smoothing of a `spatialMap`.

Use cases:

1. "available resources" - suppose we have a map of "habitat"; for concreteness suppose that the value of the map is "how much food is there here". Now suppose an individual whose location is at `x` spends time at nearby locations proportional to a Gaussian kernel centered at `x`; and so the Gaussian-smoothed map evaluated at `x` tells us how much food they encounter.
2. "nearby habitat" - now suppose instead that the indivduals' birth rate depends on "number of neighbors divided by amount of food"; to compute this we need to divide `localPopulationDensity` by this (as computed in (1)).
3. Compute "interaction density at a point" : some interpretations of "interactions" require an actual interaction with another individual; however, some don't. For instance, suppose that as above an individual at `x` spends time around `x` proportional to a Gaussian kernel; then we might ask "how much total time do individuals spend at `y`, where `y` is not necessarily the location of an individual.

What do I mean by "smoothed image" (or map)? If the grid points corresponding to the centers of the map cells are `x_i` , the value in cell `i` is `m_i`, and the smoothing kernel is `f( )` then the smoothed value at `y` is `\sum_i f(y-x_i) m_i` (perhaps `y` is a cell center, perhaps not). (Note that we might wonder if this method should apply to an `Image` or a `spatialMap`; however, we see that since the kernel depends on distance, for interpretabiliy, it needs to operate on `spatialMap`.)

There are a few related things we might want:

**a.** Given an Map, produce a new, smoothed image (of the same dimensions?).
**b.** Given a Map, return the smoothed value at an arbitrary location.
**c.** Given a bunch of individuals, return the Image/Map that to each cell `i` gives the local density at its center `y_i`, computed as `sum_j f(y_i - x_j)`, where the sum is over the individuals, and the location of the j-th individual is `x_j`. Note that `summarizeIndividuals` does this but with a rectangular kernel.

These operations are (a) map -> map; (b) map(point) -> value; (c) individuals -> map. 

So how do we do the use cases with these? Use case (1) is (c); however, to approximate it we could first use `summarizeIndividuals` to produce a map, then do (a) to that map. Similarly, use case (3) is basically (c) except at an arbitrary point; we might approximate it by producing a map with `summarizeIndividuals` and then returning an interpolated value for that map at the arbitrary point.  This approximation will be good if the cells of the map are smaller than the width of the kernel used.

This is an important point; let's think through it in a bit more detail. Suppose our goal is to get local population density through the map intermediate instead of using `localPopulationDensity` (which is pairwise). To do this we can (i) do `summarizeIndividuals`; (ii) smooth it with the desired interaction kernel; and (iii) return the interpolated map value at the locations of the individuals. How good an approximation is this? Well, (i) and (ii) is equivalent to moving every individual to the center of their grid cell, and then computing density at each other grid cell. Then there's the additional approximation induced by the interpolation. These two approximations will be good if the kernel we smooth by is wider than the distance between grid cells (concretely, accuracy would be similar to but a bit better than how well we could compute the integral under the kernel by discretizing in grid cells).
 
How would we do (b)? Two options:

**i.** implement a "Gaussian" interpolation option (in addition to the existing "linear" one).
**ii.** produce a smoothed map with (a) and then use existing evaluation (eg with linear interpolation).

However, note that to  have sensible answers through discretization, we'd need a bunch of grid cells within the width of each Gaussian kernel, making (i) a somewhat expensive operation, i.e., one we wouldn't want to do for everyone in the population. This suggests that (ii) is in fact the way to go. 

So, I think I'm proposing one, maybe two, things:

- `smoothSpatialMap(map, functionType, ...)`, which takes a map and information specifying a kernel in the same format as provided to `setInteractionFunction` and produces another map. I'm not sure *how* it produces the new map - perhaps it modifies the map in place? Or returns an Image that one can use to make a new map?
- add the ability to do *weighted* sums in `summarizeIndividuals`, by passing in kernel information.

So, I think that this issue is about `smoothSpatialMap`; that lets us do everything reasonably; the proposed extension to summarizeIndividuals is less crucial.

ps. Note that a more sophisticated way of doing some of this is through the 'reproducing kernel Hilbert space' technology; this might give us better approximations for the same computational power but not better scaling with number of individuals.

**Comment by bhaller** [comment]
I guess modifying in place is best?  People wouldn't have any use for the Image except to make a new spatial map out of it; and whatever data was used to generate the original spatial map could be used to generate a second spatial map with the same data, so there's no difficulty there; and often people wouldn't want the intermediate map at all, only the final (blurred) map.

Two questions.  (1) What happens at the edges of the spatial map?  If periodic boundaries are in effect then that's easy – you wrap around.  If they're not, then you sum up values over the area that is within-bounds, and divide by the total area within-bounds, I guess?  (2) Given a spatial map and kernel parameters in the same format as provided to setInteractionFunction(), what's the math to get the matrix of values that I convolve with the spatial map?  I know how to do the convolution given the matrix, but I don't know how to generate the matrix itself.

**Comment by bhaller** [comment]
I guess the matrix used for the convolution would always be a (2n+1)x(2n+1) matrix, so that it has an odd width/height and is thus centered on the center of each focal pixel in the spatial map.  Half of that, (n+0.5), would be chosen so that the maxDistance specified is fully represented – the specified circular kernel with its maxDistance fits completely within the convolution matrix (not sure what that implies for n exactly, but I imagine I can figure it out).  My question is: what's the right way to compute the value of each cell of that (2n+1)x(2n+1) convolution matrix?  Just subsampling at some fairly high resolution, getting kernel values across a subsampled grid and averaging them?  Or is there a more elegant and mathy way to do it?  Initially, at least, I think we only need to support a type "n" (Gaussian) kernel, so maybe at least for that there's a good analytical solution?  Maybe the maxDistance messes that up, though – if we really want the kernel to cut off sharply at the maxDistance (do we?), subsampling is probably the only way to get the values.  Once I've got the convolution matrix, I just loop over pixels, do the convolution, put the result values into a new buffer, and copy the buffer into the map at the end of the process.  Seems quite easy, should be reasonably fast – if this is something you envision doing once per tick, it will take a negligible amount of time I think.  Thoughts?

**Comment by petrelharp** [comment]
> I guess modifying in place is best?

I agree.

>  (1) What happens at the edges of the spatial map? If periodic boundaries are in effect then that's easy – you wrap around. If they're not, then you sum up values over the area that is within-bounds, and divide by the total area within-bounds, I guess?

Yes, that's right.

**Comment by petrelharp** [comment]
As for implementation (reference: google 'gaussian convolution' although we don't just want to do Gaussian):

- For the value in the matrix, sometimes people just use the kernel function evaluated at the midpoint; better would be the integral of the kernel across the corresponding cell.
- The fast way to do this is not by using that matrix but with the fast Fourier transform; however, that would be a lot more of a pain; I say at least start here?
- For the Gaussian case you can do it by independently blurring each axis (!); if that seems a lot nicer to do then we could implement the non-Gaussian ones as averages of Gaussian ones.
- Somewhere there should be a nice technical book (or ten) on how to do this sort of thing. I haven't found it yet.

**Comment by bhaller** [comment]
Doing the convolution is easy, no need to do one axis at a time.  The only stumbling block is "better would be the integral of the kernel across the corresponding cell".  That's what I was suggesting using subsampling to approximate – i.e., using the "midpoint rule" in 2D.  For starters I will just use the midpoint value, though, and then we can work through whether subsampling is needed, and at what resolution.

**Comment by petrelharp** [comment]
Sounds good. I looked back at what I did [in R code to do this same thing](https://github.com/petrelharp/landsim/blob/master/R/discretize_kernel.R) and I just used midpoint value also. (Well, actually, I used midpoint value on a finer grid and then added them up - and this might be good to do if the requested cell resolution is sufficiently coarse.)

**Comment by bhaller** [comment]
That sounds the same as what I'm calling subsampling.  :->  I will proceed, once I've got a couple of other things off my plate.

**Comment by silastittes** [comment]
This all sounds great! Implementation is blurry to me because I haven't interacted with SLiM's source code, but I like the idea.

**Comment by petrelharp** [comment]
In the meeting today we proposed making the "individuals per unit of *habitat* thing use case very easy - like, building it into `localPopulationDensity`. So:

We'd like to compute, for an individual:
```
   (sum of interaction strength over neighbors) / (integral of interaction kernel *times habitat map value*)
```
The "times habitat map value" is the new bit; already `localPopulationDensity` does this for a map that is all =1.

To do this exactly, we'd need to actually do the integral in the denominator. But we can approximate it by computing the integral at a grid of points and interpolating. In other words, making a smoothed version of the habitat map and then looking up the value at the individual's location.

At first I wondered if we should require the user to pre-smooth the map. But, `localPopulationDensity` is a method of `Interaction`, which has exactly the kernel we want to use already, so I think not. Instead, I'd propose adding an argument like maybe:
```
  i1.localPopulationDenity(receivers, exerterSubpop=NULL, habitatDensityMap=NULL)
```
This might be tricky because you don't want to re-smooth the habitat density map every time this is called, so you have to know if the map has been changed. Alternatively, maybe there's a method on `Interaction` that registers the habitat density map, eg
```
i1.registerHabitatDensityMap(...)
// followed by
 i1.localPopulationDenity(receivers, exerterSubpop=NULL, perUnitHabitat=F)
```
That seems easier?

**Comment by bhaller** [comment]
Regarding your last comment @petrelharp, I'm unconvinced by the idea of building this into `localPopulationDensity()`.  Seems over-complicated, and APIs that try to do every aspect of a very complex operation in a single call are usually not a good idea, I think.  Much simpler to just let the user get the local population densities, get the smoothed habitat map values, and divide one by the other if that's what they want.  There will be essentially no performance difference between the two (assuming they're being done in a vectorized fashion).  Philosophically, this is like why the design of the Unix shell is good: make a bunch of simple operations like sed, awk, cat, sort, etc., and then let the user connect them together with pipes, rather than trying to build one command-line utility that somehow does _everything_.  There will probably turn out to be lots of other ways in which smoothed maps also turn out to be useful; best to just let the user use them however they want to use them.  An approach like `registerHabitatDensityMap()` just assumes way too much about what these smoothed maps are going to be used for; this is bigger than "habitat density".  Anyhow, the first step is certainly to build the smoothed-map machinery, so I'll do that first and then we can discuss the rest.  Starting on it today, I think.  (And: I looked up "reproducing kernel Hilbert space" and was amused by how few words into the article I got before my level of understanding dropped to zero.  :->)

**Comment by bhaller** [comment]
The first step in this process, I think, is making SpatialMap an independent class.  That ought to happen anyway, regardless of this issue, and once it is done, some of the questions arising in this issue may be clearer.  The steps I propose:

- make -defineSpatialMap() return an o<SpatialMap>$ object that can be used independently
- make SpatialMap know the spatial bounds that it is aligned to; all uses of a given SpatialMap must use the same spatial bounds!  If a subpop changes its bounds, it forgets all spatial maps it was using, because their bounds are incompatible; but changing spatial bounds is quite unusual, I think, and spatial maps really shouldn't carry over to new bounds since that would be a very weird change in the landscape.
- make SpatialMap know its name; it becomes an intrinsic property of the map, used primarily for SLiMgui display, and enforced to be unique across the whole simulation at any one time (implying some sort of registry of all currently in-use spatial maps, but that registry would not be user-visible)
- add a `changeValues()` method on SpatialMap that lets the user redefine the values upon which the map is based
- calling defineSpatialMap() with a name already used for a spatial map in that subpop needs to continue to work, for (temporary) backward compatibility, so it ought to (1) release the existing map by that name, at which time it will cease to exist and the name will be freed up for use by a new map, and (2) create a new map with the same name, given the new map data
- add a constructor for SpatialMap, of the same form as defineSpatialMap() but with spatial bounds supplied as well, and **deprecate** defineSpatialMap(); the SpatialMap() constructor will be the new way to create a map
- allow a given SpatialMap to be retained long-term (e.g., with defineConstant() or defineGlobal()) for easy use
- allow a given SpatialMap to be set on more than one subpopulation, with a new method setSpatialMap(); this is the new way to set a spatial map on a subpopulation, and can be used to set the same map on multiple subpopulations
- add a `spatialMaps` property of Subpopulation that returns the spatial maps attached to the subpop
- add a 'removeSpatialMap()` method to remove a given spatial map from a subpop
- add utility methods directly on SpatialMap for the things subpop already does – value(), color(), image() – and **deprecate** the Subpopulation APIs

Deprecations will be done with a warning, perhaps; or maybe I should simply break the old APIs, since this is part of the SLiM 5 release anyway, and provide a good error message to the user stating where the functionality they're looking for has moved to?  I'm torn.  Much easier/cleaner to just break with the past, and eventually I will want to break the old APIs anyway, so maybe it is better to just do it now?

Anyway, once this redesign has been done the smoothing call can be a method on `SpatialMap`, modifying the values of the existing map just like the new `changeValues()` method would.  We can then add other useful methods to the class as well, such as `subsampleMap()` to replace the map's current values with subsampled values interpolated via a chosen method (linear interpolation, etc.), with a given subsampling factor N (between every adjacent pair of grid values, add N new grid values that are interpolated).  I suspect there might be other useful things to be done as well – add/subtract maps to/from each other, etc.  We will see where this takes us.  But splitting out spatial maps into their own class is the change that enables all of this with a clean API, so I'll do it first, now.  Comments welcome of course!

**Comment by bhaller** [comment]
The main thing I'm not sure of is the `name` property.  I think I want to just let it be a user-controlled name with no requirements (such as uniqueness) from SLiM.  It is used only by the old APIs – defineSpatialMap(), spatialMapValue(), etc.  If those APIs are all removed in favor of the new APIs, the name won't be used in any APIs any more, and the user can do whatever they want with it.  That seems like an argument in favor of removing the old APIs.  I don't want to spend time defining and enforcing rules for the `name` property that are just there to make the old APIs continue to work.

**Comment by bhaller** [comment]
No need to comment on the small details of this proposal; the design is shaking out as I'm implementing it, and some things are changing a little.  I'm mostly kinda thinking out loud here, and leaving a trail of breadcrumbs.

**Comment by bhaller** [comment]
OK, the first stage of this has been done; SpatialMap is now a standalone class.  I've just published a new branch named `smooth` that has the diffs.  Could make a PR for it if anybody cares.  :->  Existing models should continue to work, but there is now a lot more flexibility to extend spatial maps with new methods and functionality.  Stay tuned.

**Comment by bhaller** [comment]
Next stage done: I've just added (to the `smooth` branch) a new method on SpatialMap called `interpolateValues()`:

`– (void)interpolateValues(integer$ factor)`
Increases the resolution of the spatial map by `factor`, changing the dimensions of the spatial map’s grid of values (while leaving its spatial bounds unchanged), by interpolating new values between the existing values.  The parameter `factor` must be an integer in [2, 100].
For a 1D spatial map, `factor-1` new values will be inserted between every pair of values in the original value grid.  A `factor` of `2` would therefore insert one new value between each pair of existing values, thereby increasing the map’s resolution by a factor of two.  Note that if the spatial map’s original grid dimension was N, the new grid dimension with a `factor` of k would be kN−1, not kN, because new values are inserted only between existing values.  For 2D and 3D spatial maps, essentially the same process is conducted along each axis of the map’s spatiality, increasing the resolution of the map by `factor` in every dimension.
Linear (or bilinear or trilinear) interpolation will be used to interpolate the values for the new grid points; this is done even if interpolation is not normally enabled for the spatial map (i.e., if the map’s `interpolate` property is `F`).

This would be more useful if there were a second parameter, `[string$ method = "linear"]`, that could be set to other interesting interpolation methods – bicubic or something, at least.  I'm not sure of the math for that, but I'll figure it out at some point, perhaps with help from @petrelharp.  For now, the point is that I now have a working proof-of-concept method that replaces the values for a spatial map with new values, calculated based upon the old values.  So all the elements needed are now in place to implemented the smoothing algorithm.  I'll probably do that this weekend so we can discuss it while you're here, @petrelharp.

**Comment by bhaller** [comment]
Next stage done: there is now a working `smoothValues()` method.  Doc for it:

`– (void)smoothValues(float$ maxDistance, string$ functionType, ...)`
Smooths (or blurs, one could say) the values of the spatial map by convolution with a kernel.  The kernel is specified with a maximum distance maxDistance (beyond which the kernel cuts off to a value of zero), a kernel type functionType that should be "f", "l", "e", "n", or "c", and additional parameters in the ellipsis that depend upon the kernel type and further specify its shape.  The kernel types and their additional parameters are exactly the same as for the setInteractionType() method of InteractionType; see the documentation of that method for details.
Distance metrics specified to this method, such as maxDistance and the additional kernel shape parameters, are measured in the distance scale of the spatial map – the same distance scale in which the spatial bounds of the map are specified.  The operation is performed upon the grid values of the spatial map; distances are internally translated into the scale of the value grid.
The density scale of the kernel is unimportant and will be normalized; for example, a kernel specified to have a maximum value of 1, versus a kernel specified to have a maximum value of 10, will produce the same effect.  This normalization prevents the kernel from increasing or decreasing the average spatial map value (apart from possible edge effects).

Remaining to do: deal with periodic boundaries, add more interpolation methods for interpolateValues().

**Comment by petrelharp** [comment]
> if the spatial map’s original grid dimension was N, the new grid dimension with a factor of k would be kN−1

I think it should be `k(N-1)+1`?

**Comment by bhaller** [comment]
> > if the spatial map’s original grid dimension was N, the new grid dimension with a factor of k would be kN−1
> 
> I think it should be `k(N-1)+1`?

Yes; I already fixed that.  :->

**Comment by bhaller** [comment]
This work is now complete, in the `smooth` branch.  The new method, final-ish doc:

`– (object<SpatialMap>$)smooth(float$ maxDistance, string$ functionType, ...)`
Smooths (or blurs, one could say) the values of the spatial map by convolution with a kernel.  The kernel is specified with a maximum distance maxDistance (beyond which the kernel cuts off to a value of zero), a kernel type functionType that should be "f", "l", "e", "n", "c", or "t", and additional parameters in the ellipsis ... that depend upon the kernel type and further specify its shape.  The target spatial map is returned, to allow easy chaining of operations.
The kernel specification is similar to that for the setInteractionType() method of InteractionType, but omits the maximum value of the kernel.  Specifically, functionType may be "f", in which case no ellipsis arguments should be supplied; "l", similarly with no ellipsis arguments; "e", in which case the ellipsis should supply a numeric$ lambda (shape) parameter for a negative exponential function; "n", in which case the ellipsis should supply a numeric$ sigma (standard deviation) parameter for a Gaussian function; "c", in which case the ellipsis should supply a numeric$ scale parameter for a Cauchy distribution function; or "t", in which case the ellipsis should supply a numeric$ degrees of freedom and a numeric$ scale parameter for a t-distribution function.  See the InteractionType class documentation for discussions of these kernel types.
Distance metrics specified to this method, such as maxDistance and the additional kernel shape parameters, are measured in the distance scale of the spatial map – the same distance scale in which the spatial bounds of the map are specified.  The operation is performed upon the grid values of the spatial map; distances are internally translated into the scale of the value grid.  Clipping at the edge of the spatial map is done; in particular, the weights of edge and corner grid values are adjusted for their partial (one-half and one-quarter) coverage.
The density scale of the kernel has no effect and will be normalized; this is the reason that smooth(), unlike InteractionType, does not require specification of the maximum value of the kernel.  This normalization prevents the kernel from increasing or decreasing the average spatial map value (apart from possible edge effects).

Closing.
