### ISSUE TITLE
suggestion for description of drawByStrength()

### ISSUE THREAD

**Issue by jiseonmin** [MesserLab/SLiM#388]
Hi, just a small suggestion for the description of drawByStrength() in SLiM manual. I think it is implied that the exerter is not a potential receiver from the last sentence "Note that if no individuals exert a non-zero interaction strength upon receiver, the vector returned will be zero- length; it is important to consider this possibility", but it maybe helpful to say it explicitly? For instance, I was curious if there any selfing in my simulation with a hermaphroditic population if a mate is chosen using drawByStrength(). (And whether I needed to add another line checking if receiver == exerter to prevent selfing.)

Thanks!

**Comment by bhaller** [comment]
Hi!  I agree that this is a possible point of confusion.  It arises for every method that involves interactions, though – not just drawByStrength(), but a bunch of others.  For that reason, it's discussed in the documentation of InteractionType itself, where the doc sets out what interactions are and how they work.  In particular, it says "Second, this distance is compared to the maximum distance for the interaction type; if it is beyond that limit, the interaction strength is always zero (and it is also always zero for the interaction of an individual with itself)."  I think it's also mentioned in the non-reference doc (i.e., the recipes) once or twice, when it comes up.  I don't think I ought to state it everywhere that the question comes up, though; it would just be too many places in the doc.  Does that seem sensible?

**Comment by bhaller** [comment]
(Maybe the mention in the InteractionType doc needs to be more visible than just a parenthetical remark?)

**Comment by petrelharp** [comment]
I think the only thing that would have avoided uncertainty in this case is a note in the docs for `drawByStrength` itself, as we were looking at the API. I agree that currently things are well-documented currently, but I think adding the word "non-self" in an appropriate place would make things easier.

**Comment by bhaller** [comment]
OK, I'll look at sprinkling "non-self" across the (many) places where it would apply.  Does seem like a useful clarification, as long as it can just be one word like that, not adding identical sentences/paragraphs in all those places.

**Comment by jiseonmin** [comment]
Thank you, Ben and Peter! And yes, I agree the current documentation is good, but a little more explicit reminder would be helpful. I searched for "drawByStrength" in SLiM Manual, and that function alone appears in so many places, so that's probably why I didn't find catch discussion in the InteractionType level.

**Comment by bhaller** [comment]
Sounds good.  Reopening this issue, since there is work I intend to do for it.  :->

**Comment by bhaller** [comment]
OK, for drawByStrength() the change I'm considering looks like this:

> Returns an `object<Individual>` vector containing up to `count` individuals drawn from `exerterSubpop`, or if that is `NULL` (the default), then from the subpopulation of `receiver`, which must be singleton in the default mode of operation (but see below).  The probability of drawing particular (non-receiver) individuals is proportional to the strength of interaction they exert upon `receiver`.  All exerters must belong to a single subpopulation (but not necessarily the same subpopulation as `receiver`).  The `evaluate()` method must have been previously called for the receiver and exerter subpopulations, and positions saved at evaluation time will be used.

So I added "(non-receiver)" in the second sentence.  That seemed better than "non-self" since it's not clear what "self" means in this context (the obvious meaning for it would be the InteractionType that is doing the work of the method).

I'm not sure that I like this change, though.  Taken literally, it doesn't say that the receiver cannot be drawn, it just doesn't say what the probability of drawing the receiver itself is.  To make it clearer, I'd have to write something like:

The probability of drawing particular individuals is proportional to the strength of interaction they exert upon `receiver` (which is zero for `receiver` itself).

but I don't really want to spray that kind of verbosity across a bunch of places in the doc, since this is really general knowledge about what "interaction strength" means, not something specific to `drawByStrength()` or any other specific method.  But maybe I'm being too picky, and should go with the more verbose form?

In the InteractionType class documentation (section 24.8) I added a clarification early on:

> Note that a receiver will never be an exerter of an interaction upon itself; a given individual is never both receiver and exerter in the same interaction.

and then strengthened the existing statement in that class documentation later:

> Second, this distance is compared to the maximum distance for the interaction type; if it is beyond that limit, the interaction strength is always zero (and it is also always zero for the interaction of an individual with itself, since a given individual is never both receiver and exerter, as mentioned above).

So, hopefully that also makes things a bit more clear.  But I'd appreciate feedback on the first change.

**Comment by petrelharp** [comment]
I agree, the `(non-receiver)` caveat seems awkward. Maybe it's good enough, but I'd vote to add your suggestion:
```
The probability of drawing particular individuals is proportional to the strength of interaction they exert upon receiver (which is zero for receiver itself).
```
although not strongly - either is fine.

**Comment by bhaller** [comment]
OK, this is fixed (in the `smooth` branch, to be merged later).  It was a useful exercise; some methods of InteractionType were already clear about this, but the doc for four of them needed improvement in this area.  Thanks @jiseonmin and @petrelharp.  Closing.
