### ISSUE TITLE
4.1 Memory Issue

### ISSUE THREAD

**Issue by ans6160** [MesserLab/SLiM#422]
Hello, 

I mentioned this issue on the google group page and was directed here. As stated in the original post, 4.1 uses an extensive amount of memory when running a simulation that worked in the previous version (4.0.1) causing the app to crash when just running the simulation in the gui or crash my computer when trying to run it through R. Attached below are the necessary files and code.

[slim_v4.1_issue_scripts.zip](https://github.com/MesserLab/SLiM/files/13889307/slim_v4.1_issue_scripts.zip)

Thanks!
Abigail

**Comment by bhaller** [comment]
Hi @ans6160,

I've fixed this issue, I think, and the fix is pushed to GitHub.  It was a fairly bad bug, so I will post about it on slim-discuss in a moment; you can see further discussion there.  You can get the fix by building the GitHub head version of SLiM, or you can stay on SLiM 4.0.1.  Thanks for the very helpful bug report!

**Comment by bhaller** [comment]
Discussion here: https://groups.google.com/g/slim-discuss/c/bJP5d1dx848/m/DRMA0vL3AAAJ

**Comment by petrelharp** [comment]
Damn, this looks subtle.

**Comment by ans6160** [comment]
Thank you! For now I will stay on 4.0.1.

**Comment by bhaller** [comment]
> Damn, this looks subtle.

An unintended side effect of a rearchitecture of MutationRun to support parallel SLiM.  A bit subtle if one has not already lived through the whole soap opera up to this point, yes.  :->  The fix is rather ugly, but I can't think of a better one offhand.  Might be a nice thing to talk through at some point, actually, but I know you're swamped right now, and so am I...
