### ISSUE TITLE
4.2.2 release process

### ISSUE THREAD

**Issue by bhaller** [MesserLab/SLiM#443]
Hey folks.  OK, I have accepted reality and closed #442, giving up on the idea of a 4.2.1 fc 3 release, which was just causing confusion and difficulty.  Here is a new issue to track release 4.2.2.  The 4.2.2 release will contain the fix for the SLiMgui crash that needs immediate fixing, and also contains an opportunistic fix for a VCF reading bug.

The `v4.2.2` tag has been created, but the Release on GitHub does not yet exist; I will post here when it does.  The `SLiM.spec` file has been updated to this release, @bryce-carson.

So, you all know the drill:

- [x] a new conda package (me)
- [x] a new macOS installer (me)
- [x] a new Arch installer (@grahamgower)
- [x] a new Windows pacman installer (@rdinnager)
- [x] Linux installers (@bryce-carson)

Hopefully this is the last bug-fix release 4.2 will need; it is a huge pain doing this while in transit.  Onward and upward!

**Comment by bryce-carson** [comment]
The Copr build has been submitted.

The EPEL 8 and RHEL 8 builders have been deselected for this build, since there is still the issue with the linker on RHEL 8 systems (#440).

For future reference, @bhaller, here are some instructions on submitting a build on Copr, since you do have access. _When the release is a clean new tag_, like this one, it is quite simple. When there is a need for a patch to the software, which is Fedora specific, is when there are more complexities that require my understanding. I think the RPM spec file is mature enough that you should be able to submit simple builds like this without my input, but I'm always happy to flip the switches for you when the need for a release isn't emergent like this one. You don't _need_ to do this process today, I've done it. The instructions are for reference, should you want or need to flip the switch on an emergent basis such as this in the future.

1. Log in to Copr and navigate to [the project page.](https://copr.fedorainfracloud.org/coprs/bacarson/SLiM-Selection_on_Linked_Mutations/)
2. Click the _Builds_ tab near the top of the main content, just below the project title header.
3. Press the _New Build_ button.
4. Select the _SCM_ (source control management) source type in the first box of the build wizard (the _Select the source type_ step).
5. In the _Provide the source_ step of the wizard, Git is the default source type and does not need to be changed. Insert the _Clone url_ of SLiM---`https://github.com/MesserLab/SLiM.git`---and type the tag name in the _Committish_ field; in this case that was `v4.2.2`.
6. Change nothing in the third step of the wizard.
7. In the fourth step of the wizard, deselect the "epel-8-x86_64" and "rhel-8-x86_64" chroots until the issue mentioned above is resolved.
8. Press the _Build_ button.

[![Copr build status](https://copr.fedorainfracloud.org/coprs/bacarson/SLiM-Selection_on_Linked_Mutations/package/SLiM/status_image/last_build.png)](https://copr.fedorainfracloud.org/coprs/bacarson/SLiM-Selection_on_Linked_Mutations/package/SLiM/)

**Comment by bhaller** [comment]
Thanks @bryce-carson!  I have some instructions that you gave me before, but these look more complete.  I'll get used to it over time; it would be good for me to do the next one.  :->

**Comment by bhaller** [comment]
OK @bryce-carson, from the project page it looks like the build finished and succeeded, so I've checked off your box in the to-do list.  Thanks!

**Comment by bhaller** [comment]
OK, the release is now live on GitHub: https://github.com/MesserLab/SLiM/releases/tag/v4.2.2.  @rdinnager

**Comment by bhaller** [comment]
And the release is now announced on slim-discuss: https://groups.google.com/g/slim-discuss/c/Z3sJ4d4nyEw.

**Comment by grahamgower** [comment]
Thanks @bhaller. The Arch package has been updated. Say hi to the folks in Copenhagen for me!

**Comment by bhaller** [comment]
> Thanks @bhaller. The Arch package has been updated. Say hi to the folks in Copenhagen for me!

Sure!  Who do you know here?  Anyhow, thanks for the quick turnaround!

**Comment by grahamgower** [comment]
> Sure! Who do you know here?

Until last year I was a postdoc in Fernando Racimo's group sitting across from Martin Petr. So I know most of the popgen/bioinfo folks there. :)

**Comment by bhaller** [comment]
The pacman installer has cleared, so the 4.2.2 release is done.  Thanks everybody!  Hopefully this is the last of the 4.2.x series!  :-O
