### ISSUE TITLE
Linux recipe to open an external pdf viewer (re: manual section 14.8)

### ISSUE THREAD

**Issue by grahamgower** [MesserLab/SLiM#46]
Hi Ben,

I've made two recipes for you to look at, which have small diffs to [the current recipe](https://github.com/MesserLab/SLiM/blob/303030d/SLiMgui/Recipes/Recipe%2014.8%20-%20Live%20plotting%20with%20R%20using%20system().txt). The first uses `xdg-open`, which opens the pdf in the application that is associated with the pdf MIME type. This must be done after the pdf is created. As you indicate in section 14.8 of the SLiM manual, many pdf viewers will not check for file changes to refresh the pdf canvas.

With `mupdf` (my preferred pdf viewer), I can hit `r` within the application (or send a HUP signal) to refresh the canvas from the pdf file. If I do this repeatedly while SLiM is running the recipe, then mupdf sometimes exits because the pdf is invalid (there is a race with the R script). So, I've included a second recipe, specific to mupdf, which sends the HUP signal to mupdf after the R script has updated the pdf. It should be easily adapted to other pdf viewers, assuming they also have a way to update the pdf canvas.

-Graham

[14.8-gg1.txt](https://github.com/MesserLab/SLiM/files/3380727/14.8-gg1.txt)
[14.8-gg2.txt](https://github.com/MesserLab/SLiM/files/3380728/14.8-gg2.txt)

**Comment by bhaller** [comment]
Hi Graham.  This is great, thanks.  I'll include these recipes in the Recipes download archive, and mention them in the manual, with credit to you, if that's OK.  :->  There won't be any corresponding changes in the GitHub repo, so I'll just close this issue once I've done this work.

BTW, since I gather you're a Linux user with some development experience, let me ask you: do you have any experience with Qt and/or qmake?  If so, I could really use a hand with something.  :->  Let me know if you think you could help.

**Comment by grahamgower** [comment]
Hi Ben,

You're welcome to archive the recipes, and credit me (or not) as appropriate.

I don't have any specific experience with Qt or qmake, and tend to shy away from C++ (as opposed to C). But I have been developing on Linux for nearly 20 years, so you're welcome to mail me anyway, perhaps I can be of use.

-G

**Comment by bhaller** [comment]
Thanks Graham.  This issue is resolved (I decided to add your recipes to the SLiM-Extras repository; they are there now), so I'm closing this issue.
