### ISSUE TITLE
Unable to close pop-up graphs in SLiMgui Windows WSL. 

### ISSUE THREAD

**Issue by smolxd** [MesserLab/SLiM#461]
Hello, I am currently using SLiM 4.2.2 on Ubuntu 22.04.4 LTS using WSL. When I run a simulation and open the population pop-up visualization, I am unable to interact with the pop-up tab using my mouse and hence am unable to close it. All libraries have been updated to the latest and no error logs appear on my terminal. Thank you!

<img width="960" alt="bug1" src="https://github.com/user-attachments/assets/44d82cef-e95c-46c2-99f0-3eabd7264cc7">

I noticed that the issue has also been raised prior https://github.com/MesserLab/SLiM/issues/408 . Are there any workthroughs for this situation?

**Comment by bhaller** [comment]
Hi!  It seems like it might be a problem with SLiMgui specifically under the WSL, and perhaps specifically with Ubuntu 22.04 under the WSL.  It is probably an incompatibility between Qt and that environment (i.e., a bug in Qt).  One possible workaround that someone has mentioned to me is launching SLiMgui via the terminal, rather than by double-clicking it in the desktop environment.  Can you try that and let me know here whether it worked or not?  That would be very helpful to know.  Also, of course note that you can run SLiMgui natively on Windows, so perhaps you can avoid running it under the WSL?  Or you could even consider down-grading to Ubuntu 20.04, which I think works.  You say you're running the latest libraries; if you open the About panel inside SLiMgui, what version of Qt does it state in that panel?

Sorry for the problems.  It's hard when the widget kit has a bug, which is, as far as I can tell, what is happening here.  At some point SLiMgui needs to switch to being based on Qt6 instead of Qt5; but that will require C++17, so it will cause its own problems.  :-<  Please let me know anything that you find out about this bug.  Thanks!

**Comment by smolxd** [comment]
> Hi! It seems like it might be a problem with SLiMgui specifically under the WSL, and perhaps specifically with Ubuntu 22.04 under the WSL. It is probably an incompatibility between Qt and that environment (i.e., a bug in Qt). One possible workaround that someone has mentioned to me is launching SLiMgui via the terminal, rather than by double-clicking it in the desktop environment. Can you try that and let me know here whether it worked or not? That would be very helpful to know. Also, of course note that you can run SLiMgui natively on Windows, so perhaps you can avoid running it under the WSL? Or you could even consider down-grading to Ubuntu 20.04, which I think works. You say you're running the latest libraries; if you open the About panel inside SLiMgui, what version of Qt does it state in that panel?
> 
> Sorry for the problems. It's hard when the widget kit has a bug, which is, as far as I can tell, what is happening here. At some point SLiMgui needs to switch to being based on Qt6 instead of Qt5; but that will require C++17, so it will cause its own problems. :-< Please let me know anything that you find out about this bug. Thanks!

Hi, thank you for the prompt reply. Yes, I have tried running it through the terminal and it yielded the same bug. I have tried running it on windows and encountered the same problem as the following reported issue: https://github.com/MesserLab/SLiM/issues/462

Below I have provided the about panel from my application:
<img width="960" alt="image" src="https://github.com/user-attachments/assets/cdd220d9-813f-4e08-8ed3-278c95fb02e3">

Is the only workaround to downgrade the Ubuntu version? Thank you very much for your help

**Comment by bhaller** [comment]
> Is the only workaround to downgrade the Ubuntu version? Thank you very much for your help

Hi @smolxd.  The causes of this problem are so poorly understood that I actually don't know whether downgrading to Ubuntu 20.04 would even fix the problem.  It may be a hardware-specific incompatibility in Qt across all versions of Ubuntu; I really have no idea.  Sorry; it is very hard to figure out what to do with bugs inside the widget kit, especially when they occur in environments that I'm not running in myself.  If you do try downgrading, I'd very much like to hear how that goes; please post here.

**Comment by bhaller** [comment]
OK, progress.  The GitHub head version of SLiM can now build SLiMgui against Qt6 as well as Qt5, and my hope is that Qt6 will just magically fix this problem.  CMake will automatically detect Qt6, and prefer it to Qt5, so you can leave Qt5 installed if you wish, and just additionally install Qt6.  Then build SLiMgui from current GitHub sources, run it, check the About panel to confirm that it was built against Qt6 (it says the Qt version in that panel), see if the bug is fixed, and report back here.  @smolxd, it would be great if you could try this out.  If anybody else is also lurking here who could try it, that would be very helpful.  Thanks!

**Comment by smolxd** [comment]
> Hey @smolxd, I'm putting together a SLiM 4.3 release now, and I'd really like to know whether Qt6 fixes this problem for you. Thanks!

Hi, sorry for the late reply.

The problem has been solved. Looking forward for the new release!

**Comment by smolxd** [comment]
Hi, sorry for the late reply.

The problem has been solved. Looking forward for the new release!

**Comment by bhaller** [comment]
Ah, that is fantastic news, thanks!

**Comment by bhaller** [comment]
By the way, @smolxd, if you'd like to be added to the credits in the SLiM manual, please let me know your real name.  You can email it to me at bhaller mac com if you don't want to post it here.  :->
