### ISSUE TITLE
Mention of Qt version hard-coded in string in CMakeLists.txt

### ISSUE THREAD

**Issue by bryce-carson** [MesserLab/SLiM#472]
https://github.com/MesserLab/SLiM/blob/f872f3df812df4da4e18515af43d79e2d78bf33c/CMakeLists.txt#L91

**Comment by bhaller** [comment]
Just fixed this.  The fix comes after the 4.3 release was tagged, though.  I could put a patched SLiM.zip into the release, containing this post-tag fix, if you want me to @bryce-carson; that seems harmless.  Otherwise I'll leave it as it is, which means the CMakeLists.txt that your install script operates on will _not_ have this fix in it, unless you ask me to make it so.  Thanks!

**Comment by bryce-carson** [comment]
> Just fixed this.  The fix comes after the 4.3 release was tagged, though.  I could put a patched SLiM.zip into the release, containing this post-tag fix, if you want me to @bryce-carson; that seems harmless.  Otherwise I'll leave it as it is, which means the CMakeLists.txt that your install script operates on will _not_ have this fix in it, unless you ask me to make it so.  Thanks!

No, it's okay. It is only a typo. :)
