### ISSUE TITLE
QtSLiM font sizes and missing symbols

### ISSUE THREAD

**Issue by grahamgower** [MesserLab/SLiM#84]
This is what QtSLiM looks like for me. (Both qmake and cmake builds look identical now)
![slim-fonts](https://user-images.githubusercontent.com/8665077/78747362-851cb700-7969-11ea-9548-a94090f65a06.png)

1. In the recipes, there are some square symbols after python recipes (e.g. after recipe 17.10). Usually when I've seen this symbol in a web browser, it means I need to install more fonts to see the character properly. Any clue what I'm missing to make the symbol appear here?

2. I've increased the font size in the preferences. But it seems that only the font size in the input/output panels are increased. The menus, tooltip texts, and more importantly the help text, are still quite small on my laptop screen. I've read that at least the Qt menu fonts are not directly under the programmer's control (annoyingly, these are set by the monitor DPI). But maybe there's something that can be done for the tooltips and help text?

**Comment by grahamgower** [comment]
Starting QtSLiM with `QT_SCALE_FACTOR=1.3 qtslim`, everything is scaled up. 1.3 seems about right for my bad eyes. But now the icons (e.g. play, profile, recycle) look jagged/blurry. Maybe these icons could be substituted with vector graphic equivalents?
![slim-fonts-2](https://user-images.githubusercontent.com/8665077/78748748-117ca900-796d-11ea-80a8-16e2d0d1eb4b.png)

**Comment by grahamgower** [comment]
The best result for me so far is to start QtSLiM with `QT_FONT_DPI=128 qtslim`. This seems to scale the fonts, but not the icons.
![slim-fonts-3](https://user-images.githubusercontent.com/8665077/78750099-d5971300-796f-11ea-8f50-306eb2997319.png)

**Comment by bhaller** [comment]
> 1. In the recipes, there are some square symbols after python recipes (e.g. after recipe 17.10). Usually when I've seen this symbol in a web browser, it means I need to install more fonts to see the character properly. Any clue what I'm missing to make the symbol appear here?

This is the snake emoji, 🐍, which people often use to symbolize Python.  It appears correctly for me on Ubuntu 18.04 LTS, as well as on macOS, without (to my knowledge) any additional font packages having been installed.

> 2. I've increased the font size in the preferences. But it seems that only the font size in the input/output panels are increased. The menus, tooltip texts, and more importantly the help text, are still quite small on my laptop screen. I've read that at least the Qt menu fonts are not directly under the programmer's control (annoyingly, these are set by the monitor DPI). But maybe there's something that can be done for the tooltips and help text?

It's quite possible that I have made everything too small by default.  It's quite hard to tell, because I regularly use four different monitors in my work, at QtSLiM looks different in size/scale on each.  I'm not really sure what to do about this, but yes, it's an issue to be considered more carefully before release.

**Comment by bhaller** [comment]
> Starting QtSLiM with `QT_SCALE_FACTOR=1.3 qtslim`, everything is scaled up. 1.3 seems about right for my bad eyes. But now the icons (e.g. play, profile, recycle) look jagged/blurry. Maybe these icons could be substituted with vector graphic equivalents?

Yeah, wouldn't that be nice?  :->  SLiMgui on macOS uses PDFs for all button images, which makes things nice and smooth and resolution-independent.  Qt, unfortunately, has no support for displaying PDFs; it's a huge hole in their APIs.  To try to get things to look nice, the button images in QtSLiM are actually high-res images – much higher than screen resolution, generated from the SLiMgui PDFs.  However, Qt insists on displaying them in an ugly blocky form on high-res screens or when magnified.  I have not yet figured out the fix for that; there are various settings for displaying images with antialiasing and so forth, but none of them seems to fix the problem.  So, yes, another issue that needs to be resolved before release, although I'm not presently sure how.

**Comment by bhaller** [comment]
> The best result for me so far is to start QtSLiM with `QT_FONT_DPI=128 qtslim`. This seems to scale the fonts, but not the icons.

Interesting.  Well, if nothing else works we can always suggest that to users as a way to scale the UI to fit their needs.  Thanks.

**Comment by grahamgower** [comment]
> This is the snake emoji, , which people often use to symbolize Python.
Ah, thanks. I installed the 'noto-fonts-emoji' Arch package and now it appears!

**Comment by grahamgower** [comment]
> It's quite possible that I have made everything too small by default.

I don't think that's the case. I suspect its more a local configuration issue. I've checked the settings for the font sizes in the three other gui apps I use, and they're all set manually, so I probably just didn't notice before.

There seems to be another more wide-ranging fix that can be applied too: I added `Xft.dpi: 120` to `~/.Xresources` and merged in the change with `xrdb -merge ~/.Xresources`. This applies to all X11 apps, including the window manager, not just Qt5 apps. (`QT_FONT_DPI` is Qt5 specific, I think).

Feel free to close this issue if you like. QtSLiM is both working and looking beautifully now!

**Comment by bhaller** [comment]
I'll keep it open for now, partly as an issue for the pixellated icons, partly as a doc bug (need to mention the fixes you've found in the doc when that gets written).  Thanks!

**Comment by bhaller** [comment]
@petrelharp @samchamper What do you think of the default font sizes in QtSLiM?  Do they seem well-matched with other Linux GUI apps?  (It's hard for me to judge, because I run Ubuntu on a high-res screen that... isn't very high res... and I run it under VirtualBox which I'm not sure correctly informs Ubuntu that the screen is high-res, etc.; so I don't really know what everything looks like on a normal Ubuntu/Debian system.)

**Comment by petrelharp** [comment]
Font sizes look good on my computer!
![Screenshot from 2020-04-08 21-19-06](https://user-images.githubusercontent.com/1046249/78857579-9f44ac80-79de-11ea-8f80-ea801a80bbeb.png)
![Screenshot from 2020-04-08 21-19-14](https://user-images.githubusercontent.com/1046249/78857582-a1a70680-79de-11ea-8208-39430824e061.png)

**Comment by bhaller** [comment]
> I'll keep it open for now, partly as an issue for the pixellated icons, partly as a doc bug (need to mention the fixes you've found in the doc when that gets written). Thanks!

The pixellated icons have been fixed, I believe; it should now look nice when on a high-res display (like a Retina display), and probably also when magnified using those command-line switches you explored, @grahamgower, although I didn't try that myself.  The doc bug has been taken care of, and it sounds like others are happy with the font sizes in the app.  So I'm going to close this bug now.  Thanks!
