### ISSUE TITLE
Drawer won't open in SLiMgui?

### ISSUE THREAD

**Issue by amanda128891** [MesserLab/SLiM#86]
My drawer won't open in SLiMgui. I've tried putting the window full screen, making the window the size of my screen, and manually adjusting the width of the window to be about half my screen and I still haven't seen the drawer. The button highlights blue after I click it, but nothing pops up.
My labmate showed me what the drawer looks like, so I'm sure mine has not worked yet.

**Comment by bhaller** [comment]
There are two common causes of this.  One: you are running too old a version of macOS.  SLiMgui is happiest when running against 10.13.x or later; I have not disabled the use of it against 10.11 or 10.12, since some people are unable to upgrade their machines for various reasons, but running against those old OS versions various glitches like this will be observed.  The recommended fix is, then, to upgrade, of course.

The other common cause is that there isn't enough space available on the screen for the drawer to open; macOS will refuse to open the drawer if there isn't room.  It sounds like you tried to address that, though; but if you're not sure, you might quit/restart the app, get the window to a good size, and then click the drawer button.

Please let me know how this goes, so I know whether I can close the issue, whether it requires more follow-up, etc.  Thanks!

**Comment by amanda128891** [comment]
Thanks for the quick reply. I believe my case is the OS (I have 10.12). I will definitely update if there could be some other issues down the road.
