### ISSUE TITLE
HDF5

### ISSUE THREAD

**Issue by bryce-carson** [MesserLab/SLiM#98]
It would be wonderful to have the ability to write object values to HDF5 without calling system() and needing extensive Eidos scripting to assign attributes to H5.

HDF5 has an extensive C library and interface, and the vectorized nature of Eidos would pair well with HDF and downstream R workflows.

Is this a feature we may be able to see sometime this year?

**Comment by bhaller** [comment]
I'm entirely unfamiliar with HDF5.  Could you provide some background information?

**Comment by bryce-carson** [comment]
Sure!HDF5 is the modern version of the Hierarchical Data Format. It's used widely throughout the sciences and and is also recommended by the HPC network I'm using (Compute Canada); the storage system I have access to is better suited to few, large files, rather than hundred of thousands of small ASCII files.https://www.hdfgroup.org/solutions/hdf5/That is the main website.An HDF5 file itself can be thought of like a filesystem within a file, and objects within it can even be addressed and grouped using POSIX (Unix) path names. It is very portable, working on all operating systems of note, and is well integrated with Python, R, and Fortran workflows.Here's an informal video from an ecologist  (3:57 runtime): https://youtu.be/q14F3WRwSck.Here's a formal introduction from a member of the HDF Group presented by Scot Breitenfeld at the Argonne Training Program for Extreme Scale Computing (33:54 runtime): https://youtu.be/eXL1Kf9uANI.What motivates my workflow to adopt HDF5 is the number of output files I am generating with my model. Previously, I was outputting an ASCII file at a regular generation interval to display all the frequencies and positions of the mutations in the model for the simulated populations. These became great in number, given replicates and a parameter sweep.Another obvious solution is to append to a single output file the data for each generation with writeFile (that is possible, yes?), but I can see the utility in support for native HDF output in SLiM.Thanks for the great support as always.If you'd like any more information I'll see what I can provide, but I am only just beginning to learn how to use HDF5 myself. I am writing an Eidos function for its use with system(), and hopefully that will be portable enough to include on the SLiMExtras GitHub repo.Regards,Bryce Carson.Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Ben Haller <notifications@github.com> Date: 2020-07-19  5:22 p.m.  (GMT-07:00) To: MesserLab/SLiM <SLiM@noreply.github.com> Cc: bryce-carson <bcars268@mtroyal.ca>, Author <author@noreply.github.com> Subject: Re: [MesserLab/SLiM] HDF5 (#98) 
I'm entirely unfamiliar with HDF5.  Could you provide some background information?

**Comment by bhaller** [comment]
Hmm.  Just looked into it a bit.  It looks like overkill to me.  It's a pretty big and complex library – a download of the source for it is 125 MB!  That means it couldn't possibly just be integrated into SLiM's code, so it would have to be an external link dependency.  We try very hard not to have any of those, to keep SLiM's installation issues to a minimum; this is why we don't have a dependency on Boost, GSL, tskit, etc.  There would have to be a *very* compelling reason for it to be worth adding an external dependency to SLiM.

This would also complicate SLiM's Eidos APIs considerably – every output method/function would need to have a way to output to HDF5 instead, with all of the additional API complexity that that would entail.  Again, there would have to be a *very* compelling reason to take on this additional complexity, especially for a feature that the large majority of users would be unlikely to use.

And it's not clear that these issues can't be solved in other ways.  As you note, you could append to existing files with writeFile() rather than generating a new file with every chunk of data you generate; that seems like it might be a better approach.  On the other hand, if you really want one file per chunk, you could probably write things out that way from SLiM and then, at the end of execution of each run, use some kind of post-processing tool to suck up all those files into HDF5 at that point in time.  That seems like it would be a pretty reasonable design, and I imagine tools already exist to do this kind of data importation, so it would probably be pretty straightforward.

That's my initial take.  Since you're the first person to request this, and it sounds like a big change with a lot of ramifications (changes to many Eidos APIs, changes to SLiM's external dependencies, etc.), I'm going to nix it for now, and close this issue.  But I'll be happy to reopen it if you can convince me; feel free to debate/discuss.  :->
