### ISSUE TITLE
order of operations for unary minus and exponents is surprising

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#99]
In Eidos, `- 2^2` is 4:
```
$ eidos <(echo "catn(- 2^2);")
4
```
but that is not what I expected, and that is not how it works in R:
```
> -2^2
[1] -4
```
or python
```
>>> -2**2
-4
```

... was this a design choice?

I hit this because I had `exp( - (x - x0)^2 )` for a fitness function, and it was doing the opposite to what I expected.

**Comment by bhaller** [comment]
Hmm.  Well, it wasn't a conscious choice.  The operator precedence table in Eidos derives from that in C, because the Eidos parser is derived from a C parser I modified.  But C doesn't have an exponentiation operator, so I added that to the language grammar, giving it a precedence higher than * / % (and also higher than the sequence operator, :, which I also added).  It looks like that choice doesn't match R; if I had noticed that, I would have done it differently.

However, it's also not **100%** clear that there is a right or wrong answer here, at least from a computer software perspective.  There are precedents for doing it the way Eidos does: https://en.wikipedia.org/wiki/Order_of_operations#Unary_minus_sign.  Now, am I embarrassed to claim Microsoft Excel as justification?  Yes – yes, I am.  The "bc" programming language is perhaps at least a slightly more prestigious precedent.  :->  (And it's interesting that it, too, derives its operator precedence from C and then adds in exponentiation; parallel evolution, perhaps?)  Maybe those precedents are all just wrong too; but it seems like perhaps there is just some ambiguity here, and the safest thing to do would be to use parentheses to guarantee the desired order of operations.  One can certainly assume that at some point this behavior has come to the attention of the engineers who work on these software packages, and they have chosen not to regard it as a bug.

One question – which may or may not be dispositive – is: Is this 100% absolutely wrong from the perspective of mathematics?  I.e. do you feel confident that if you sat down 1000 professional mathematicians in a room and asked them what -2^2 is, they would all say -4 without hesitation or caveat?

In any case, as I said above, if I had noticed this discrepancy at the time I would have followed R's lead.  The problem now is backward compatibility; there may be code out there that relies upon the current behavior, and which would change behavior if I were to change this in the language.  How much of a risk is that?  I really have no idea.  Probably fairly small, but still, changing language semantics on people is pretty dangerous, and if it bit even one SLiM user that would be pretty unfortunate.

Thoughts?

**Comment by bhaller** [comment]
I'm really surprised this got past me, since the R operator precedence table is of course available online (e.g., https://stat.ethz.ch/R-manual/R-devel/library/base/html/Syntax.html).  I guess it just never even occurred to me that it was an issue.  Sigh.

**Comment by petrelharp** [comment]
Well, I'm collecting some data: https://twitter.com/petrelharp/status/1285662498188865536

But, from [wikipedia](https://en.wikipedia.org/wiki/Order_of_operations#Unary_minus_sign), it notes that (a) the *binary* minus operator always works the other way, and (b) in "written or printed mathematics", -2^2 = -4 (which I agree with). Both those are very strong arguments in favor of -2^2 = -4, I think.

In particular, if unary and binary minus operators don't always agree, then `2 - 2^2` is not equal to `2 + (- 2^2)`.

**Comment by petrelharp** [comment]
Here's a [good point](https://twitter.com/PhillipCompeau/status/1285668093726007297): the "graph of y = - x^2" should look like a hill, not a valley (I think!).

**Comment by bhaller** [comment]
> Well, I'm collecting some data: https://twitter.com/petrelharp/status/1285662498188865536

Interesting.  Well, I voted for -4 so that I could see the answers so far.  Looks like -4 is actually the minority view so far!

> But, from [wikipedia](https://en.wikipedia.org/wiki/Order_of_operations#Unary_minus_sign), it notes that (a) the _binary_ minus operator always works the other way, and (b) in "written or printed mathematics", -2^2 = -4 (which I agree with). Both those are very strong arguments in favor of -2^2 = -4, I think.

I don't find the argument from binary minus compelling at all.  It is a different operator than unary minus, with a different precedence.

The argument from the standard convention in written/printed mathematics is far more compelling.

> In particular, if unary and binary minus operators don't always agree, then `2 - 2^2` is not equal to `2 + (- 2^2)`.

Indeed.  But notice that you're biasing the interpretation of the expressions by the way you add spaces.  If you write `2 + (-2 ^ 2)` it looks pretty different!  :->

Overall, my take as a programmer – which is very different from a mathematician! – is that languages vary widely in the precedence rules they give to operators.  I'm not sure that any two languages I'm fluent in has exactly the same precedence rules.  That is unfortunate, yes; but I'm not sure it's a *bug*.  Programmers get used to this, and either develop some kind of weird brain that instantly adjusts to fit the precedence rules of the language they're coding in (as I instinctively add semicolons at the end of every line when writing C/C++, but leave it off when writing R, mostly without ever thinking about it), or they parenthesize any expression where the order of operations seems at all unclear (which I what I usually do in all languages).  This is just life.

Now, the counterargument would be that that's fine for all the weird operators that programming languages use, but that standard mathematical operators should follow standard mathematical precedence rules.  And that makes good sense.

However, your poll so far suggests that even if those rules are objectively known and standard among professional mathematicians, that's not the case for other people.  So I'm not sure how binding that precedent really ought to be.  Eidos is not a language designed primarily for professional mathematicians.  :->

But again, if I could wave a magic wand and change this retroactively, I would.  Following R and mathematics would clearly be better.  I'm just not sure that it's worth breaking backward compatibility over.

**Comment by bhaller** [comment]
> Here's a [good point](https://twitter.com/PhillipCompeau/status/1285668093726007297): the "graph of y = - x^2" should look like a hill, not a valley (I think!).

Presumably the result one gets from this depends on the graphing program one uses?  Since we've already seen that some software follows the same rules as Eidos?  I don't know whether GNU bc supports graphing (probably not), but if it does, presumably the graph it produced would look like a valley...?

**Comment by petrelharp** [comment]
Hm, but look at this poll: https://twitter.com/petrelharp/status/1285666798306766849

which gets at what we want better...

**Comment by bhaller** [comment]
> Hm, but look at this poll: https://twitter.com/petrelharp/status/1285666798306766849
> 
> which gets at what we want better...

Well, again I voted for the "right" answer (i.e., your answer) to see the result.  But really, if I were writing this in code I probably would use the fully parenthesized version to remove the ambiguity.  That's what my programmer brain tells me to do.  :->

**Comment by bhaller** [comment]
In any case, at this point it is what it is, so what I'd like to hear is not so much an argument about why the behavior is wrong, but an argument about why changing it, and breaking backward compatibility, is better than leaving it alone.

**Comment by bhaller** [comment]
Well, I've been reflecting on this for a while.  I think it should be changed.  A couple reasons:

- The common case where someone will have an equation like -x^y will be exactly the case where you ran into this: some kind of Gaussian function.  And in this case, typing the standard mathematical notation into Eidos will produce the wrong result.  Since working with Gaussians is pretty common, this is likely to bite people.  Indeed, I searched through the SLiM manual and there are several places where this would have bitten me if I hadn't happened to use a binary minus instead of a unary minus, with a function like w-x^y.

- The behavior provided by Eidos now, that -x^y is (-x)^y, seems not very useful mathematically, since it's undefined and returns NAN for all non-integer y; it's a weird function that increases quadratically but flips sign, defined only for the integers.  One sometimes sees a use for (-1)^y, converting even/odd values of y into alternating signs, but for other x it doesn't strike me as very useful.  This means that it is quite unlikely that any existing SLiM code is relying on the current semantics; more likely is that existing SLiM code wants the R/Python semantics, and either the author of that code noticed the problem and parenthesized to avoid it, or didn't notice the problem and has a bug.  Looking through the code in the manual, there was no instance where I intentionally raised a negative number to a power.  It's just not a common thing.  (Of course, it could be that x is negative and one wants to do -x^y to make x positive before exponentiation; but that also seems unlikely to me...?)

- Given that Eidos is explicitly based on R, this discrepancy will surprise people, and may even bite people who directly copy/paste code from R into Eidos, which sometimes works with little-to-no modification.  If Eidos were more independent linguistically, it might not matter as much, but since it styles itself as a direct derivative of R, it ought to match R wherever that is easy to achieve.  Similarly, although C's choices regarding operator precedence were flawed, those flaws were not fixed in C++, deliberately, because of the heritage of C++ from C and the desire for code to be maximally interoperable.

So, I assume you concur?

**Comment by petrelharp** [comment]
Wow, now I totally agree. I was pondering more before having an opinion, but you did better pondering. I was already leaning in this direction, but hadn't realized how uncommon it would be for someone to really want (-x)^y.

I can try a GitHub search for affected code, too.

**Comment by petrelharp** [comment]
> Given that Eidos is explicitly based on R, this discrepancy will surprise people

Yes: to keep it the way it is you'd need to say " it's based on R, except for the order of ..."

**Comment by bhaller** [comment]
> > Given that Eidos is explicitly based on R, this discrepancy will surprise people
> 
> Yes: to keep it the way it is you'd need to say " it's based on R, except for the order of ..."

Yeah.  There are already tons of those, of course; but best to eliminate them where one can, especially where they give you different actual results rather than just a syntax error.

So OK, we are agreed.  Should be a reasonably straightforward fix, hopefully, although changes to the parser are always a little scary.

**Comment by petrelharp** [comment]
> I can try a GitHub search for affected code, too.

Turns out this isn't do-able with a github search (no regexps).

**Comment by petrelharp** [comment]
Good luck... scary!

**Comment by bhaller** [comment]
@petrelharp, this is done and passes tests.  Want to confirm that it now behaves as you expected it to, for your model?

**Comment by petrelharp** [comment]
Yep!!!
